### ISSUE TITLE
Game Profiler does not work with Vulkan

### ISSUE THREAD

**Issue by herocrab** [stride3d/stride#1020]
**Release Type**: Official 4.0

**Version**: 4.0.1.1400

**Platform(s)**: Windows

**Describe the bug**
Game Profiler does not work with Vulkan. I remove the Api reference in .csproj and it works no problem. Looks like it's a command list thing, see error below.

**To Reproduce**
1. Attempt to attach game profiler to game running with Vulkan.

**Expected behavior**
Expect GameProfiler to work with all renderer API.

[Game]: Error: Unexpected exception. System.InvalidOperationException: Can't use WriteDiscard on Graphics API that doesn't support renaming
   at Stride.Graphics.CommandList.MapSubresource(GraphicsResource resource, Int32 subResourceIndex, MapMode mapMode, Boolean doNotWait, Int32 offsetInBytes, Int32 lengthInBytes) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\Vulkan\CommandList.Vulkan.cs:line 1280
   at Stride.Graphics.FastTextRenderer.End(GraphicsContext graphicsContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\FastTextRenderer.cs:line 196
   at Stride.Profiling.GameProfilingSystem.Draw(GameTime gameTime) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Engine\Profiling\GameProfilingSystem.cs:line 414
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameSystemCollection.cs:line 125
   at Stride.Games.GameBase.Draw(GameTime gameTime) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 792
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 639
   at Stride.Games.GameBase.RawTickProducer() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 590

**Comment by sasvdw** [comment]
Still open on **Stride 4.3.0.2507** (Windows, `StrideGraphicsApi=Vulkan`, .NET 10). Two data points worth adding.

**Repro:** build any project with `<StrideGraphicsApi>Vulkan</StrideGraphicsApi>` and either press **F7** (`GameProfilingSystem` → instant crash) or call `DebugTextSystem.Print(...)` every frame (HUD text renders only partially).

### 1. This isn't just the profiler — it breaks every `FastTextRenderer` consumer, including `DebugTextSystem`

`DebugTextSystem.Draw` renders through the same `FastTextRenderer.Begin`/`DrawString`/`End` path, so any on-screen `DebugText.Print(...)` overlay is affected too. The two consumers just fail differently:
- **`GameProfilingSystem`** (F7 GPU profiler) → **hard crash** (stack below).
- **`DebugTextSystem`** (general debug HUD) → **soft failure**: glyphs/lines are intermittently dropped or corrupted — the overlay renders only partially, because the VB map silently doesn't take.

Common root cause is the one already identified here and in #602: `FastTextRenderer.End()` maps its dynamic vertex buffer with `MapMode.WriteDiscard`, which Vulkan rejects (no buffer renaming).

### 2. On 4.3 it's now a native access violation, not the managed exception from the original report

The 2021 report shows `InvalidOperationException: Can't use WriteDiscard on Graphics API that doesn't support renaming`. On 4.3.0.2507 it surfaces as a native `0xC0000005` inside `FastTextRenderer.End`:

```
Fatal error. 0xC0000005
   at Stride.Graphics.FastTextRenderer.End(Stride.Graphics.GraphicsContext)
   at Stride.Profiling.GameProfilingSystem.Draw(Stride.Games.GameTime)
   at Stride.Games.GameSystemCollection.Draw(Stride.Games.GameTime)
   at Stride.Games.GameBase.RawTick(System.TimeSpan, Int32, Single, Boolean)
   at Stride.Games.GameBase.RawTickProducer()
```

(The 4.2 `fix(graphics): Stop FastTextRenderer VB clobbering` changed the failure mode but didn't resolve the Vulkan case.)

### Suggested fix direction

Replace the `WriteDiscard` map in `FastTextRenderer` with a Vulkan-safe buffer update — e.g. a rotating ring of dynamic buffers written with `MapMode.WriteNoOverwrite`, or `CommandList.UpdateSubresource`, selected via `GraphicsDevice.Features`/platform. Since both
  `DebugTextSystem` and `GameProfilingSystem` funnel through this one method, a single fix restores the debug-text overlay **and** the GPU profiler on Vulkan.

**Workaround for others:** ImGui-style overlays render through their own buffers and are unaffected; on the engine side, gate/disable `GameProfilingSystem` on Vulkan to avoid the hard crash.
