### ISSUE TITLE
Cant build / run any stride application on macOS machine

### ISSUE THREAD

**Issue by coman3** [stride3d/stride#1061]
**Release Type**: Official Release

**Version**: 4.1.0.1459-beta

**Platform(s)**: macOS

**Describe the bug**
Execution of build through Visual Studio for Mac results in error:
```
/Users/lachlan/.nuget/packages/stride.core.assets.compilerapp/4.1.0.1459-beta/buildTransitive/Stride.Core.Assets.CompilerApp.targets(5,5): Error MSB3073: The command "mono "/Users/lachlan/.nuget/packages/stride.core.assets.compilerapp/4.1.0.1459-beta/buildTransitive/../lib/net5.0-windows7.0/Stride.Core.Assets.CompilerApp.exe"  --disable-auto-compile --project-configuration "Release" --platform=Windows --project-configuration=Release --compile-property:StrideGraphicsApi=Direct3D11 --output-path="/Users/lachlan/Desktop/CSharpBeginner/Bin/macOS/Release/osx-x64/data" --build-path="/Users/lachlan/Desktop/CSharpBeginner/CSharpBeginner.macOS/obj/stride/assetbuild/data" --package-file="/Users/lachlan/Desktop/CSharpBeginner/CSharpBeginner.macOS/CSharpBeginner.macOS.csproj" --msbuild-uptodatecheck-filebase="/Users/lachlan/Desktop/CSharpBeginner/CSharpBeginner.macOS/obj/x64/Release/osx-x64/stride/assetcompiler-uptodatecheck"" exited with code 2. (MSB3073) (CSharpBeginner.macOS)
```
(Notice how platform is "windows" despite building on a mac.
**To Reproduce**
1. Create new stripe project on Windows machine through the Stripe UI (ensure you select macOS and Windows as a platform)
2. Ensure it builds and runs on windows
3. Copy assets over to macOS machine ensuring to remove all bin, obj and .vs folders
4. Open project in Visual Studio for Mac
5. Build macOS project

**Expected behavior**
The project builds

**Log and callstacks**
**Additional context**
If building the macOS project on windows first and attempting to run through macos using `dotnet run projectname.macos.dll` i am presented with the following error as well:
```
Unhandled exception. System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Stride.Rendering.BackgroundCubemapShaderKeys' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Stride.Core.Native.NativeInvoke' threw an exception.
 ---> System.InvalidOperationException: Could not load native library libcore using CPU architecture x64.
   at Stride.Core.NativeLibraryHelper.PreloadLibrary(String libraryName, Type owner) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Native\NativeLibraryHelper.cs:line 98
   at Stride.Core.Native.NativeInvoke..cctor() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Native\NativeInvoke.cs:line 24
   --- End of inner exception stack trace ---
   at Stride.Core.Native.NativeInvoke.Setup() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Native\NativeInvoke.cs:line 50
   at Stride.Native.Module.Initialize() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Native\NativeInvoke.cs:line 46
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.DataSerializers.Stride_GraphicsSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.RuntimeHelpers._RunClassConstructor(RuntimeType type)
   at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(RuntimeTypeHandle type)
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.Serialization.AssemblyScan.Stride_EngineAssemblyScan.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
   at Stride.Core.DataSerializers.CSharpBeginner_macOSSerializerFactory.Initialize()
   at .cctor()
   --- End of inner exception stack trace ---
zsh: abort      dotnet CSharpBeginner.macOS.dll
```

**Comment by manio143** [comment]
Two notes from me: make sure the RuntimeIdentifier is properly set for the executable project - this is used to include the correct native libs; when running on Linux using `dotnet run` I had library errors unless I specifically set the `LD_LIBRARY_PATH` to point the loader at the libs location - I'm not sure what's the story like for Mac wrt to things like that.

**Comment by coman3** [comment]
Would you mind providing an example on how to go about this for Linux? I assume its relatively similar to macOS and I can probably look further into it then.

I think the primary things missing / are confusing for me are:
- When running on macOS where would the required libraries be located? 
- Is there any dependencies I might have to install for execution?
- Shouldn't the RuntimeIdentifier be set on execution when running on said platform - for example macos-x64 would be default on macOS no?

Sorry for the questions here, just trying to get a project to run on macOS with very little documentation on the topic 😅

If i do manage to get this working i do intend on submitting a PR for documentation to try and help anyone else in the same boat as my self.

**Comment by manio143** [comment]
I have a video on configuring Stride with Vulkan to run on Linux here: https://www.youtube.com/watch?v=BoHEASoQvu8 (I get the game to run at the very end).
But to answer your questions specifically:

* All the libraries should be properly copied to the output folder (usually `/bin/Debug/<rid>/`) as long as you have the RuntimeIdentifier set
* If you're compiling the game with `SelfContained` property (set in csproj of executable) then the dotnet runtime will be included, otherwise you'd have to have it installed on macOS. Other than that you'll need graphics drivers for the selected graphics API (for me when compiling for Vulkan I had to install some package to verify my device has support for it) - usually this should already be in the system I believe.
* The RID isn't set to the platform - if it's not set you're effectively compiling a portable project - meaning no platform specific dependencies. So in this case it has to be specified. I checked the default project template for macOS and it should already be set. If not you can always add it explicitly when building `dotnet build -r osx-x64`.
