### ISSUE TITLE
Asset compilation fails when configuration section references asset

### ISSUE THREAD

**Issue by johang88** [stride3d/stride#1063]
**Release Type**: GitHub

**Version**: master

**Platform(s)**: Windows

**Describe the bug**
Asset compilation fails with the error `[AssetCompiler] Unhandled exception. Exception: InvalidOperationException: Could not find asset ""ASSET URL"" for bundle default` when implementing a custom configuration setting that references an asset.

I have also noted that the asset does not seem to be included in the dependencies and thus not compiled at all if for example a `UrlReference<T>` is used instead and no other assets reference it.

**To Reproduce**
See https://github.com/johang88/StrideConfigurationReference

1. Create custom configuration implementing `Stride.Data.Configuration`
2. Add a property referencing an asset type
3. Add the configuration section in the GameSettings object in game studio
4. Link the asset reference in game studio.
5. Asset compilation will now fail

**Expected behavior**
I expect the asset compilation to be successful

**Log and callstacks**
``` 
1>info 0.011s: [AssetCompiler] BuildEngine arguments: --disable-auto-compile --project-configuration Debug --platform=Windows --project-configuration=Debug --compile-property:StrideGraphicsApi=Direct3D11 --output-path=C:\Users\johan\Documents\Stride Projects\StrideConfigurationReference\Bin\Windows\Debug\win-x64\data --build-path=C:\Users\johan\Documents\Stride Projects\StrideConfigurationReference\StrideConfigurationReference.Windows\obj\stride\assetbuild\data --package-file=C:\Users\johan\Documents\Stride Projects\StrideConfigurationReference\StrideConfigurationReference.Windows\StrideConfigurationReference.Windows.csproj --msbuild-uptodatecheck-filebase=C:\Users\johan\Documents\Stride Projects\StrideConfigurationReference\StrideConfigurationReference.Windows\obj\Debug\win-x64\stride\assetcompiler-uptodatecheck
1>info 0.012s: [AssetCompiler] Starting builder.
1>EXEC : warning 1.478s: [YamlAssemblyRegistry] Assembly [SDL2-CS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null] has not been processed by assembly processor with --serialization flags. [DataContract] aliases won't be available.
1>EXEC : warning 2.132s: [YamlAssemblyRegistry] Assembly [SDL2-CS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null] has not been processed by assembly processor with --serialization flags. [DataContract] aliases won't be available.
1>info 2.170s: [AssetCompiler] Build finished in 839 steps. Command results: 0 succeeded, 839 up-to-date, 0 failed, 0 not triggered due to previous failure.
1>info 2.170s: [AssetCompiler] Build is successful.
1>info 2.194s: [AssetCompiler] Generate bundles: Scan assets and their dependencies...
1>info 2.195s: [AssetCompiler] Generate bundles: Assign assets to bundles...
1>EXEC : error 2.315s: [AssetCompiler] Unhandled exception. Exception: InvalidOperationException: Could not find asset Sphere (2) for bundle default
1>   at Stride.Core.Assets.CompilerApp.BundlePacker.CollectBundle(DatabaseFileProvider databaseFileProvider, ResolvedBundle resolvedBundle, String assetUrl) in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\BundlePacker.cs:line 358
1>   at Stride.Core.Assets.CompilerApp.BundlePacker.CollectBundle(DatabaseFileProvider databaseFileProvider, ResolvedBundle resolvedBundle, String assetUrl) in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\BundlePacker.cs:line 370
1>   at Stride.Core.Assets.CompilerApp.BundlePacker.Build(Logger logger, PackageSession packageSession, Package rootPackage, String indexName, String outputDirectory, ISet`1 disableCompressionIds, Boolean useIncrementalBundles, List`1 bundleFiles) in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\BundlePacker.cs:line 152
1>   at Stride.Core.Assets.CompilerApp.PackageBuilder.BuildMaster() in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\PackageBuilder.cs:line 169
1>   at Stride.Core.Assets.CompilerApp.PackageBuilder.Build() in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\PackageBuilder.cs:line 57
1>   at Stride.Core.Assets.CompilerApp.PackageBuilderApp.Run(String[] args) in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\PackageBuilderApp.cs:line 304
1>System.InvalidOperationException: Could not find asset Sphere (2) for bundle default
1>   at Stride.Core.Assets.CompilerApp.BundlePacker.CollectBundle(DatabaseFileProvider databaseFileProvider, ResolvedBundle resolvedBundle, String assetUrl) in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\BundlePacker.cs:line 358
1>   at Stride.Core.Assets.CompilerApp.BundlePacker.CollectBundle(DatabaseFileProvider databaseFileProvider, ResolvedBundle resolvedBundle, String assetUrl) in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\BundlePacker.cs:line 370
1>   at Stride.Core.Assets.CompilerApp.BundlePacker.Build(Logger logger, PackageSession packageSession, Package rootPackage, String indexName, String outputDirectory, ISet`1 disableCompressionIds, Boolean useIncrementalBundles, List`1 bundleFiles) in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\BundlePacker.cs:line 152
1>   at Stride.Core.Assets.CompilerApp.PackageBuilder.BuildMaster() in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\PackageBuilder.cs:line 169
1>   at Stride.Core.Assets.CompilerApp.PackageBuilder.Build() in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\PackageBuilder.cs:line 57
1>   at Stride.Core.Assets.CompilerApp.PackageBuilderApp.Run(String[] args) in C:\Users\johan\Documents\GitHub\stride\sources\assets\Stride.Core.Assets.CompilerApp\PackageBuilderApp.cs:line 304
```

**Comment by johang88** [comment]
Issue caused by `Prefab` not being included in the runtime types list in the game settings asset compiler.
