### ISSUE TITLE
Could not restore Stride.VisualStudio.Commands 4.1.0.1459-beta

### ISSUE THREAD

**Issue by AmbulantRex** [stride3d/stride#1113]
**Release Type**: Official Release

**Version**: 4.1.0.1459-beta

**Platform(s)**: Windows

**Describe the bug**
Visual Studio extension attempts to restore the Stride.VisualStudio.Commands nuget package necessary to function and is unable to do so. Latest plugin has been installed and reinstalled with no change in behavior.

**To Reproduce**
1. Load solution in VS that contains `.sdsl` files.
2. Go to Output -> Show output from: General

**Expected behavior**
Would expect the extension to be able to restore the appropriate version that has been installed.

**Log and callstacks**
Error initializing Stride command proxy: System.InvalidOperationException: Could not restore Stride.VisualStudio.Commands 4.1.0.1459-beta, this visual studio extension may fail to work properly without it. To fix this you can either build Stride.VisualStudio.Commands or pull the right version from nugget manually
   at Stride.VisualStudio.Commands.StrideCommandsProxy.<FindStrideSdkDir>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Stride.VisualStudio.StridePackage.<InitializeCommandProxy>d__19.MoveNext()

**Additional context**
- Visual Studio Community 2019, Version 16.10.4
- Windows 10 Pro, Version 10.0.19042
- .NET SDK 5.0.400

**Comment by AmbulantRex** [comment]
Seems like this is an issue with compatibility between Net5.0 and Net5.0-windows7.0.

```
Package Stride.VisualStudio.Commands 4.1.0.1459-beta is not compatible with net50 (.NETFramework,Version=v5.0). Package Stride.VisualStudio.Commands 4.1.0.1459-beta supports: net5.0-windows7.0 (.NETCoreApp,Version=v5.0)
```

**Comment by AmbulantRex** [comment]
This issue was resolved with the above commit. Closing.
