### ISSUE TITLE
Making changes to a scene and saving generates an error and breaks the project

### ISSUE THREAD

**Issue by WaitWhatWolf** [stride3d/stride#1118]
**Release Type**: Official Release

**Version**: Any (in the examples below, 4.0.1.1405 was used)

**Platform(s)**: Windows

**Describe the bug**
Whenever I create a new project,  it creates itself properly, but as soon as I make any changes that would prompt a scene save the project refuses to save the scene, and when I try to, it will display an Operation failed window (see screenshots)
When closing and opening the project again, it completely breaks.

**To Reproduce**
1. Create a new scene or open an existing one
2. Make any change that would prompt a [*] to appear in the Asset editor
3. Save (Ctrl+S)

**Expected behavior**
The scene would be saved.

**Screenshots**
![Screenshot_1542](https://user-images.githubusercontent.com/58935825/130194220-3271d426-adf0-44f3-a72e-1dd5e041e96b.png)

**Log and callstacks**
```
Error: The asset cannot be saved to path [D:/StrideProjects/MyGame/MyGame/Assets/MainScene.sdscene]
NullReferenceException: Object reference not set to an instance of an object.
   at Stride.Debugger.Target.CloneReferenceSerializer.CreateOrTransformObject(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Debugger\Debugger\CloneReferenceSerializer.cs:line 60
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.CreateOrTransformObjectInternal(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 124
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 378
   at Stride.Debugger.Target.CloneReferenceSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Debugger\Debugger\CloneReferenceSerializer.cs:line 100
   at Stride.Core.Yaml.ContextAttributeSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ContextAttributeSerializer.cs:line 32
   at Stride.Core.Yaml.ErrorRecoverySerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 165
   at Stride.Core.Yaml.AssetObjectSerializerBackend.WriteDictionaryValue(ObjectContext& objectContext, Object key, Object value, Type valueType) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\AssetObjectSerializerBackend.cs:line 291
   at Stride.Core.Yaml.Serialization.Serializers.DictionarySerializer.WriteDictionaryItem(ObjectContext& objectContext, KeyValuePair`2 keyValue, KeyValuePair`2 keyValueTypes) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\DictionarySerializer.cs:line 224
   at Stride.Core.Yaml.CollectionWithIdsSerializerBase.WriteDictionaryItems(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\CollectionWithIdsSerializerBase.cs:line 187
   at Stride.Core.Yaml.CollectionWithIdsSerializerBase.WriteYamlAfterTransform(ObjectContext& objectContext, Boolean transformed) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\CollectionWithIdsSerializerBase.cs:line 232
   at Stride.Core.Yaml.ContextAttributeSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ContextAttributeSerializer.cs:line 32
   at Stride.Core.Yaml.ErrorRecoverySerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 165
   at Stride.Core.Yaml.AssetObjectSerializerBackend.WriteMemberValue(ObjectContext& objectContext, IMemberDescriptor memberDescriptor, Object memberValue, Type memberType) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\AssetObjectSerializerBackend.cs:line 51
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteMember(ObjectContext& objectContext, IMemberDescriptor member) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 429
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteMembers(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 391
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 378
   at Stride.Debugger.Target.CloneReferenceSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Debugger\Debugger\CloneReferenceSerializer.cs:line 100
   at Stride.Core.Yaml.ContextAttributeSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ContextAttributeSerializer.cs:line 32
   at Stride.Core.Yaml.ErrorRecoverySerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 165
   at Stride.Core.Yaml.AssetObjectSerializerBackend.WriteMemberValue(ObjectContext& objectContext, IMemberDescriptor memberDescriptor, Object memberValue, Type memberType) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\AssetObjectSerializerBackend.cs:line 51
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteMember(ObjectContext& objectContext, IMemberDescriptor member) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 429
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteMembers(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 391
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 378
   at Stride.Core.Yaml.ContextAttributeSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ContextAttributeSerializer.cs:line 32
   at Stride.Core.Yaml.ErrorRecoverySerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 165
   at Stride.Core.Yaml.AssetObjectSerializerBackend.WriteCollectionItem(ObjectContext& objectContext, Object item, Type itemType, Int32 index) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\AssetObjectSerializerBackend.cs:line 159
   at Stride.Core.Yaml.Serialization.Serializers.CollectionSerializer.WriteCollectionItems(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\CollectionSerializer.cs:line 214
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 378
   at Stride.Core.Yaml.ContextAttributeSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ContextAttributeSerializer.cs:line 32
   at Stride.Core.Yaml.ErrorRecoverySerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 165
   at Stride.Core.Yaml.AssetObjectSerializerBackend.WriteMemberValue(ObjectContext& objectContext, IMemberDescriptor memberDescriptor, Object memberValue, Type memberType) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\AssetObjectSerializerBackend.cs:line 51
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteMember(ObjectContext& objectContext, IMemberDescriptor member) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 429
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteMembers(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 391
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 378
   at Stride.Core.Yaml.ContextAttributeSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ContextAttributeSerializer.cs:line 32
   at Stride.Core.Yaml.ErrorRecoverySerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 165
   at Stride.Core.Yaml.AssetObjectSerializerBackend.WriteMemberValue(ObjectContext& objectContext, IMemberDescriptor memberDescriptor, Object memberValue, Type memberType) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\AssetObjectSerializerBackend.cs:line 51
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteMember(ObjectContext& objectContext, IMemberDescriptor member) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 429
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteMembers(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 391
   at Stride.Core.Yaml.Serialization.Serializers.ObjectSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializers\ObjectSerializer.cs:line 378
   at Stride.Core.Yaml.ContextAttributeSerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ContextAttributeSerializer.cs:line 32
   at Stride.Core.Yaml.ErrorRecoverySerializer.WriteYaml(ObjectContext& objectContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\ErrorRecoverySerializer.cs:line 165
   at Stride.Core.Yaml.Serialization.Serializer.Serialize(IEmitter emitter, Object graph, Type type, SerializerContextSettings contextSettings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializer.cs:line 203
   at Stride.Core.Yaml.Serialization.Serializer.Serialize(TextWriter writer, Object graph, Type type, SerializerContextSettings contextSettings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializer.cs:line 179
   at Stride.Core.Yaml.Serialization.Serializer.Serialize(Stream stream, Object graph, Type expectedType, SerializerContextSettings contextSettings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Yaml\Serialization\Serializer.cs:line 146
   at Stride.Core.Yaml.AssetYamlSerializer.Serialize(Stream stream, Object instance, Type type, SerializerContextSettings contextSettings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Yaml\AssetYamlSerializer.cs:line 139
   at Stride.Core.Assets.Serializers.YamlAssetSerializer.Save(Stream stream, Object asset, AttachedYamlAssetMetadata yamlMetadata, ILogger log) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Serializers\YamlAssetSerializer.cs:line 53
   at Stride.Core.Assets.AssetFileSerializer.Save(Stream stream, Object asset, AttachedYamlAssetMetadata yamlMetadata, ILogger log) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\AssetFileSerializer.cs:line 173
   at Stride.Core.Assets.AssetFileSerializer.Save(String filePath, Object asset, AttachedYamlAssetMetadata yamlMetadata, ILogger log) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\AssetFileSerializer.cs:line 142
   at Stride.Core.Assets.Package.SaveSingleAsset_NoUpdateSourceFolder(AssetItem asset, ILogger log) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Package.cs:line 478
```

**Additional context**
A project before saving:
[MyGameUnsaved.zip](https://github.com/stride3d/stride/files/7019759/MyGameUnsaved.zip)
A project after saving:
[MyGame.zip](https://github.com/stride3d/stride/files/7019732/MyGame.zip)

Note: The change made in this specific project is simply adding a .dll library reference to the .csproj file (and only that), but it seems like any other change has the same effect.

**Comment by Eideren** [comment]
Hey, thanks for the clean report !
I tried it out on my end following your repro steps and it didn't error-out on latest commit, here's what I did:
- Download and extract the unsaved one
- Open the gamestudio, browse for project, open that project, gamestudio queries about upgrading packages to local, accept
- Toggled off cast shadows on the sphere model, changed the tesselation on the sphere asset
- Saved, no error dialog
- Closed, reopened, still no errors.

As for the second, saved one
- Download and extract it
- Open the gamestudio, browse for project, open that project, gamestudio queries about upgrading packages to local, accept
- No error dialog box

Perhaps it is because of that *.dll you included, could you try without it in the project ?

---
Here's where the error occurs
https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Debugger/Debugger/CloneReferenceSerializer.cs#L60
Note the ``[ThreadStatic]`` for that field, which should have been initialized here 
https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Debugger/Debugger/LiveAssemblyReloader.cs#L28 but might not have been, or not on the right thread, for whatever reason.

**Comment by WaitWhatWolf** [comment]
Hmm, It seems that including the *.dll file is what initially breaks it, but after it breaks, it stays broken as long as the project is opened (even if the include lines from the *.csproj are removed) and only starts working again after the project is re-opened without the *.dll file included.

The include line added to the *.csproj:
```xml
<ItemGroup>
		<Reference Include="WarWolfWorksxS">

<HintPath>C:\Users\WhiteWarriorWolf\Desktop\GameDevelopment\Compiled\WarWolfWorksxS\WarWolfWorksxS.dll</HintPath>
		</Reference>
	</ItemGroup>
```

I'm not sure if it's the *.dll itself that's breaking the project, or just the fact that a *.dll was included, I would need to test this on my side

For reference, here is the *.dll file:
[WarWolfWorksxS.zip](https://github.com/stride3d/stride/files/7020188/WarWolfWorksxS.zip)
And here's the Github repository for it:
[https://github.com/WaitWhatWolf/WarWolfWorks-x-Stride](https://github.com/WaitWhatWolf/WarWolfWorks-x-Stride)

**Comment by WaitWhatWolf** [comment]
After some digging, it turns out it is indeed the fault of the *.dll file specifically, which means that it's probably messing with the thread(s) somehow, so this doesn't seem to be an issue with Stride.

Either way, thank you for your time @Eideren .
