### ISSUE TITLE
Broken Sample Game (SpaceEscape)

### ISSUE THREAD

**Issue by ToolmakerSteve** [stride3d/stride#1183]
**Release Type**: GitHub

**Version**: master - 2bf586d6

**Platform(s)**: Windows

**Describe the bug**
When newly created Space Escape solution opens in GameStudio, null reference occurs at SpaceEscape.Rendering.BendFogRenderFeature.

**To Reproduce**
1. Build GitHub sources, master branch.
2. Run Stride.GameStudio.
3. New, pick Space Escape. (Windows)
4. Solution is created, attempt to open in GameStudio.
Result: stack dump.

**Expected behavior**
Space Escape project opens in Game Studio.

**Log and callstacks**
System.NullReferenceException: Object reference not set to an instance of an object.
   at SpaceEscape.Rendering.BendFogRenderFeature.Prepare(RenderDrawContext context) in C:\Users\toolm\Documents\Stride Projects\SpaceEscape\SpaceEscape.Game\Rendering\BendFogRenderFeature.cs:line 84
   at Stride.Rendering.MeshRenderFeature.Prepare(RenderDrawContext context) in C:\gh\stride\sources\engine\Stride.Rendering\Rendering\MeshRenderFeature.cs:line 118
   at Stride.Rendering.RenderSystem.Prepare(RenderDrawContext context) in C:\gh\stride\sources\engine\Stride.Rendering\Rendering\RenderSystem.cs:line 241
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context) in C:\gh\stride\sources\engine\Stride.Engine\Rendering\Compositing\GraphicsCompositor.cs:line 181
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context) in C:\gh\stride\sources\engine\Stride.Rendering\Rendering\RendererBase.cs:line 49
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime) in C:\gh\stride\sources\engine\Stride.Engine\Engine\SceneSystem.cs:line 230
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime) in C:\gh\stride\sources\engine\Stride.Games\GameSystemCollection.cs:line 132
   at Stride.Games.GameBase.Draw(GameTime gameTime) in C:\gh\stride\sources\engine\Stride.Games\GameBase.cs:line 780
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Draw(GameTime gameTime) in C:\gh\stride\sources\editor\Stride.Editor\EditorGame\Game\EditorServiceGame.cs:line 214

- - - - - - - - - - - 
NOTE: I tried reproducing this error today, but instead of this crash, the following message stayed for at least 15 minutes (after which I killed Stride Game Studio via Task Manager):

Loading scene...

This might take a few minutes the first time.

(below was a Marquee progress bar that kept animating.)

**Comment by windperson** [comment]
The Fog effect has name collision with built-in ones, so you have to rename that, I've made a example runnable one here:
https://github.com/windperson/SpaceEscape
