### ISSUE TITLE
Error when installing Visual Studio plugin

### ISSUE THREAD

**Issue by s-ccy** [stride3d/stride#1209]
On the Stride launcher (version 5.0.5), I clicked on "Stride: Install" under "Visual Studio plugin" to install the VS plugin. It pops up an error.

My Visual Studio edition is Community 2022 Preview (Version 17.1.0 Preview 1.1)

I suppose this is because Visual Studio 2022 is probably not supported by the plugin yet? 

Tail of error log listed below:

Microsoft.VisualStudio.ExtensionManager.NotInstalledException: The extension with ID '248ff1ce-dacd-4404-947a-85e999d3c3ea' is not installed to any currently installed products.
   at VSIXInstaller.ExtensionService.GetUninstallableData(IStateData stateData, MarkupRawExtensionData vsixData, IEnumerable`1& targetSkus)
   at VSIXInstaller.ExtensionService.ComputeUninstallableExtensions(IStateData stateData, IDictionary`2 skuDataMapping, IList`1 uninstallableVsixIds)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by TheHeksiii** [comment]
Same problem here, I want to try Stride because it looks amazing, and it boasts C# 9 support, yet it doesnt support VS2022 ? I really dont want to downgrade back to VS2019...

**Comment by Eideren** [comment]
The plugin only helps in writing shaders for stride, you don't need it if you don't intend to work with shaders yet
