### ISSUE TITLE
Exception during Alt+Tab processing (SDL)

### ISSUE THREAD

**Issue by HordeResurrection** [stride3d/stride#1317]
**Release Type**: Official Release

**Version**: 4.0.1.1428

**Platform(s)**: Windows 10

**Describe the bug**
Exception during game window minimizing.

**To Reproduce**
1. Launch game with SDL context
2. This bug caused sometimes when `Alt+Tab` is pressed in fullscreen game
It seems like race condition here

**Expected behavior**
I expect that windows will minimize correctly

**Log and callstacks**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stride.Graphics.SwapChainGraphicsPresenter.OnDestroyed()
   at Stride.Graphics.ResumeManager.OnDestroyed()
...
```
See full: [20220204_194924_crash.log](https://github.com/stride3d/stride/files/8005361/20220204_194924_crash.log)

**Comment by HordeResurrection** [comment]
`Stride 4.0.1.1428` also affected to that bug

**Comment by HordeResurrection** [comment]
Do not use fullscreen in exclusive mode.
