### ISSUE TITLE
Impossible to import FBX animation(s)

### ISSUE THREAD

**Issue by NicusorN5** [stride3d/stride#1567]
**Release Type**: Latest official release

**Version**: 4.1.0.1734

**Platform(s)**:  Windows

**Describe the bug**
Loading animations from a FBX 3D animation literally takes hours before being shown a `OutOfMemoryException`.

**To Reproduce**
1. Use a animated 3D model and export it as a FBX.
I've used for example (models are removed, sorry):
 ~~https://sketchfab.com/3d-models/ak-47-47e1f4abe10e4ea9909708529b67a488~~
 ~~https://sketchfab.com/3d-models/m4-animations-95b877e551254a2e8cc42add94e11f13~~
 
 1.1) I've also used https://github.com/JackPilley/BlenderToStrideAnimationSeparator but I still get the out of memory exception. I don't get the `multiple FBX stacks` warning though.
 
 2.) Import the model and skeleton into Stride. Works successfully.

 3.) Import the animations. This will **not** work, atleast with the given examples.
 
**Expected behavior**
Animations being properly imported.

**Screenshots**
Error report (generated using a propietary model)
![image](https://user-images.githubusercontent.com/20599225/203644652-2aa9489b-03a5-4cf5-9209-cc9ee219553b.png)

**Logs and callstacks**
Log reported with a example model from above:
```Warning: Multiple FBX animation stacks detected in 'D:/Projects/FPS Controller/M4/source/m4.fbx', exporting only the first one to '
Error: An exception occurred while generating the template.
OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.AddWithResize(T item)
   at Stride.Importer.FBX.AnimationConverter.ProcessAnimationCurveFloatsHelper<Stride::Core::Mathematics::Vector3>(FbxAnimCurve** curves, Vector3 defaultValue, Int32 numCurves)
   at Stride.Importer.FBX.AnimationConverter.ProcessAnimationCurveVector<Stride::Core::Mathematics::Vector3>(AnimationClip animationClip, String name, Int32 numCurves, FbxAnimCurve** curves, Vector3 defaultValue, Boolean isUserDefinedProperty)
   at Stride.Importer.FBX.AnimationConverter.ProcessAnimationByNode(Dictionary`2 animationClips, FbxAnimLayer* animLayer, FbxNode* pNode, Boolean importCustomAttributeAnimations)
   at Stride.Importer.FBX.AnimationConverter.ProcessAnimationByNode(Dictionary`2 animationClips, FbxAnimLayer* animLayer, FbxNode* pNode, Boolean importCustomAttributeAnimations)
   at Stride.Importer.FBX.AnimationConverter.ProcessAnimation(String inputFilename, String vfsOutputFilename, Boolean importCustomAttributeAnimations)
   at Stride.Importer.FBX.MeshConverter.GetAnimationDuration(String inputFileName)
   at Stride.Assets.Models.FbxAssetImporter.GetAnimationDuration(UFile localPath, Logger logger, AssetImporterParameters importParameters, TimeSpan& startTime, TimeSpan& endTime) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Assets.Models\FbxAssetImporter.cs:line 43
   at Stride.Assets.Models.ModelAssetImporter.Import(UFile localPath, AssetImporterParameters importParameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Assets.Models\ModelAssetImporter.cs:line 81
   at Stride.Assets.Presentation.Templates.AnimationFromFileTemplateGenerator.CreateAssets(AssetTemplateGeneratorParameters parameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\Templates\AnimationFromFileTemplateGenerator.cs:line 46
   at Stride.Assets.Presentation.Templates.AssetTemplateGenerator.Run(AssetTemplateGeneratorParameters parameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\Templates\AssetTemplateGenerator.cs:line 32
   at Stride.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Core.Assets.Editor\Components\TemplateDescriptions\TemplateGeneratorHelper.cs:line 56

Info: Nothing to import.
```

**Comment by NicusorN5** [comment]
Update 1: Updated post with a log generated from importing a example provided above.

**Comment by NicusorN5** [comment]
As of today, I tried to research this issue, here's what I found today:
- The links in the initial post are dead, will find upload other models soon
- This only happens with specific FBX files, not sure what the criteria is to trigger this problem. For example, this animation loads perfectly ( https://github.com/Tvtig/PropLibrary/blob/main/9mm.blend )
- There's a list that is infinitely growing at https://github.com/stride3d/stride/blob/3d218db080d31ce9283a1053c82123e394741217/sources/tools/Stride.Importer.FBX/AnimationConverter.h#LL284C14-L284C14
![image](https://user-images.githubusercontent.com/20599225/235372730-8044b52b-f1f4-4372-b35c-6655390337cb.png)
![image](https://user-images.githubusercontent.com/20599225/235373680-fc2e43d6-0afc-4f69-8bfb-4997ee2fdd9b.png)
There are hundreds of duplicated values (picture above)

I can't even properly debug this because the unmanaged variables are optimized away. The boolean expression 
```cpp
time < endTime || !lastFrame;
```
in L338 in the function `ProcessAnimationCurveFloatsHelper` is never true when the importer gets stuck. This is because `oneFrame` is 0 and that (speculation) `endTime` is approaching infinity.

I'm still investigating this issue...

**Comment by NicusorN5** [comment]
Update from the previous post: `FbxTime::GetOneFrameValue` returns 0, so as consequence, the loop at L338 in `AnimationConverter.h` is infinite. The return type of `FbxTime::GetOneFrameValue` is `FbxLongLong` and it is a typedef of `FbxInt64` (`FbxInt64` is `signed __int64`).

A workaround by checking if `oneFrame` is 0 makes the importer return a empty animation. This is not acceptable behavior.

**Comment by NicusorN5** [comment]
I just wrote a fix for this issue. This is why the issue existed.

- Likely to a bug in FBX SDK, if `FbxTime::eFrames30Drop` is passed to `FbxTime::GetOneFrameValue` 0 is returned. The fix is re-using a valid value.
- With 0 being returned, there's a loop that's iterating over time. with the `oneFrame` being 0, the loop is infinite therefore resulting in the issue initially described.
- As the loop keeps executing the `keyFrames` list will get filled with repeated value until the importer crashes. (the error being an out-of-memory exception).

The fix is checking if `oneFrame` is 0, then setting it again to a valid number. I will create a PR after this post.

**Comment by NicusorN5** [comment]
Solved by PR1653
