### ISSUE TITLE
Could not load file or assembly 'K4os.Compression.LZ4.Legacy'

### ISSUE THREAD

**Issue by Jklawreszuk** [stride3d/stride#1590]
**Release Type**: GitHub

**Version**: master branch
**Platform(s)**: Any

**Describe the bug**
As a developer, when I build and run Stride.GameStudio from source and then build any game project, the game does not start and AssetsCompiler throws an error : Could not load file or assembly 'K4os.Compression.LZ4.Legacy'

**To Reproduce**
Steps to reproduce the behavior: As Above.

**Expected behavior**
The game should run without any errors

**Log and callstacks**
[error.txt](https://github.com/stride3d/stride/files/10468181/error.txt)

**Additional context**
I have no clue but this issue fixes sometimes. See PR #1566

**Comment by tagcode** [comment]
I got different lz4 error when running android

Stride.Core.Serialization.Contents.ContentManagerException: 'Unexpected exception while loading asset [GameSettings]. Reason: TypeInitialization_Type, Stride.Core.LZ4.LZ4Codec. Check inner-exception for details.

```
[ViewRootImpl@8791217[GameMenuActivity]] Relayout returned: old=(0,0,1440,2678) new=(0,0,1440,2678) req=(1440,2678)0 dur=5 res=0x100000 s={true 0x7bcb6fff20} ch=false seqId=0
[ViewRootImpl@8791217[GameMenuActivity]] updateBoundsLayer: t = android.view.SurfaceControl$Transaction@7b0951b sc = Surface(name=Bounds for - GameMenu.GameMenu/crc64c83969b9872c8cbe.GameMenuActivity@0)/@0x17fe6b8 frame = 5
[ViewRootImpl@8791217[GameMenuActivity]] mWNT: t=0x7afb114a90 mBlastBufferQueue=0x7b3b1288f0 fn= 5 caller= android.view.ViewRootImpl.prepareSurfaces:2865 android.view.ViewRootImpl.performTraversals:4108 android.view.ViewRootImpl.doTraversal:2991 
[BLASTBufferQueue] mergeWithNextTransaction, mNativeObject= 0x7b3b1288f0 t.mNativeObject= 0x7afb114a90 frameNumber= 5 caller= android.view.ViewRootImpl.mergeWithNextTransaction:12594 android.view.ViewRootImpl.prepareSurfaces:2865 android.view.ViewRootImpl.performTraversals:4108 android.view.ViewRootImpl.doTraversal:2991 android.view.ViewRootImpl$TraversalRunnable.run:10665 android.view.Choreographer$CallbackRecord.run:1301 
[ViewRootImpl@8791217[GameMenuActivity]] Surface Surface(name=null)/@0x26caf07 drawing to bitmap w=1440, h=2678
[ViewRootImpl@8791217[GameMenuActivity]] Drawing: package:GameMenu.GameMenu, metrics=DisplayMetrics{density=4.0, width=1440, height=2678, scaledDensity=4.0, xdpi=571.5, ydpi=564.444}, compatibilityInfo={480dpi always-compat}
[monodroid-assembly] Shared library 'libc.so' not loaded, p/invoke '__system_property_get' may fail
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Overlapped.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.IO.Compression.dll
[monodroid-assembly] Symbol 'LZ4_compress_limitedOutput' not found in shared library 'libcore', p/invoke may fail
[monodroid-assembly] Symbol 'LZ4_compress_limitedOutput' not found in shared library 'libcore', p/invoke may fail
[monodroid-assembly] Symbol 'LZ4_compress_limitedOutput' not found in shared library 'libcore', p/invoke may fail
**Stride.Core.Serialization.Contents.ContentManagerException:** 'Unexpected exception while loading asset [GameSettings]. Reason: TypeInitialization_Type, Stride.Core.LZ4.LZ4Codec. Check inner-exception for details.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Stride.Core.Serialization.Contents.ContentManagerException: Unexpected exception while loading asset [GameSettings]. Reason: TypeInitialization_Type, Stride.Core.LZ4.LZ4Codec. Check inner-exception for details.
[mono-rt]  ---> System.TypeInitializationException: TypeInitialization_Type, Stride.Core.LZ4.LZ4Codec
[mono-rt]  ---> System.NotSupportedException: No LZ4 compression service found
[mono-rt]    at Stride.Core.LZ4.LZ4Codec..cctor() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\LZ4\LZ4Codec.cs:line 90
[mono-rt]    Exception_EndOfInnerExceptionStack
[mono-rt]    at Stride.Core.LZ4.LZ4Stream.AcquireNextChunk() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\LZ4\LZ4Stream.cs:line 313
[mono-rt]    at Stride.Core.LZ4.LZ4Stream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\LZ4\LZ4Stream.cs:line 411
[mono-rt]    at Stride.Core.Serialization.VirtualFileStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.IO\VirtualFileStream.cs:line 135
[mono-rt]    at Stride.Core.IO.NativeStream.ReadUInt32() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\IO\NativeStream.cs:line 41
[mono-rt]    at Stride.Core.Serialization.BinarySerializationReader.Serialize(Int32& value) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Serialization\Binary\BinarySerializationReader.cs:line 59
[mono-rt]    at Stride.Core.Serialization.Contents.ChunkHeader.Read(SerializationStream stream) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ChunkHeader.cs:line 49
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(Queue`1 serializeOperations, Reference parentReference, String url, Type objType, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 501
[mono-rt]    Exception_EndOfInnerExceptionStack
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(Queue`1 serializeOperations, Reference parentReference, String url, Type objType, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 550
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(String initialUrl, String newUrl, Type type, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 387
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.Load(Type type, String url, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 136
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.Load[GameSettings](String url, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 113
[mono-rt]    at Stride.Engine.Game.PrepareContext() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Engine\Engine\Game.cs:line 264
[mono-rt]    at Stride.Games.GameBase.Run(GameContext gameContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 435
[mono-rt]    at GameMenu.GameMenuActivity.OnRun() in C:\Users\tonik\source\repos\GameMenu\GameMenu.Android\GameMenuActivity.cs:line 24
[mono-rt]    at Silk.NET.Windowing.Sdl.Android.SilkActivity.Run()
[mono-rt]    at Silk.NET.Windowing.Sdl.Android.SilkActivity.Main()`
```

**Comment by manio143** [comment]
I have pulled master with the LZ4 changes, built Stride solution - this correctly picked up the new dependency of `Stride.Core.Serialization` and restored the K4os package into the nuget cache. I was able to run the asset compiler within the Stride solution without any issues.
I then launched the GameStudio and ran a project. It built fine, but failed to start - with the above exception.
I had trouble running restore/rebuild from `dotnet` cli because GameStudio does something weird to the sln, but **performing a rebuild of the game in VS has fixed the issue**.
I believe this is caused because there's multiple layers of nuget caching and if you had a project which previously performed a restore you will see the dependencies are listed in `project.assets.json` and, unless you perform a rebuild which makes a forcefull restore, those old dependencies will be used to copy dlls into your output.
This should not be happening for users after a new release because a new Stride nuget version will force a full restore after updating the project.

For developers it is recommended to rebuild all local Stride libraries when pulling in new changes and to rebuild any project that uses the dev packages.

Feel free to reopen if the issue occurs still after a confirmed `Rebuild` action.
I tried following [comment](https://github.com/stride3d/stride/pull/1566#issuecomment-1396109558) to get the error in asset compiler but could not repro.
