### ISSUE TITLE
Android Application Crash at startup

### ISSUE THREAD

**Issue by tagcode** [stride3d/stride#1597]
**Release Type**: Official Release
**Version**: 4.1.0.1734
**Platform(s)**: Android
**Describe the bug**
Non-deterministic System.ArgumentNullException and crash at application start.

**To Reproduce**
1. Install *GameMenu* or *FirstPersonShooter* sample application with Android support

**Expected behavior**
Application to run

**Screenshots**
<img width="1492" alt="GameMenu" src="https://user-images.githubusercontent.com/5236113/216645537-a3ce4e4d-588f-49a3-b32b-36af926c8153.png">

**Log and callstacks**
`[Stride] [Game]: Error: Unexpected exception. System.ArgumentNullException: Array cannot be null. (Parameter 'bytes')
[Stride]    at System.Text.Encoding.GetString(Byte* bytes, Int32 byteCount)
[Stride]    at Silk.NET.Core.Native.SilkMarshal.Utf8PtrToString(IntPtr ptr)
[Stride]    at Silk.NET.Core.Native.SilkMarshal.PtrToString(IntPtr input, NativeStringEncoding encoding)
[Stride]    at Silk.NET.OpenGLES.GL.GetShaderInfoLog(UInt32 shader, UInt32 bufSize, UInt32& length, String& infoLog)
[Stride]    at Silk.NET.OpenGLES.GL.GetShaderInfoLog(UInt32 shader, String& info)
[Stride]    at Silk.NET.OpenGLES.GL.GetShaderInfoLog(UInt32 shader)
[Stride]    at Stride.Graphics.GraphicsDevice.TryCompileShader(ShaderType shaderType, String sourceCode) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\GraphicsDevice.OpenGL.cs:line 578
[Stride]    at Stride.Graphics.GraphicsDevice.CreateCopyProgram(Boolean srgb, Int32& offsetLocation, Int32& scaleLocation) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\GraphicsDevice.OpenGL.cs:line 319
[Stride]    at Stride.Graphics.GraphicsDevice.GetCopyProgram(Boolean srgb, Int32& offsetLocation, Int32& scaleLocation) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\GraphicsDevice.OpenGL.cs:line 234
[Stride]    at Stride.Graphics.CommandList.CopyScaler2D(Texture sourceTexture, Texture destTexture, Rectangle sourceRectangle, Rectangle destRectangle, Boolean flipY) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\CommandList.OpenGL.cs:line 515
[Stride]    at Stride.Graphics.SwapChainGraphicsPresenter.EndDraw(CommandList commandList, Boolean present) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\SwapChainGraphicsPresenter.OpenGL.cs:line 58
[Stride]    at Stride.Games.GameBase.EndDraw(Boolean present) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 816
[Stride]    at Stride.Engine.Game.EndDraw(Boolean present) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Engine\Engine\Game.cs:line 445
[Stride]    at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 670
[Stride]    at Stride.Games.GameBase.RawTickProducer() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 586System.ArgumentNullException: Array cannot be null. (Parameter 'bytes')
[Stride]    at System.Text.Encoding.GetString(Byte* bytes, Int32 byteCount)
[Stride]    at Silk.NET.Core.Native.SilkMarshal.Utf8PtrToString(IntPtr ptr)
[Stride]    at Silk.NET.Core.Native.SilkMarshal.PtrToString(IntPtr input, NativeStringEncoding encoding)
[Stride]    at Silk.NET.OpenGLES.GL.GetShaderInfoLog(UInt32 shader, UInt32 bufSize, UInt32& length, String& infoLog)
[Stride]    at Silk.NET.OpenGLES.GL.GetShaderInfoLog(UInt32 shader, String& info)
[Stride]    at Silk.NET.OpenGLES.GL.GetShaderInfoLog(UInt32 shader)
[Stride]    at Stride.Graphics.GraphicsDevice.TryCompileShader(ShaderType shaderType, String sourceCode) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\GraphicsDevice.OpenGL.cs:line 578
[Stride]    at Stride.Graphics.GraphicsDevice.CreateCopyProgram(Boolean srgb, Int32& offsetLocation, Int32& scaleLocation) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\GraphicsDevice.OpenGL.cs:line 319
[Stride]    at Stride.Graphics.GraphicsDevice.GetCopyProgram(Boolean srgb, Int32& offsetLocation, Int32& scaleLocation) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\GraphicsDevice.OpenGL.cs:line 234
[Stride]    at Stride.Graphics.CommandList.CopyScaler2D(Texture sourceTexture, Texture destTexture, Rectangle sourceRectangle, Rectangle destRectangle, Boolean flipY) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\CommandList.OpenGL.cs:line 515
[Stride]    at Stride.Graphics.SwapChainGraphicsPresenter.EndDraw(CommandList commandList, Boolean present) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Graphics\OpenGL\SwapChainGraphicsPresenter.OpenGL.cs:line 58
[Stride]    at Stride.Games.GameBase.EndDraw(Boolean present) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 816
[Stride]    at Stride.Engine.Game.EndDraw(Boolean present) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Engine\Engine\Game.cs:line 445
[Stride]    at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 670
[Stride]    at Stride.Games.GameBase.RawTickProducer() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 586
**System.ArgumentNullException:** 'Array cannot be null. (Parameter 'bytes')'
`

**Additional context**
Sometimes runs, sometimes not.

**Comment by tagcode** [comment]
Issue is [known on Silk.NET 2.10.1](https://github.com/dotnet/Silk.NET/issues/686)  and [fixed](https://github.com/dotnet/Silk.NET/commit/d6de1a48a63e535a8cab6072c8e9b708eb21b03e). Stride.Graphics.csproj should be updated to use newer version.
