### ISSUE TITLE
Android Asset Compiler InvalidOperationException "Image size different than expected."

### ISSUE THREAD

**Issue by tagcode** [stride3d/stride#1600]
**Release Type**: GitHub

**Version**: [git branch main](https://github.com/stride3d/stride/commit/441fb473dc30caa44e8fa25acccad5cd39e95ba4)

**Platform(s)**: Android

**Describe the bug**
Asset compiler does not compile textures. 
StrideTexLibrary.Export Throws [InvalidOperationException](https://github.com/stride3d/stride/blob/d7049340b64e7dd6d5e98b3ae75b6ce329a847e2/sources/tools/Stride.TextureConverter/Backend/TexLibraries/StrideTexLibrary.cs#L261).

**To Reproduce**
1. Install an Android Sample code
2. Add TextureAsset if there already isn't one
3. Build to Android

**Expected behavior**
Build to succeed

**Screenshots**
<img width="1595" alt="AssetCompiler" src="https://user-images.githubusercontent.com/5236113/216765949-81bb6d3b-d078-4292-b5bc-064a90ec4f54.png">

**Log and callstacks**
```none
1>EXEC : error 27,515s: [AssetCompiler] BuildStep Asset build steps [TextureAsset:'0001_metallic'] (1 items) failed.
1>EXEC : error 35,546s: [StrideTexLibrary] Image size different than expected.
1>EXEC : error 35,547s: [AssetCompiler] Exception in command [0001_ao] Stride.Assets.Textures.TextureConvertParameters: System.InvalidOperationException: Image size different than expected.
1>   at Stride.TextureConverter.TexLibraries.StrideTexLibrary.ExportToStride(TexImage image, StrideTextureLibraryData libraryData, ExportToStrideRequest request) in C:\repos\stride-tagcode\sources\tools\Stride.TextureConverter\Backend\TexLibraries\StrideTexLibrary.cs:line 367
1>   at Stride.TextureConverter.TexLibraries.StrideTexLibrary.Execute(TexImage image, IRequest request) in C:\repos\stride-tagcode\sources\tools\Stride.TextureConverter\Backend\TexLibraries\StrideTexLibrary.cs:line 111
1>   at Stride.TextureConverter.TextureTool.ExecuteRequest(TexImage image, IRequest request) in C:\repos\stride-tagcode\sources\tools\Stride.TextureConverter\Frontend\TextureTool.cs:line 1448
1>   at Stride.TextureConverter.TextureTool.ConvertToStrideImage(TexImage image) in C:\repos\stride-tagcode\sources\tools\Stride.TextureConverter\Frontend\TextureTool.cs:line 1021
1>   at Stride.Assets.Textures.TextureHelper.ImportStreamableTextureImage(ContentManager assetManager, TextureTool textureTool, TexImage texImage, ImportParameters convertParameters, CancellationToken cancellationToken, ICommandContext commandContext) in C:\repos\stride-tagcode\sources\engine\Stride.Assets\Textures\TextureHelper.cs:line 516
1>   at Stride.Assets.Textures.TextureAssetCompiler.TextureConvertCommand.Import(ICommandContext commandContext, TextureTool textureTool, TexImage texImage, ImportParameters convertParameters) in C:\repos\stride-tagcode\sources\engine\Stride.Assets\Textures\TextureAssetCompiler.cs:line 73
1>   at Stride.Assets.Textures.TextureAssetCompiler.TextureConvertCommand.DoCommandOverride(ICommandContext commandContext) in C:\repos\stride-tagcode\sources\engine\Stride.Assets\Textures\TextureAssetCompiler.cs:line 85
1>   at Stride.Core.BuildEngine.Command.DoCommand(ICommandContext commandContext) in C:\repos\stride-tagcode\sources\buildengine\Stride.Core.BuildEngine.Common\Command.cs:line 67
1>   at Stride.Core.BuildEngine.CommandBuildStep.StartCommand(IExecuteContext executeContext, ListStore`1 commandResultEntries, BuilderContext builderContext) in C:\repos\stride-tagcode\sources\buildengine\Stride.Core.BuildEngine.Common\CommandBuildStep.cs:line 304
1>EXEC : error 35,547s: [AssetCompiler] BuildStep [0001_ao] Stride.Assets.Textures.TextureConvertParameters failed.```

**Comment by tagcode** [comment]
Does anyone understand the Asset Compiler? What is this assert about?

Also how to set asset compiler so that I can debug it while it runs in visual studio? For example, how to debug it while it compiles texture asset '0001_metallic' to Android?

**Comment by tagcode** [comment]
I tried running asset compiler from console from visual studio. I got sometimes file lock.
<img width="1585" alt="assetcompiler1" src="https://user-images.githubusercontent.com/5236113/216777372-1ac0b58f-141b-4925-b986-d91a8b410d5c.png">

Required always visual studio restart. Then I got this.
<img width="1409" alt="assetcompiler2" src="https://user-images.githubusercontent.com/5236113/216777387-85d890d8-676f-415d-92b6-77b838f9bd8d.png">

And then...
<img width="764" alt="assetcompiler3" src="https://user-images.githubusercontent.com/5236113/216777400-22dd9fdd-92eb-40df-8822-6e9a1eab769a.png">


This code base is impossible.

**Comment by tagcode** [comment]
I tried running from Stride.Core.Assets.CompilerApp but I couldn't add breakpoints as it loads nuget binaries.

This code base is impossible to use.

**Comment by tagcode** [comment]
Surely this same situation is in ios target too?

**Comment by tagcode** [comment]
**Stride.Core.Serialization.Contents.ContentManagerException:** 'Unexpected exception while loading asset [GameSettings]. Reason: TypeInitialization_Type, Stride.Core.LZ4.LZ4Codec. Check inner-exception for details.

```none
[ViewRootImpl@8791217[GameMenuActivity]] Relayout returned: old=(0,0,1440,2678) new=(0,0,1440,2678) req=(1440,2678)0 dur=5 res=0x100000 s={true 0x7bcb6fff20} ch=false seqId=0
[ViewRootImpl@8791217[GameMenuActivity]] updateBoundsLayer: t = android.view.SurfaceControl$Transaction@7b0951b sc = Surface(name=Bounds for - GameMenu.GameMenu/crc64c83969b9872c8cbe.GameMenuActivity@0)/@0x17fe6b8 frame = 5
[ViewRootImpl@8791217[GameMenuActivity]] mWNT: t=0x7afb114a90 mBlastBufferQueue=0x7b3b1288f0 fn= 5 caller= android.view.ViewRootImpl.prepareSurfaces:2865 android.view.ViewRootImpl.performTraversals:4108 android.view.ViewRootImpl.doTraversal:2991 
[BLASTBufferQueue] mergeWithNextTransaction, mNativeObject= 0x7b3b1288f0 t.mNativeObject= 0x7afb114a90 frameNumber= 5 caller= android.view.ViewRootImpl.mergeWithNextTransaction:12594 android.view.ViewRootImpl.prepareSurfaces:2865 android.view.ViewRootImpl.performTraversals:4108 android.view.ViewRootImpl.doTraversal:2991 android.view.ViewRootImpl$TraversalRunnable.run:10665 android.view.Choreographer$CallbackRecord.run:1301 
[ViewRootImpl@8791217[GameMenuActivity]] Surface Surface(name=null)/@0x26caf07 drawing to bitmap w=1440, h=2678
[ViewRootImpl@8791217[GameMenuActivity]] Drawing: package:GameMenu.GameMenu, metrics=DisplayMetrics{density=4.0, width=1440, height=2678, scaledDensity=4.0, xdpi=571.5, ydpi=564.444}, compatibilityInfo={480dpi always-compat}
[monodroid-assembly] Shared library 'libc.so' not loaded, p/invoke '__system_property_get' may fail
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Overlapped.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.IO.Compression.dll
[monodroid-assembly] Symbol 'LZ4_compress_limitedOutput' not found in shared library 'libcore', p/invoke may fail
[monodroid-assembly] Symbol 'LZ4_compress_limitedOutput' not found in shared library 'libcore', p/invoke may fail
[monodroid-assembly] Symbol 'LZ4_compress_limitedOutput' not found in shared library 'libcore', p/invoke may fail
**Stride.Core.Serialization.Contents.ContentManagerException:** 'Unexpected exception while loading asset [GameSettings]. Reason: TypeInitialization_Type, Stride.Core.LZ4.LZ4Codec. Check inner-exception for details.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Stride.Core.Serialization.Contents.ContentManagerException: Unexpected exception while loading asset [GameSettings]. Reason: TypeInitialization_Type, Stride.Core.LZ4.LZ4Codec. Check inner-exception for details.
[mono-rt]  ---> System.TypeInitializationException: TypeInitialization_Type, Stride.Core.LZ4.LZ4Codec
[mono-rt]  ---> System.NotSupportedException: No LZ4 compression service found
[mono-rt]    at Stride.Core.LZ4.LZ4Codec..cctor() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\LZ4\LZ4Codec.cs:line 90
[mono-rt]    Exception_EndOfInnerExceptionStack
[mono-rt]    at Stride.Core.LZ4.LZ4Stream.AcquireNextChunk() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\LZ4\LZ4Stream.cs:line 313
[mono-rt]    at Stride.Core.LZ4.LZ4Stream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\LZ4\LZ4Stream.cs:line 411
[mono-rt]    at Stride.Core.Serialization.VirtualFileStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.IO\VirtualFileStream.cs:line 135
[mono-rt]    at Stride.Core.IO.NativeStream.ReadUInt32() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\IO\NativeStream.cs:line 41
[mono-rt]    at Stride.Core.Serialization.BinarySerializationReader.Serialize(Int32& value) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Serialization\Binary\BinarySerializationReader.cs:line 59
[mono-rt]    at Stride.Core.Serialization.Contents.ChunkHeader.Read(SerializationStream stream) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ChunkHeader.cs:line 49
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(Queue`1 serializeOperations, Reference parentReference, String url, Type objType, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 501
[mono-rt]    Exception_EndOfInnerExceptionStack
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(Queue`1 serializeOperations, Reference parentReference, String url, Type objType, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 550
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(String initialUrl, String newUrl, Type type, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 387
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.Load(Type type, String url, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 136
[mono-rt]    at Stride.Core.Serialization.Contents.ContentManager.Load[GameSettings](String url, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 113
[mono-rt]    at Stride.Engine.Game.PrepareContext() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Engine\Engine\Game.cs:line 264
[mono-rt]    at Stride.Games.GameBase.Run(GameContext gameContext) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Games\GameBase.cs:line 435
[mono-rt]    at GameMenu.GameMenuActivity.OnRun() in C:\Users\tonik\source\repos\GameMenu\GameMenu.Android\GameMenuActivity.cs:line 24
[mono-rt]    at Silk.NET.Windowing.Sdl.Android.SilkActivity.Run()
[mono-rt]    at Silk.NET.Windowing.Sdl.Android.SilkActivity.Main()
```

**Comment by Basewq** [comment]
The `Unsupported texture format: ETC2_RGB_SRgb` is due to the unhandled case in this method
https://github.com/stride3d/stride/blob/fb60fe04c35d51a58aacc5a6da8c8a556bb3ae23/sources/engine/Stride.Graphics/OpenGL/OpenGLConvertExtensions.cs#L179https://github.com/stride3d/stride/blob/fb60fe04c35d51a58aacc5a6da8c8a556bb3ae23/sources/engine/Stride.Graphics/OpenGL/OpenGLConvertExtensions.cs#L179

Any rendering guru that know what the correct format(s) should be?
