### ISSUE TITLE
glb import

### ISSUE THREAD

**Issue by anan1213095357** [stride3d/stride#1666]
**Release Type**: github

**Version**: 4.1

**Platform(s)**: windows

**Describe the bug**
When I clicked 
[阿克尚.zip](https://github.com/stride3d/stride/files/11549422/default.zip)
to import the model in GLB format, there was no prompt. The model was not imported either

**Comment by Ceebox** [comment]
There should be a message saying "Invalid character * found in path [{filePath}]". It is strange that there is no prompt.

I originally assumed that this issue was due to the UTF8 characters in the file name and mentally dismissed this as "eh, just change the name and it will work" _but_ it actually turns out this seems to be an issue with [Stride's current version of?] ASSIMP not supporting .glb files, or Stride doesn't support the output of ASSIMPs glb import.

`MeshConverter.ExtractTextureDependencies` is an important function in this. It calls `assimp.GetMaterialTexture`, which references a path variable. The output of this path when you input a GLB file is `*{textureNumber}`, eg `*0`,`*1`,`*2*`. This is because a .glb file stores the texture inside of that file, and I'm _not sure_ that we have a way to deal with this. I suppose I could work on this in the future but I do not have time at the moment.

Realistically the workaround to this is to convert it to a GLTF (not embedded) or another file format (obj or fbx, unfortunately), until this is fixed. I'll keep looking into this in the morning because it is possible I've not investigated far enough into this.

o7

**Comment by lightway82** [comment]
I have same bug.

ArgumentException: Invalid character [*] found in path [I:\*0]
   at Stride.Core.IO.UPath.Decode(String pathToNormalize, Boolean isPathDirectory, StringSpan& drive, StringSpan& directory, StringSpan& fileName, StringSpan& fileExtension) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Design\IO\UPath.cs:line 791
   at Stride.Core.IO.UPath..ctor(String filePath, Boolean isDirectory) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Design\IO\UPath.cs:line 66
   at Stride.Assets.Models.ModelAssetImporter.ImportTextures(IEnumerable`1 textureDependencies, List`1 assetReferences) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Assets.Models\ModelAssetImporter.cs:line 292
   at Stride.Assets.Models.ModelAssetImporter.Import(UFile localPath, AssetImporterParameters importParameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Assets.Models\ModelAssetImporter.cs:line 81
   at Stride.Assets.Models.AssimpAssetImporter.Import(UFile localPath, AssetImporterParameters importParameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Assets.Models\AssimpAssetImporter.cs:line 71
   at Stride.Assets.Presentation.Templates.ModelFromFileTemplateGenerator.CreateAssets(AssetTemplateGeneratorParameters parameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\Templates\ModelFromFileTemplateGenerator.cs:line 141
   at Stride.Assets.Presentation.Templates.AssetTemplateGenerator.Run(AssetTemplateGeneratorParameters parameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\Templates\AssetTemplateGenerator.cs:line 32
   at Stride.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Core.Assets.Editor\Components\TemplateDescriptions\TemplateGeneratorHelper.cs:line 56


[statue.zip](https://github.com/stride3d/stride/files/13168563/statue.zip)
