### ISSUE TITLE
Arithmetic overflow error being thrown upon project loading

### ISSUE THREAD

**Issue by NicusorN5** [stride3d/stride#1700]
**Release Type**: GitHub

**Version**: Github master branch

**Platform(s)**: Windows

**Describe the bug**
Upon loading a project, the Stride editor either crashes (like in https://github.com/stride3d/stride/issues/1692) or there's a `Arithmetic operation resulted in an overflow.` error being shown when loading a project that renders a front in the scene. In this case two buttons were attempted to be loaded.

**To Reproduce**
1,) Create a new project for example, "AnimatedModel" in my example. ( Literally the same steps as 1692! )
2.) Wait for the scene to load

**Expected behavior**
I expected no errors.

**Screenshots**
![image](https://github.com/stride3d/stride/assets/20599225/1c96a51b-79bd-4982-8e9c-b6918d4d34a7)

**Log and callstacks**
```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Stride.Graphics.Font.FontManager.GenerateCharacterGlyph(CharacterSpecification character, Boolean renderBitmap) in D:\Dev\stride\sources\engine\Stride.Graphics\Font\FontManager.cs:line 120
   at Stride.Graphics.Font.FontManager.GenerateBitmap(CharacterSpecification characterSpecification, Boolean synchronously) in D:\Dev\stride\sources\engine\Stride.Graphics\Font\FontManager.cs:line 101
   at Stride.Graphics.Font.RuntimeRasterizedSpriteFont.GetGlyph(CommandList commandList, Char character, Vector2& fontSize, Boolean uploadGpuResources, Vector2& fixScaling) in D:\Dev\stride\sources\engine\Stride.Graphics\Font\RuntimeRasterizedSpriteFont.cs:line 111
   at Stride.Graphics.SpriteFont.ForGlyph[T](CommandList commandList, StringProxy& text, Vector2& fontSize, GlyphAction`1 action, T& parameters, Int32 forStart, Int32 forEnd, Boolean updateGpuResources, Single startX, Single startY) in D:\Dev\stride\sources\engine\Stride.Graphics\SpriteFont.cs:line 575
   at Stride.Graphics.SpriteFont.ForEachGlyph[T](CommandList commandList, StringProxy& text, Vector2& requestedFontSize, GlyphAction`1 action, T& parameters, TextAlignment scanOrder, Boolean updateGpuResources, Nullable`1 textBoxSize) in D:\Dev\stride\sources\engine\Stride.Graphics\SpriteFont.cs:line 512
   at Stride.Graphics.SpriteFont.MeasureString(StringProxy& text, Vector2& size) in D:\Dev\stride\sources\engine\Stride.Graphics\SpriteFont.cs:line 452
   at Stride.UI.Controls.TextBlock.CalculateTextSize(StringProxy textToMeasure) in D:\Dev\stride\sources\engine\Stride.UI\Controls\TextBlock.cs:line 261
   at Stride.UI.Controls.TextBlock.CalculateTextSize(String textToMeasure) in D:\Dev\stride\sources\engine\Stride.UI\Controls\TextBlock.cs:line 208
   at Stride.UI.Controls.TextBlock.MeasureOverride(Vector3 availableSizeWithoutMargins) in D:\Dev\stride\sources\engine\Stride.UI\Controls\TextBlock.cs:line 215
   at Stride.UI.UIElement.Measure(Vector3 availableSizeWithMargins) in D:\Dev\stride\sources\engine\Stride.UI\UIElement.cs:line 908
   at Stride.UI.Controls.ContentControl.MeasureOverride(Vector3 availableSizeWithoutMargins) in D:\Dev\stride\sources\engine\Stride.UI\Controls\ContentControl.cs:line 90
   at Stride.UI.Controls.Button.MeasureOverride(Vector3 availableSizeWithoutMargins) in D:\Dev\stride\sources\engine\Stride.UI\Controls\Button.cs:line 183
   at Stride.UI.UIElement.Measure(Vector3 availableSizeWithMargins) in D:\Dev\stride\sources\engine\Stride.UI\UIElement.cs:line 908
   at Stride.UI.Panels.StackPanel.MeasureOverride(Vector3 availableSizeWithoutMargins) in D:\Dev\stride\sources\engine\Stride.UI\Panels\StackPanel.cs:line 217
   at Stride.UI.UIElement.Measure(Vector3 availableSizeWithMargins) in D:\Dev\stride\sources\engine\Stride.UI\UIElement.cs:line 908
   at Stride.Rendering.UI.UIRenderFeature.DrawInternal(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex) in D:\Dev\stride\sources\engine\Stride.UI\Rendering\UI\UIRenderFeature.cs:line 234
   at Stride.Rendering.UI.UIRenderFeature.Draw(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex) in D:\Dev\stride\sources\engine\Stride.UI\Rendering\UI\UIRenderFeature.cs:line 86
   at Stride.Rendering.RenderSystem.Draw(RenderDrawContext renderDrawContext, RenderView renderView, RenderStage renderStage) in D:\Dev\stride\sources\engine\Stride.Rendering\Rendering\RenderSystem.cs:line 341
   at Stride.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount) in D:\Dev\stride\sources\engine\Stride.Engine\Rendering\Compositing\ForwardRenderer.cs:line 555
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext) in D:\Dev\stride\sources\engine\Stride.Engine\Rendering\Compositing\ForwardRenderer.cs:line 750
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context) in D:\Dev\stride\sources\engine\Stride.Rendering\Rendering\Compositing\SceneRendererBase.cs:line 38
   at Stride.Rendering.Compositing.EditorTopLevelCompositor.DrawInner(RenderDrawContext context) in D:\Dev\stride\sources\engine\Stride.Engine\Rendering\Compositing\EditorTopLevelCompositor.cs:line 61
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext) in D:\Dev\stride\sources\engine\Stride.Engine\Rendering\Compositing\SceneCameraRenderer.cs:line 70
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context) in D:\Dev\stride\sources\engine\Stride.Rendering\Rendering\Compositing\SceneRendererBase.cs:line 38
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context) in D:\Dev\stride\sources\engine\Stride.Engine\Rendering\Compositing\GraphicsCompositor.cs:line 116
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context) in D:\Dev\stride\sources\engine\Stride.Rendering\Rendering\RendererBase.cs:line 49
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime) in D:\Dev\stride\sources\engine\Stride.Engine\Engine\SceneSystem.cs:line 232
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime) in D:\Dev\stride\sources\engine\Stride.Games\GameSystemCollection.cs:line 125
   at Stride.Games.GameBase.Draw(GameTime gameTime) in D:\Dev\stride\sources\engine\Stride.Games\GameBase.cs:line 795
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Draw(GameTime gameTime) in D:\Dev\stride\sources\editor\Stride.Editor\EditorGame\Game\EditorServiceGame.cs:line 214
   ```

**Additional context**
This issue is very simiar, if not related to https://github.com/stride3d/stride/issues/1692 .

Q: Should I merge this with *1692*?

**Comment by NicusorN5** [comment]
With the latest master commit, I can't seem to reproduce this anymore. Closed for now. (Will reopen if it is the case)

**Comment by NicusorN5** [comment]
I was able to reproduce this after few attempts. The other attempts were crashes with different stacktraces.

This time, the stacktrace of the error is different from the one in the initial post.

```System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at SharpFont.FTVector26Dot6.get_X()
   at Stride.Graphics.Font.FontManager.GenerateCharacterGlyph(CharacterSpecification character, Boolean renderBitmap) in D:\Dev\Stride\sources\engine\Stride.Graphics\Font\FontManager.cs:line 144
   at Stride.Graphics.Font.FontManager.GenerateBitmap(CharacterSpecification characterSpecification, Boolean synchronously) in D:\Dev\Stride\sources\engine\Stride.Graphics\Font\FontManager.cs:line 101
   at Stride.Graphics.Font.RuntimeRasterizedSpriteFont.GetGlyph(CommandList commandList, Char character, Vector2& fontSize, Boolean uploadGpuResources, Vector2& fixScaling) in D:\Dev\Stride\sources\engine\Stride.Graphics\Font\RuntimeRasterizedSpriteFont.cs:line 113
   at Stride.Graphics.SpriteFont.ForGlyph[T](CommandList commandList, StringProxy& text, Vector2& fontSize, GlyphAction`1 action, T& parameters, Int32 forStart, Int32 forEnd, Boolean updateGpuResources, Single startX, Single startY) in D:\Dev\Stride\sources\engine\Stride.Graphics\SpriteFont.cs:line 575
   at Stride.Graphics.SpriteFont.ForEachGlyph[T](CommandList commandList, StringProxy& text, Vector2& requestedFontSize, GlyphAction`1 action, T& parameters, TextAlignment scanOrder, Boolean updateGpuResources, Nullable`1 textBoxSize) in D:\Dev\Stride\sources\engine\Stride.Graphics\SpriteFont.cs:line 512
   at Stride.Graphics.SpriteFont.MeasureString(StringProxy& text, Vector2& size) in D:\Dev\Stride\sources\engine\Stride.Graphics\SpriteFont.cs:line 452
   at Stride.UI.Controls.TextBlock.CalculateTextSize(StringProxy textToMeasure) in D:\Dev\Stride\sources\engine\Stride.UI\Controls\TextBlock.cs:line 241
   at Stride.UI.Controls.TextBlock.CalculateTextSize(String textToMeasure) in D:\Dev\Stride\sources\engine\Stride.UI\Controls\TextBlock.cs:line 208
   at Stride.UI.Controls.TextBlock.CalculateTextSize() in D:\Dev\Stride\sources\engine\Stride.UI\Controls\TextBlock.cs:line 186
   at Stride.UI.Controls.TextBlock.MeasureOverride(Vector3 availableSizeWithoutMargins) in D:\Dev\Stride\sources\engine\Stride.UI\Controls\TextBlock.cs:line 217
   at Stride.UI.UIElement.Measure(Vector3 availableSizeWithMargins) in D:\Dev\Stride\sources\engine\Stride.UI\UIElement.cs:line 908
   at Stride.UI.Controls.ContentControl.MeasureOverride(Vector3 availableSizeWithoutMargins) in D:\Dev\Stride\sources\engine\Stride.UI\Controls\ContentControl.cs:line 96
   at Stride.UI.Controls.Button.MeasureOverride(Vector3 availableSizeWithoutMargins) in D:\Dev\Stride\sources\engine\Stride.UI\Controls\Button.cs:line 183
   at Stride.UI.UIElement.Measure(Vector3 availableSizeWithMargins) in D:\Dev\Stride\sources\engine\Stride.UI\UIElement.cs:line 908
   at Stride.UI.Panels.StackPanel.MeasureOverride(Vector3 availableSizeWithoutMargins) in D:\Dev\Stride\sources\engine\Stride.UI\Panels\StackPanel.cs:line 218
   at Stride.UI.UIElement.Measure(Vector3 availableSizeWithMargins) in D:\Dev\Stride\sources\engine\Stride.UI\UIElement.cs:line 908
   at Stride.Rendering.UI.UIRenderFeature.DrawInternal(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex) in D:\Dev\Stride\sources\engine\Stride.UI\Rendering\UI\UIRenderFeature.cs:line 234
   at Stride.Rendering.UI.UIRenderFeature.Draw(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex) in D:\Dev\Stride\sources\engine\Stride.UI\Rendering\UI\UIRenderFeature.cs:line 86
   at Stride.Rendering.RenderSystem.Draw(RenderDrawContext renderDrawContext, RenderView renderView, RenderStage renderStage) in D:\Dev\Stride\sources\engine\Stride.Rendering\Rendering\RenderSystem.cs:line 341
   at Stride.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount) in D:\Dev\Stride\sources\engine\Stride.Engine\Rendering\Compositing\ForwardRenderer.cs:line 557
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext) in D:\Dev\Stride\sources\engine\Stride.Engine\Rendering\Compositing\ForwardRenderer.cs:line 750
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context) in D:\Dev\Stride\sources\engine\Stride.Rendering\Rendering\Compositing\SceneRendererBase.cs:line 39
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawInner(RenderDrawContext renderContext) in D:\Dev\Stride\sources\engine\Stride.Engine\Rendering\Compositing\SceneCameraRenderer.cs:line 105
   at Stride.Rendering.Compositing.EditorTopLevelCompositor.DrawInner(RenderDrawContext context) in D:\Dev\Stride\sources\engine\Stride.Engine\Rendering\Compositing\EditorTopLevelCompositor.cs:line 61
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext) in D:\Dev\Stride\sources\engine\Stride.Engine\Rendering\Compositing\SceneCameraRenderer.cs:line 70
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context) in D:\Dev\Stride\sources\engine\Stride.Rendering\Rendering\Compositing\SceneRendererBase.cs:line 39
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context) in D:\Dev\Stride\sources\engine\Stride.Engine\Rendering\Compositing\GraphicsCompositor.cs:line 184
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context) in D:\Dev\Stride\sources\engine\Stride.Rendering\Rendering\RendererBase.cs:line 49
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime) in D:\Dev\Stride\sources\engine\Stride.Engine\Engine\SceneSystem.cs:line 234
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime) in D:\Dev\Stride\sources\engine\Stride.Games\GameSystemCollection.cs:line 132
   at Stride.Games.GameBase.Draw(GameTime gameTime) in D:\Dev\Stride\sources\engine\Stride.Games\GameBase.cs:line 795
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Draw(GameTime gameTime) in D:\Dev\Stride\sources\editor\Stride.Editor\EditorGame\Game\EditorServiceGame.cs:line 214
   ```

**Comment by NicusorN5** [comment]
Moved to https://github.com/stride3d/stride/issues/1750 .
