### ISSUE TITLE
VR Template fails to create project

### ISSUE THREAD

**Issue by vpenades** [stride3d/stride#1766]
**Release Type**: Official Release/GitHub (please choose appropriate option)

Official

**Version**: Version number and/or git branch

4.1.0.1897

**Platform(s)**: Does the problem occur on Windows, Android...?

Windows

**Describe the bug**

On a fresh stride installation, when trying to create a VR Template, an error occurs:

"Error: An exception occurred while generating the template. (...)"

**To Reproduce**

Create a VR template

**Expected behavior**

The template is created successfully.

**Comment by Eideren** [comment]
Works as expected on my end, could you share the full logs, don't forget to press on the (...) button
![image](https://github.com/stride3d/stride/assets/5742236/83bcf99e-84c0-4fdf-b994-a6d9fdea5944)

**Comment by vpenades** [comment]
Here's the log

```
Error: An exception occurred while generating the template.
InvalidProjectFileException: Error del solucionador del SDK: "Error en el solucionador del SDK "Microsoft.DotNet.MSBuildWorkloadSdkResolver" al intentar resolver el SDK "Microsoft.NET.Sdk". Excepción: "Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: La dependencia del manifiesto de carga de trabajo 'Microsoft.NET.Workload.Emscripten' versión '6.0.4' es inferior a la versión '6.0.9' requerida por el manifiesto 'microsoft.net.workload.mono.toolchain' [C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.workload.mono.toolchain\WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult)"."  D:\Work\(_Stride_)\VrDemo1\VRSandbox5\VRSandbox5.Game\VRSandbox5.Game.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1](IElementLocation elementLocation, String resourceName, T1 arg0)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory)
   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)
   at Stride.Core.Assets.VSProjectHelper.LoadProject(String fullProjectLocation, String configuration, String platform, Dictionary`2 extraProperties) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\VSProjectHelper.cs:line 207
   at Stride.Assets.Presentation.Templates.TemplateSampleGenerator.Generate(SessionTemplateGeneratorParameters parameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\Templates\TemplateSampleGenerator.cs:line 72
   at Stride.Core.Assets.Editor.Components.TemplateDescriptions.SessionTemplateGenerator.Run(SessionTemplateGeneratorParameters parameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Core.Assets.Editor\Components\TemplateDescriptions\SessionTemplateGenerator.cs:line 41
   at Stride.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Core.Assets.Editor\Components\TemplateDescriptions\TemplateGeneratorHelper.cs:line 56

```

I have VisualStudio 2022 with Net7, but I also installed Net6 x64 as requested by the installer, specifically: dotnet-sdk-6.0.414-win-x64.exe

**Comment by Eideren** [comment]
Looks like it's an issue with VS or the build tools themselves ? Could you try this https://github.com/dotnet/maui/issues/9800#issuecomment-1246567310

**Comment by vpenades** [comment]
I'll look into it tonight

In the mean time, could you tell me if stride uses  Microsoft.Build.Locator?

**Comment by Eideren** [comment]
Yes, here's one of the csprojs which uses the MSBuild locator https://github.com/stride3d/stride/blob/master/sources/assets/Stride.Core.Assets/Stride.Core.Assets.csproj#L15

**Comment by vpenades** [comment]
Hmm... Is locator used widely along the whole framework?

Finding msbuild has become so difficult that even Microsoft is struggling, so they published this package as a way to standarize finding it... But it has lots of gotchas.... One we found is that you can only call locator before attempting to use any msbuild api

**Comment by Eideren** [comment]
Yes, the editor has to compile your project, hook a couple of things in and display popups and helpers when users don't have the necessary requirements installed.
If you can figure out a better way to deal with those issues without the locator, feel free to open a PR to replace it

**Comment by vpenades** [comment]
@Eideren I can't try the fix you suggested [here 9800](https://github.com/dotnet/maui/issues/9800#issuecomment-1246567310 ) because it may affect my development environment in unexpected ways and I can't afford to do that.

I do have some past experience with MSBuild.Locator, we maintain a few projects using it and we noticed, _at least in our case_ that the project referencing MsBuild locator must target the latest SDK available in the dev machine, otherwise it fails to find the SDK directory.

In my case I have installed these SDKs (dotnet sdk check):
![imagen](https://github.com/stride3d/stride/assets/5433822/4b75bbde-1ace-4d0e-be38-9c4d78d5e608)

And, the library we use that consumes MSBuild locator looks like this:
```c#
if (!Microsoft.Build.Locator.MSBuildLocator.IsRegistered)
    {
        try { Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults(); }
        catch (InvalidOperationException ex)
        {
            Console.Error.WriteLine(ex.Message + "\r\n Additionally, ensure that this application targets the VERY LATEST net framework available, net8.0, net9.0, whatever.");
            throw ex;
        }
    }
```

So in our case, that application is targeting Net7 just to ensure that Locator works correctly, targeting anything less (net6 or less) leads to obscure errors.

Also when we started working with locator, we had some issues related to Msbuild discovery under projects targeting different framework versions...  the issue is old and probably outdated, but it might give some useful insights:

https://github.com/microsoft/MSBuildLocator/issues/120#issuecomment-963970057

A point of interest is that I was suggested to register the Locator with a specific path, instead of RegisterDefault (in which case, I don't understand the point of RegisterDefault)

**Comment by vpenades** [comment]
Well... I've been trying to uninstall and reinstall SDKs...  I've also ended reinstalling the whole Visual Studio and the problem remains.

I don't know what else to do,
