### ISSUE TITLE
Skybox texture asset preview cause game studio crash

### ISSUE THREAD

**Issue by dawnmichal** [stride3d/stride#1770]
**Release Type**: Official Release

**Version**: 4.1.0.1897

**Platform(s)**: Windows

**Describe the bug**
Game studio crashes when skybox texture asset is deselected (during switching between assets). Asset preview panel must be active (visible), 

**To Reproduce**
1. Create standard empty project
2. Select "Skybox texture" asset in Asset view
3. Select "Asset preview" panel in bottom right corner (to see preview).
4. Select any another asset in Asset view (e.g. "Sphere Material")
5. Stride Game Studio crashes... 

**Expected behavior**
Show selected asset preview.

**Screenshots**
![StrideBug](https://github.com/stride3d/stride/assets/69644971/836bbd63-7d2c-490b-8bf6-176b6f679800)

**Log and callstacks**
Application: GameStudio
UserEmail: 
UserMessage: 
StrideVersion: 4.1.0.1897
GameStudioVersion: 4
ThreadName: PreviewGame Thread
DefaultGraphicProfile: Level_10_0
OpenedAssets: 499ab651-63de-4f09-8ca3-a6abbfd43859:MainScene (Scene)

LastActions: 
CurrentDirectory: %USERPROFILE%\.nuget\packages\stride.gamestudio\4.1.0.1897\tools\net6.0-windows7.0
CommandArgs: C:\dSoftware\dDrive\dDrive\dDrive.sln
OsVersion: Microsoft Windows 10 Pro 10.0.19045 x64
ProcessorCount: 16
Exception: NullReferenceException: Object reference not set to an instance of an object.
   at Stride.Graphics.CommandList.ClearStateImpl()
   at Stride.Graphics.CommandList.ClearState()
   at Stride.Games.GameBase.BeginDraw()
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
   at Stride.Games.GameBase.Tick()
   at Stride.Games.GamePlatform.Tick()
   at Stride.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GamePlatform.Run(GameContext gameContext)
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at Stride.Editor.Preview.GameStudioPreviewService.StrideUIThread() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Editor\Preview\GameStudioPreviewService.cs:line 151
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Diagnostics\SafeAction.cs:line 21
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

GPU0.AdapterCompatibility: NVIDIA
GPU0.AdapterDACType: Integrated RAMDAC
GPU0.AdapterRAM: 4293918720
GPU0.Availability: 3
GPU0.Caption: NVIDIA GeForce RTX 3060 Ti
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 2560
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 59
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 1440
GPU0.Description: NVIDIA GeForce RTX 3060 Ti
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20230814000000.000000-000
GPU0.DriverVersion: 31.0.15.3713
GPU0.InfFilename: oem51.inf
GPU0.InfSection: Section056
GPU0.InstalledDisplayDrivers: C:\WINDOWS\System32\DriverStore\FileRepository\nvmdi.inf_amd64_faac8d1bca70beae\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdi.inf_amd64_faac8d1bca70beae\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdi.inf_amd64_faac8d1bca70beae\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvmdi.inf_amd64_faac8d1bca70beae\nvldumdx.dll
GPU0.MaxRefreshRate: 75
GPU0.MinRefreshRate: 50
GPU0.Monochrome: False
GPU0.Name: NVIDIA GeForce RTX 3060 Ti
GPU0.PNPDeviceID: PCI\VEN_10DE&DEV_2486&SUBSYS_39091462&REV_A1\4&2283F625&0&0019
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: %USERNAME%
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 2560 x 1440 x 4294967296 barev
GPU0.VideoProcessor: NVIDIA GeForce RTX 3060 Ti
Log: 1: BasicCameraController(0,0): []: Fatal: The asset BasicCameraController is missing or incorrectly indexed in the package. Please report this issue.
2: dDriveApp(0,0): []: Fatal: The asset dDriveApp is missing or incorrectly indexed in the package. Please report this issue.
3: [Preview]: Error: An exception occurred while changing the previewed asset. System.InvalidOperationException: Could not recreate all objects.
   at Stride.Graphics.ResumeManager.OnRecreate()
   at Stride.Games.GameBase.GraphicsDeviceService_DeviceReset(Object sender, EventArgs e)
   at Stride.Games.GraphicsDeviceManager.OnDeviceReset(Object sender, EventArgs args)
   at Stride.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   at Stride.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   at Stride.Games.GraphicsDeviceManager.ApplyChanges()
   at Stride.Editor.Preview.AssetPreview.Initialize(AssetViewModel asset, IPreviewBuilder builder) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Editor\Preview\AssetPreview.cs:line 74
   at Stride.Editor.Preview.GameStudioPreviewService.ChangePreviewAsset() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Editor\Preview\GameStudioPreviewService.cs:line 268
4: [PreviewGame]: Error: Unexpected exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Stride.Graphics.CommandList.ClearStateImpl()
   at Stride.Graphics.CommandList.ClearState()
   at Stride.Games.GameBase.BeginDraw()
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
5: [SafeAction]: Fatal: Unexpected exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Stride.Graphics.CommandList.ClearStateImpl()
   at Stride.Graphics.CommandList.ClearState()
   at Stride.Games.GameBase.BeginDraw()
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
   at Stride.Games.GameBase.Tick()
   at Stride.Games.GamePlatform.Tick()
   at Stride.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GamePlatform.Run(GameContext gameContext)
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at Stride.Editor.Preview.GameStudioPreviewService.StrideUIThread() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Editor\Preview\GameStudioPreviewService.cs:line 151
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Diagnostics\SafeAction.cs:line 21

**Comment by NicusorN5** [comment]
I confirm this issue exists, as I just reproduced it. I will start looking for a fix.

**Comment by dawnmichal** [comment]
Game studio crash once I enabled asset preview for Font assets. But can't reproduce. Font asset preview works now... there is maybe some deeper problem with asset preview. But with skybox texture id easy to reproduce...

**Comment by NicusorN5** [comment]
I was also able to reproduce the `SpriteFont` asset crash once by these steps:
1.) First open Stride, with Asset Preview enabled
2.) Select any `SpriteFont` assset
3.) Crash

**Comment by NicusorN5** [comment]
As far as I tried to find a fix, it seems that this is all happening because of race conditions involving the `Asset Previewer` native(?) device and device context handles. I don't know how I can fix this. 😔 

Any help would be greatly appreciated.

It should be tested if this can be reproduced with Stride running under other GAPIs, like Vulkan.
