### ISSUE TITLE
Stop failing build for unserializable assets

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#1771]
The current problem:
Currently in Stride if it can't serialize a field or property it fails the whole build with a messy stacktrace error.

Potential solution:
Can we make it so it shows a warning instead and just ignores that field/property?

**Comment by Eideren** [comment]
Here's an example stacktrace related to the above:
```
[(0,0)]: Info: Assembly [SimpleMath, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null] has already been processed, skip it.
[(0,0)]: Info: SimpleMath -> C:\Stride Projects\Space Game\SimpleMath\bin\Debug\net6.0-windows\SimpleMath.dll
[(0,0)]: Info: Patch for assembly [SharedBase, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
[(0,0)]: Info: System.InvalidOperationException: Could not process serialization for member System.Collections.Generic.List`1<SharedBase.GridInventorySubnet>[] SharedBase.BlockGrid::subnets
[(0,0)]: Info:  ---> System.InvalidOperationException: Could not find serializer for generic dependent type SharedBase.GridInventorySubnet when processing System.Collections.Generic.List`1<SharedBase.GridInventorySubnet>
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.AddSerializableType(TypeReference dataType, SerializableTypeInfo serializableTypeInfo, String profile) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 540
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.GenerateSerializer(TypeReference type, Boolean force, String profile, Boolean generic) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 153
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.GenerateSerializer(TypeReference type, Boolean force, String profile, Boolean generic) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 86
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.ProcessComplexSerializerMembers(TypeReference type, SerializableTypeInfo serializableTypeInfo, String profile) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 215
[(0,0)]: Info:    --- End of inner exception stack trace ---
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.ProcessComplexSerializerMembers(TypeReference type, SerializableTypeInfo serializableTypeInfo, String profile) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 229
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilSerializerContext.FindSerializerInfo(TypeReference type, Boolean generic) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilSerializerContext.cs:line 365
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilComplexClassSerializerProcessor.ProcessType(CecilSerializerContext context, TypeDefinition type) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilComplexClassSerializerProcessor.cs:line 28
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.Serializers.CecilComplexClassSerializerProcessor.ProcessSerializers(CecilSerializerContext context) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\Serializers\CecilComplexClassSerializerProcessor.cs:line 18
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.ComplexSerializerRegistry..ctor(PlatformType platform, AssemblyDefinition assembly, TextWriter log) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\ComplexSerializerRegistry.cs:line 124
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.SerializationProcessor.Process(AssemblyProcessorContext context) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\SerializationProcessor.cs:line 45
[(0,0)]: Info:    at Stride.Core.AssemblyProcessor.AssemblyProcessorApp.Run(AssemblyDefinition& assemblyDefinition, Boolean& readWriteSymbols, Boolean& modified, Nullable`1& serializationHash) in C:\dev\stride\sources\core\Stride.Core.AssemblyProcessor\AssemblyProcessorApp.cs:line 262
[(0,0)]: Info: Unexpected error
[C:\Users\me\.nuget\packages\stride.core\4.1.0.1898\buildTransitive\Stride.Core.targets(92,5)]: Error: Failed to run assembly processor with parameters: --auto-notify-property --parameter-key --auto-module-initializer --serialization --add-reference="C:\Users\me\.nuget\packages\stride.engine\4.1.0.1898\lib\net6.0\Stride.Engine.dll" --add-reference="C:\Stride Projects\Space Game\SimpleMath\bin\Debug\net6.0-windows\SimpleMath.dll" --references-file="obj\Debug\net6.0-windows\StrideReferences.cache" --platform=Windows --targetFramework= "obj\Debug\net6.0-windows\SharedBase.dll"
[C:\Users\me\.nuget\packages\stride.core\4.1.0.1898\buildTransitive\Stride.Core.targets(92,5)]: Error: Check the previous logs
```
To repro:
```cs
public class A : SyncScript
{
    public List<B>[] Collections;
}

public class B
{
    public float SomeValue;
}
```

**Comment by CWilliamsDev** [comment]
If class B derives from SyncScript it will build. Not sure what the intention of that is.

**Comment by IXLLEGACYIXL** [comment]
> If class B derives from SyncScript it will build, it will then appear editable in the inspector of class A on the Entity. Not sure if that's intended or not.

if it inherits from synscript it gets [DataContract(Inherited=true)] and should be serialized then

**Comment by CWilliamsDev** [comment]
> > If class B derives from SyncScript it will build, it will then appear editable in the inspector of class A on the Entity. Not sure if that's intended or not.
> 
> if it inherits from synscript it gets [DataContract(Inherited=true)] and should be serialized then

This makes sense, was just trying to trouble shoot that build crash!

**Comment by Doprez** [comment]
> > > If class B derives from SyncScript it will build, it will then appear editable in the inspector of class A on the Entity. Not sure if that's intended or not.
> > 
> > 
> > if it inherits from synscript it gets [DataContract(Inherited=true)] and should be serialized then
> 
> This makes sense, was just trying to trouble shoot that build crash!

Yes, you are correct and that inheritance information is important to note. The goal of this issue is to make it so we skip these unserializable references instead of failing the asset compilation. 

This will hopefully be a  task for someone to work on in the future but this is not a major blocker, just an annoying process for users who don't know about it.

**Comment by IXLLEGACYIXL** [comment]
```
            var currentType = type;
            while (currentType != null)
            {
                var dataContractAttribute = AttributeRegistry.GetAttribute<DataContractAttribute>(currentType);
                if (dataContractAttribute != null && (dataContractAttribute.Inherited || currentType == type))
                {
                    DefaultMemberMode = dataContractAttribute.DefaultMemberMode;
                    hasDataContract = true;
                    break;
                }
                currentType = currentType.BaseType;
            }
```

in objectdescriptor this checks for the default member mode of the type, but it doesnt check if it even has a datacontract so its probably here a missing check
