### ISSUE TITLE
Editor crashes on launch after installing just .NET 6 & .NET 7 SDKs on a brand new OS

### ISSUE THREAD

**Issue by JeromyWalsh** [stride3d/stride#1885]
**Release Type**: Official Release/GitHub (please choose appropriate option)

Official Release

**Version**: Version number and/or git branch

4.1.0.1948

**Platform(s)**: Does the problem occur on Windows, Android...?

Windows 11 x64

**Describe the bug**
The editor crashes before executing when launched from a clean OS after having installed only the Installer, .NET 6.0 SDK and .NET 7.0 SDK

**To Reproduce**
1. Create a clean, non-development environment either by VM or fresh Windows 11 x64 installer.
2. Download & install the StrideSetup.exe
3. Install the .NET 7.0 SDK and .NET 6.0 SDK 
4. Launch the editor, create a new Windows "New Game..." project

**Expected behavior**
The editor/Game Studio launches with the new project loaded, ready for game development.

**Actual behavior**
The editor/Game Studio crashes before even showing the below crash report, before even opening.

**Screenshots**

![image](https://github.com/stride3d/stride/assets/17633767/a10a3fc5-0efb-415b-82a3-f157286b5dd1)

**Log and callstacks**
Application: GameStudio
UserEmail: 
UserMessage: 
StrideVersion: 4.1.0.1948
GameStudioVersion: 4
ThreadName: Main thread
DefaultGraphicProfile: Level_10_0
OpenedAssets: 
LastActions: 
CurrentDirectory: %USERPROFILE%\.nuget\packages\stride.gamestudio\4.1.0.1948\tools\net6.0-windows7.0
CommandArgs: %USERPROFILE%\Documents\Stride Projects\MyGame\MyGame.sln
OsVersion: Microsoft Windows 11 Home 10.0.22621 x64
ProcessorCount: 8
Exception: InvalidOperationException: Could not load native library freetype using CPU architecture x64.
   at Stride.Core.NativeLibraryHelper.PreloadLibrary(String libraryName, Type owner) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Native\NativeLibraryHelper.cs:line 156
   at Stride.Graphics.Font.FontManager..ctor(IDatabaseFileProviderService fileProviderService)
   at Stride.Graphics.Font.FontSystem.Load(GraphicsDevice graphicsDevice, IDatabaseFileProviderService fileProviderService)
   at Stride.Rendering.Fonts.GameFontSystem.LoadContent() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Rendering\Rendering\Fonts\GameFontSystem.cs:line 36
   at Stride.Games.GameSystemBase.Stride.Games.IContentable.LoadContent()
   at Stride.Games.GameSystemCollection.LoadContent()
   at Stride.Editor.Thumbnails.ThumbnailGenerator..ctor(EffectCompilerBase effectCompiler) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Editor\Thumbnails\ThumbnailGenerator.cs:line 146
   at Stride.Editor.Thumbnails.GameStudioThumbnailService..ctor(SessionViewModel session, GameSettingsProviderService settingsProvider, GameStudioBuilderService assetBuilderService) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Editor\Thumbnails\GameStudioThumbnailService.cs:line 54
   at Stride.GameStudio.StrideEditorPlugin.InitializeSession(SessionViewModel session) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.GameStudio\StrideEditorPlugin.cs:line 82
   at Stride.GameStudio.GameStudioWindow.<GameStudioLoaded>b__36_0(AssetsPlugin x) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.GameStudio\GameStudioWindow.xaml.cs:line 251
   at Stride.Core.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Extensions\EnumerableExtensions.cs:line 57
   at Stride.GameStudio.GameStudioWindow.GameStudioLoaded(Object sender, RoutedEventArgs e) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.GameStudio\GameStudioWindow.xaml.cs:line 251
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
 
GPU0.AdapterCompatibility: Oracle Corporation
GPU0.AdapterDACType: 
GPU0.AdapterRAM: 0
GPU0.Availability: 3
GPU0.Caption: VirtualBox Graphics Adapter (WDDM)
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1884
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 1
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 1124
GPU0.Description: VirtualBox Graphics Adapter (WDDM)
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20221116000000.000000-000
GPU0.DriverVersion: 7.0.4.4605
GPU0.InfFilename: oem2.inf
GPU0.InfSection: VBoxVideo
GPU0.InstalledDisplayDrivers: VBoxDispD3D.dll,VBoxDX.dll,VBoxDX.dll
GPU0.MaxRefreshRate: 64
GPU0.MinRefreshRate: 64
GPU0.Monochrome: False
GPU0.Name: VirtualBox Graphics Adapter (WDDM)
GPU0.PNPDeviceID: PCI\VEN_80EE&DEV_BEEF&SUBSYS_040515AD&REV_00\3&267A616A&0&10
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: WINDOWS-11
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1884 x 1124 x 4294967296 colors
GPU0.VideoProcessor: 
Log: 1: BasicCameraController(0,0): []: Fatal: The asset BasicCameraController is missing or incorrectly indexed in the package. Please report this issue.
2: MyGameApp(0,0): []: Fatal: The asset MyGameApp is missing or incorrectly indexed in the package. Please report this issue.
3: [AssetsCompiler.AttributeBasedRegistry]: Error: Unable to instantiate compiler [Stride.Assets.Physics.ColliderShapeAsset, Stride.Assets, Version=4.1.0.1948, Culture=neutral, PublicKeyToken=null]. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Stride.Assets.Physics.ColliderShapeAssetCompiler' threw an exception.
 ---> System.InvalidOperationException: Could not load native library VHACD using CPU architecture x64.
   at Stride.Core.NativeLibraryHelper.PreloadLibrary(String libraryName, Type owner) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Native\NativeLibraryHelper.cs:line 156
   at Stride.Assets.Physics.ColliderShapeAssetCompiler..cctor() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Assets\Physics\ColliderShapeAssetCompiler.cs:line 30
   --- End of inner exception stack trace ---
   at Stride.Assets.Physics.ColliderShapeAssetCompiler..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at Stride.Core.Assets.Compiler.AssetCompilerRegistry.ProcessAttribute(AssetCompilerAttribute compilerCompilerAttribute, Type type) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Compiler\AssetCompilerRegistry.cs:line 161
   at Stride.Core.Assets.Compiler.AssetCompilerRegistry.RegisterCompilersFromAssembly(Assembly assembly) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Compiler\AssetCompilerRegistry.cs:line 198

**Additional context**

**Comment by JeromyWalsh** [comment]
I updated the title and description after confirming it does not require the installation of .NET 7 SDK to repro. I created a new VM with just .NET 6 SDK and Stride and I still get the same crash report.

Stride Version: 4.1.0.1948
OsVersion: Microsoft Windows 11 Home 10.0.22621 x64

**Comment by JeromyWalsh** [comment]
On the creation of a new VM I did things in a slightly different order, which included the installation of Visual Studio 2022 Community Edition. I did not get the above exception. I'm going to install a new VM and double check, but it's likely the above issue is mitigated by ensuring Visual Studio 2022 is installed. This obviously should not be necessary to use Stride.

**Comment by JeromyWalsh** [comment]
I confirmed. After experiencing the crash on launch, I proceeded to install Visual Studio 2022 Community Edition with the Managed + Native Desktop profiles and Native Game Development profile and was able to launch the Game Studio successfully. Whatever the root cause, it's *mitigated* by having Visual Studio 2022 installed, though this still shouldn't be a requirement.

**Comment by Eideren** [comment]
#837 has a similar error

**Comment by JeromyWalsh** [comment]
@Eideren Can you assign this to me?

**Comment by IXLLEGACYIXL** [comment]
could you also check the behaviour after installing  .net6 and not Rebooting?
a .net install requires a reboot after installation, this happened often in discord that people were missing that step

**Comment by JeromyWalsh** [comment]
As a general rule, .NET 6 doesn't require a reboot after installing the SDK. If the editor is having issues running after installing the SDK, it's likely a problem with the editor that should be addressed as a separate bug. Do you have a specific repro? @IXLLEGACYIXL

**Comment by IXLLEGACYIXL** [comment]
> As a general rule, .NET 6 doesn't require a reboot after installing the SDK. If the editor is having issues running after installing the SDK, it's likely a problem with the editor that should be addressed as a separate bug. Do you have a specific repro? @IXLLEGACYIXL

a .net sdk installation needs a shell restart which is in linux easy but in windows its more complicated so a normal restart is easier
https://discord.com/channels/500285081265635328/740163288746426368/1154056210576842762
one of the cases where it made problems

windows behaviour != linux behaviour

**Comment by JeromyWalsh** [comment]
Hi @IXLLEGACYIXL. I'm not sure why you're making a comparison between Windows & Linux here. This bug is about Windows and has nothing to do with Linux (has Linux even been mentioned before?). As well, this bug isn't about the installation of the .NET 6 SDK per say. It's about how after installing the .NET 6 SDK there are still unadvertised missing dependencies that cause a hard crash on startup. 

In reply to your message, while a shell restart **is** required after installing the .NET SDK, a machine reboot **is not** required (see the screenshot below). So again, if after installing the .NET SDK a machine reboot is required to get the Stride Game Studio working, that's an issue with Stride that should get a bug of its own so we can root cause it and fix it.

![image](https://github.com/stride3d/stride/assets/17633767/82ba4d4d-4057-498e-be9b-1617143e59f1)

As a side note, I'm not sure why you felt the need to identify "windows behavior != linux behavior." Aside from the fact this bug had absolutely nothing to do with Linux, do most people assume Windows and Linux behavior is the same?
