### ISSUE TITLE
Crash on Save

### ISSUE THREAD

**Issue by MCVenor** [stride3d/stride#1917]
**Release Type**: Official Release
**Version**: 4.1.0.1948

**Platform(s)**: Windows 10 Pro

**Describe the bug**
I hit Ctrl+S and the bug apears.

**To Reproduce**
1. Create basic Project from YT Tutorial
2. Delete everything
3. Delete Scene assets too
4. place some objects and play around with the values
5. Hit Ctrl+S

**Screenshots**
![grafik](https://github.com/stride3d/stride/assets/12583072/538a0c1f-a63d-433a-b9ac-fcf49cfa0cc9)

**Log and callstacks**
Error: There was a problem saving the solution. Value cannot be null. (Parameter 'value')
ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.IO.BinaryWriter.Write(String value)
   at Stride.Core.Assets.AssetReferenceDataSerializer.Serialize(AssetReference& assetReference, ArchiveMode mode, SerializationStream stream) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\AssetReferenceDataSerializer.cs:line 29
   at Stride.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Serialization\MemberSerializerGenerated.cs:line 1122
   at Stride.Core.Serialization.Serializers.KeyedSortedListSerializer`3.Serialize(TKeyedList& obj, ArchiveMode mode, SerializationStream stream) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Serialization\Serializers\KeyedSortedListSerializer.cs:line 50
   at Stride.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Serialization\MemberSerializerGenerated.cs:line 1122
   at Stride.Core.DataSerializers.StrideCoreAssets_PackageSerializer.Serialize(Package& obj, ArchiveMode mode, SerializationStream stream)
   at Stride.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Serialization\DataSerializer.cs:line 85
   at Stride.Core.Serialization.MemberReuseSerializer`1.SerializeExtended(T& obj, ArchiveMode mode, SerializationStream stream, DataSerializer`1 dataSerializer) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Serialization\MemberSerializerGenerated.cs:line 1317
   at Stride.Core.Assets.AssetCloner..ctor(Object value, AssetClonerFlags flags, IEnumerable`1 externalIdentifiables) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\AssetCloner.cs:line 78
   at Stride.Core.Assets.Package.Clone() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\Package.cs:line 387
   at Stride.Core.Assets.PackageSession.Save(ILogger log, PackageSaveParameters saveParameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\PackageSession.cs:line 1107
   at Stride.Core.Assets.Editor.ViewModel.SessionViewModel.<>c__DisplayClass194_0.<SaveSession>b__0() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Core.Assets.Editor\ViewModel\SessionViewModel.cs:line 924

**Additional context**
After watching the tutorials i wanted to try around in the editor to get a feel. I deleted everything from the basic tutorial scenery, i also deleted the scenes in the assets. Added 2 empty entities in the current main scene, made 1 cube with no material in the assets, 1 plane with metalic blue material and added both to the scene. Then i added a directional light and a point light.
The directional light was repositioned and then the Point lights radius was adjusted with the mouse first, but it was to wild of an increase, so i typed a number instead, 10.
I noticed that the alt key did not allow me to orbit in the Viewport when alt was pressed either outside of before the Viewport focus/under mouse. Then i hit Ctrl+S and the bug popped. I thought its because the cube without material, deleted it, tried again, same problem.
Then i deleted some assets , same problem still.

**Comment by JeromyWalsh** [comment]
Hi @MCVenor. Which tutorial were you following? At what point in the tutorial did you delete everything?

**Comment by MCVenor** [comment]
The tutorial has no part in this as in the tutorial did not instruct me to delete everything. This is just to give a context where i got the initial scene/project from  
This is the tutorial in question [LINK](https://www.youtube.com/watch?v=Z2kUQhSmdr0&list=PLRZx2y7uC8mNySUMfOQf-TLNVnnHkLfPi&ab_channel=Stride)

**Comment by JeromyWalsh** [comment]
Hi @MCVenor, I completely understand the tutorial didn't instruct you to delete everything. 

The exception is likely a result of something not properly being cleaned up after it was deleted. So, knowing what you'd done before deleting will help speedup the process of isolating the problem.

**Comment by jhimes144** [comment]
I'm able to recreate this bug. I run into it quiet frequently.

**Comment by IXLLEGACYIXL** [comment]
> I'm able to recreate this bug. I run into it quiet frequently.

does  it happen by not pressing ctrl s so long?
