### ISSUE TITLE
Can't import FBX file

### ISSUE THREAD

**Issue by lightway82** [stride3d/stride#1989]
**Release Type**: 
Official Release

**Version**: 
4.1.0.1948

**Platform(s)**: 
Windows

**Describe the bug**
Can't import FBX file.

**To Reproduce**
1. Imports this fbx file.
[test.zip](https://github.com/stride3d/stride/files/13168874/test.zip)

**Log and callstacks**

Error: Failed to create new asset from template.
ArgumentException: Asset location [/obj/matnet_vray/vray_man_golova1] must be relative and not absolute (not start with '/') (Parameter 'item')
   at Stride.Core.Assets.PackageAssetCollection.CheckCanAdd(AssetItem item) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\PackageAssetCollection.cs:line 361
   at Stride.Core.Assets.PackageAssetCollection.Add(AssetItem item) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets\PackageAssetCollection.cs:line 151
   at Stride.Assets.Presentation.Templates.AssetTemplateGenerator.Run(AssetTemplateGeneratorParameters parameters) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\Templates\AssetTemplateGenerator.cs:line 52

**Comment by tebjan** [comment]
Thanks for the report!

**Comment by manio143** [comment]
Had a quick look. I think we should disallow `/` in material names here:
https://github.com/stride3d/stride/blob/e200843806af650ad45595f87a78374712ecaeea/sources/tools/Stride.Importer.FBX/MeshConverter.cpp#L1607
It's treated as a path separator in asset URLs, hence the exception. We already replace `:` with `_` and can do the same for `/`.

**Comment by rizwan3d** [comment]
Hi @manio143  .
I've made some progress on it; could you take a look?
Thanks.
