### ISSUE TITLE
Got Error when enable the GameProfiling

### ISSUE THREAD

**Issue by ly3027929699** [stride3d/stride#2040]
**Release Type**: GitHub 

**Version**: the latest(.net8)

**Platform(s)**: Windows (Direct3D12)

**Describe the bug**
as title

**To Reproduce**
1. Enable the GameProfiling when select 'Direct3D12'

**Expected behavior**

**Log and callstacks**
[MyGame]: Error: Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: ��������

   at SharpDX.Result.CheckError() in C:\projects\sharpdx\Source\SharpDX\Result.cs:line 195
   at SharpDX.Direct3D12.Device.CreateCommittedResource(HeapProperties& heapPropertiesRef, HeapFlags heapFlags, ResourceDescription& descRef, ResourceStates initialResourceState, Nullable`1 optimizedClearValueRef, Guid riidResource) in C:\projects\sharpdx\Source\SharpDX.Direct3D12\Generated\REFERENCE\Interfaces.cs:line 1398
   at SharpDX.Direct3D12.Device.CreateCommittedResource(HeapProperties heapPropertiesRef, HeapFlags heapFlags, ResourceDescription resourceDescRef, ResourceStates initialResourceState, Nullable`1 optimizedClearValueRef) in C:\projects\sharpdx\Source\SharpDX.Direct3D12\Device.cs:line 221
   at Stride.Graphics.Buffer.Recreate(IntPtr dataPointer)
   at Stride.Graphics.Buffer.InitializeFromImpl(BufferDescription description, BufferFlags viewFlags, PixelFormat viewFormat, IntPtr dataPointer)
   at Stride.Graphics.Buffer`1..ctor(GraphicsDevice device, BufferDescription description, BufferFlags viewFlags, PixelFormat viewFormat, IntPtr dataPointer)
   at Stride.Graphics.Buffer.New[T](GraphicsDevice device, T[] initialValue, BufferFlags bufferFlags, PixelFormat viewFormat, GraphicsResourceUsage usage)
   at Stride.Graphics.Buffer.New[T](GraphicsDevice device, T[] initialValue, BufferFlags bufferFlags, GraphicsResourceUsage usage)
   at Stride.Graphics.Buffer.Vertex.New[T](GraphicsDevice device, T[] value, GraphicsResourceUsage usage)
   at Stride.Graphics.FastTextRenderer.Initialize(GraphicsContext graphicsContext, Int32 maxCharacters)
   at Stride.Graphics.FastTextRenderer..ctor(GraphicsContext graphicsContext, Int32 maxCharacterCount)
   at Stride.Profiling.GameProfilingSystem.Draw(GameTime gameTime) in E:\Stride\stride\sources\engine\Stride.Engine\Profiling\GameProfilingSystem.cs:line 354
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()

**Comment by ly3027929699** [comment]
Message: Parameter Error

**Comment by tebjan** [comment]
Would be interesting whether this issue was there before .NET 8 and the FastTextRenderer rewrite...
