### ISSUE TITLE
a .net exception from fairly simple code

### ISSUE THREAD

**Issue by Acromatic** [stride3d/stride#2074]
Look someone on discord created this .net exception incase it's relevant to you guys

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Stride.Core.Serialization.Contents.ContentManagerException: Unexpected exception while loading asset [Skybox/gen/Texture_1]. Reason: Content serializer for Stride.Graphics.Texture/Stride.Graphics.Image could not be found.. Check inner-exception for details.
 ---> System.InvalidOperationException: Content serializer for Stride.Graphics.Texture/Stride.Graphics.Image could not be found.
   at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(Queue`1 serializeOperations, Reference parentReference, String url, Type objType, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 510
   --- End of inner exception stack trace ---
   at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(Queue`1 serializeOperations, Reference parentReference, String url, Type objType, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 550
   at Stride.Core.Serialization.Contents.ContentManager.DeserializeObject(String initialUrl, String newUrl, Type type, Object obj, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 387
   at Stride.Core.Serialization.Contents.ContentManager.Load(Type type, String url, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 136
   at Stride.Core.Serialization.Contents.ContentManager.Load[T](String url, ContentManagerLoaderSettings settings) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Serialization\Serialization\Contents\ContentManager.cs:line 113
   at Stride.Graphics.Data.TextureContentSerializer.<>c.<Serialize>b__1_0(GraphicsResourceBase graphicsResource, IServiceRegistry services)
   at Stride.Graphics.ResumeManager.OnReload()
   at Stride.Games.GameBase.GraphicsDeviceService_DeviceReset(Object sender, EventArgs e)
   at Stride.Games.GraphicsDeviceManager.OnDeviceReset(Object sender, EventArgs args)
   at Stride.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   at Stride.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   at Stride.Games.GraphicsDeviceManager.ApplyChanges()
   at Stride.Games.GraphicsDeviceManager.Window_FullscreenChanged(Object sender, EventArgs eventArgs)
   at Stride.Games.GameWindow.set_IsFullscreen(Boolean value)
   at Stride.Games.GameWindow.OnFullscreenToggle(Object source, EventArgs e)
   at Stride.Games.GameForm.OnFullscreenToggle(EventArgs e)
   at Stride.Games.GameForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Private.CoreLib.dll
----------------------------------------
Miner_Jem.Windows
    Assembly Version: 1.0.0.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Miner_Jem.Windows.dll
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Runtime.dll
----------------------------------------
Stride.Core
    Assembly Version: 4.2.0.1
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Core.dll
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Collections.dll
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Threading.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Private.Uri.dll
----------------------------------------
ServiceWire
    Assembly Version: 5.3.4.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\ServiceWire.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\netstandard.dll
----------------------------------------
Stride.Engine
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Engine.dll
----------------------------------------
Stride.Core.Serialization
    Assembly Version: 4.2.0.1
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Core.Serialization.dll
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Linq.dll
----------------------------------------
Stride.Rendering
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Rendering.dll
----------------------------------------
Stride.Graphics
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Graphics.dll
----------------------------------------
Stride.Shaders
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Shaders.dll
----------------------------------------
Stride
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.dll
----------------------------------------
Stride.Core.Mathematics
    Assembly Version: 4.2.0.1
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Core.Mathematics.dll
----------------------------------------
SharpDX.Direct3D11
    Assembly Version: 4.2.0.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\SharpDX.Direct3D11.dll
----------------------------------------
Stride.Native
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Native.dll
----------------------------------------
Stride.Audio
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Audio.dll
----------------------------------------
Stride.VirtualReality
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.VirtualReality.dll
----------------------------------------
Stride.Input
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Input.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Diagnostics.DiagnosticSource.dll
----------------------------------------
Stride.Core.Shaders
    Assembly Version: 4.2.0.1
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Core.Shaders.dll
----------------------------------------
Stride.Shaders.Parser
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Shaders.Parser.dll
----------------------------------------
Miner_Jem
    Assembly Version: 1.0.0.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Miner_Jem.dll
----------------------------------------
Stride.Physics
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Physics.dll
----------------------------------------
BulletSharp.NetStandard
    Assembly Version: 1.0.0.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\BulletSharp.NetStandard.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Runtime.InteropServices.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Diagnostics.Process.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.ComponentModel.Primitives.dll
----------------------------------------
Stride.UI
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.UI.dll
----------------------------------------
Stride.Video
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Video.dll
----------------------------------------
Stride.Navigation
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Navigation.dll
----------------------------------------
Stride.Particles
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Particles.dll
----------------------------------------
Stride.Games
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Games.dll
----------------------------------------
Stride.Core.IO
    Assembly Version: 4.2.0.1
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Core.IO.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.ObjectModel.dll
----------------------------------------
Stride.Core.MicroThreading
    Assembly Version: 4.2.0.1
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Core.MicroThreading.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Collections.Concurrent.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Diagnostics.Tracing.dll
----------------------------------------
System.Threading.Channels
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Threading.Channels.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Threading.ThreadPool.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Threading.Thread.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0\System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0\System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0\Accessibility.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Text.RegularExpressions.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Threading.Overlapped.dll
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Memory.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.IO.Compression.dll
----------------------------------------
K4os.Compression.LZ4
    Assembly Version: 1.2.16.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\K4os.Compression.LZ4.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
Silk.NET.SDL
    Assembly Version: 2.17.1.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Silk.NET.SDL.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Numerics.Vectors.dll
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 4.2.0.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\SharpDX.DirectInput.dll
----------------------------------------
SharpDX
    Assembly Version: 4.2.0.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\SharpDX.dll
----------------------------------------
System.Reflection
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Reflection.dll
----------------------------------------
SharpDX.XInput
    Assembly Version: 4.2.0.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\SharpDX.XInput.dll
----------------------------------------
Stride.Shaders.Compiler
    Assembly Version: 4.2.0.2043
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\Stride.Shaders.Compiler.dll
----------------------------------------
SharpDX.DXGI
    Assembly Version: 4.2.0.0
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\SharpDX.DXGI.dll
----------------------------------------
SharpFont
    Assembly Version: 3.1.0.200
    Location: D:\repos\Miner Jem\Bin\Windows\Debug\win-x64\SharpFont.dll
----------------------------------------
System.Console
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Console.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Text.Encoding.Extensions.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.Collections.Immutable.dll
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly Version: 8.0.0.0
    Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\System.IO.MemoryMappedFiles.dll
----------------------------------------

************** JIT Debugging **************



```

**Comment by Kryptos-FR** [comment]
Without the source code or the asset that caused t, it is pretty useless.

**Comment by Eideren** [comment]
Duplicate of #2008 and #1493
