### ISSUE TITLE
External class reference bug

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#2081]
**Release Type**: Official Release and GitHub

**Version**: 4.2.0.2043 and master

**Platform(s)**: Windows

**Describe the bug**
I will add more info when Im not tired. but the gist is when using a project reference with EntityComponents, the Gamestudio will throw incorrect Errors and dereference properties.

```csharp
// in the main project
public Test : StartupScript
{
    // EntityComponent inherited class from a seperate referenced project
    public EntityComponentThing Test {get; set;}
}
```

The above will either give an error of duplicate reference ID or just remove the reference entirely, I couldnt get a consistant result there. 

**To Reproduce**
1. create a default project
2. add an external library project
3. add an EntityComponent class in the referenced project
4. add a public reference of that class to a script in the main project

this should be where the error fails.

**Expected behavior**
References should remain and there should be no false positive errors in the output.

**Screenshots**
Duplicate false positive, it was counting references as duplicate objects/entities.

![image](https://github.com/stride3d/stride/assets/73259914/7600d723-1a48-4791-9b54-ffdfd74e3133)

second image to go with the log below.

![image](https://github.com/stride3d/stride/assets/73259914/918c9a32-ffd9-4d08-8438-e1a33aadade5)

**Log and callstacks**
below is an error that seemed to come from one of the references that came from the external project. For some reason it was unable to set the Entity on the component hence the "Cannot add a null component" error. image is the second one above where this error came from.
```
Error: Could not restore asset after assembly reload
TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> ArgumentNullException: Cannot add a null component (Parameter 'item')
   at Stride.Engine.EntityComponentCollection.ValidateItem(Int32 index, EntityComponent item, Boolean isReplacing) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Engine\Engine\EntityComponentCollection.cs:line 208
   at Stride.Engine.EntityComponentCollection.InsertItem(Int32 index, EntityComponent item) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.Engine\Engine\EntityComponentCollection.cs:line 165
   at InvokeStub_FastCollection`1.Add(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Stride.Core.Reflection.ListDescriptor.<>c__DisplayClass11_0.<.ctor>b__8(Object obj, Object value) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core.Reflection\TypeDescriptors\ListDescriptor.cs:line 61
   at Stride.Core.Quantum.ObjectNode.Add(Object newItem, NodeIndex itemIndex) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\ObjectNode.cs:line 127
   at Stride.Core.Assets.Quantum.Internal.AssetObjectNodeExtended.Restore(Object restoredItem, NodeIndex index, ItemId id) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets.Quantum\Internal\AssetObjectNodeExtended.cs:line 142
   at Stride.Core.Assets.Quantum.Internal.AssetObjectNode.Restore(Object restoredItem, NodeIndex index, ItemId id) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets.Quantum\Internal\AssetObjectNode.cs:line 52
   at Stride.Assets.Presentation.AssemblyReloading.GameStudioAssemblyReloader.ReplaceNode(IUndoRedoService actionService, AssetViewModel asset, ItemToReload itemToReload) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\AssemblyReloading\GameStudioAssemblyReloader.cs:line 222
   at Stride.Assets.Presentation.AssemblyReloading.GameStudioAssemblyReloader.PostAssemblyReloading(IUndoRedoService actionService, SessionNodeContainer nodeContainer, ReloadingVisitor reloaderVisitor, ILogger log, Dictionary`2 assetItemsToReload) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\AssemblyReloading\GameStudioAssemblyReloader.cs:line 150
   at Stride.Assets.Presentation.AssemblyReloading.GameStudioAssemblyReloader.Reload(SessionViewModel session, ILogger log, Action postReloadAction, Action undoAction, Dictionary`2 modifiedAssemblies) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\AssemblyReloading\GameStudioAssemblyReloader.cs:line 77
   at Stride.GameStudio.ViewModels.DebuggingViewModel.ReloadAssemblies() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.GameStudio\ViewModels\DebuggingViewModel.cs:line 280
```

**Additional context**
[Long discussion between @Nicogo1705 @Eideren  and I in Discord](https://discord.com/channels/500285081265635328/1183088711810945157/1184974984322486422)

**Comment by IXLLEGACYIXL** [comment]
is the issue that the property has the same name as the class?
i can remember that i had the problem

**Comment by Nicogo1705** [comment]
![image](https://github.com/stride3d/stride/assets/20603105/9a9881a4-10d4-44e9-8006-4d70b7c57649)
don't think so, because it looks like the issue is here too.

**Comment by Nicogo1705** [comment]
Here is a repro :
https://github.com/Nicogo1705/IssueRefStride

To get the error : should get it when starting stride. If not, clean the solution with VS.
Then click :
![image](https://github.com/stride3d/stride/assets/20603105/42c778ba-5797-4c3d-8204-4a165f76b117)

**Comment by Doprez** [comment]
Adding on to this:
It seems like the issue does NOT happen when you are using the Nuget release of a project. only with the source of a referenced project.

Referenced source project
![image](https://github.com/stride3d/stride/assets/73259914/3dcc14ae-ded8-4b2b-a2bc-ee1993c2e8e7)

Nuget referenced
![image](https://github.com/stride3d/stride/assets/73259914/63cd8cac-213b-45fd-87db-e2e8ec4233ea)

**Comment by Kryptos-FR** [comment]
Is the same issue occuring on 4.1? Could be related to recent changes on the NuGetResolver.

**Comment by IXLLEGACYIXL** [comment]
```
Error: [A]MyLib.TestB cannot be cast to [B]MyLib.TestB. Type A originates from 'MyLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context '"Assembly.Load(byte[], ...)" System.Runtime.Loader.IndividualAssemblyLoadContext #12' in a byte array. Type B originates from 'MyLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context '"Assembly.Load(byte[], ...)" System.Runtime.Loader.IndividualAssemblyLoadContext #6' in a byte array.
```
changing the type dictionary to type.fullname results in this
Invalidated doesnt get triggered for the external projects serializer, so there is an old serializer in the dictionary

**Comment by IXLLEGACYIXL** [comment]
i cant reproduce the issue with repair projectwatcher PR
![grafik](https://github.com/stride3d/stride/assets/107197024/6df523ff-eda3-4d27-b8d9-2a475d37ef42)
