### ISSUE TITLE
IDE crash - Exception: InvalidCastException: Unable to cast object of type 'Stride.Assets.Models.ModelAsset' to type 

### ISSUE THREAD

**Issue by Generalec** [stride3d/stride#2166]
I will no able to describe specific way how to reproduce this problem. _I can share project._

I been doing some adjustments to models and materials I was putting material map texture on material - surface on several models.

After I restarted Stride I'm not able to run IDE because crash.

`Application: GameStudio
UserEmail: 
UserMessage: 
StrideVersion: 4.2.0.2067
GameStudioVersion: 4
ThreadName: .NET TP Worker
LastActions: 
CurrentDirectory: %USERPROFILE%\.nuget\packages\stride.gamestudio\4.2.0.2067\lib\net8.0-windows7.0
CommandArgs: %USERPROFILE%\Documents\Stride Projects\MyGame3_\MyGame3.sln
OsVersion: Microsoft Windows 10 Business 10.0.19045 x64
ProcessorCount: 16
Exception: InvalidCastException: Unable to cast object of type 'Stride.Assets.Models.ModelAsset' to type 'Stride.Core.Assets.AssetCompositeHierarchy`2[Stride.Assets.Entities.EntityDesign,Stride.Engine.Entity]'.
   at Stride.Core.Assets.Quantum.AssetCompositeHierarchyPropertyGraph`2.FindTarget(IGraphNode sourceNode, IGraphNode target) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets.Quantum\AssetCompositeHierarchyPropertyGraph.cs:line 252
   at Stride.Assets.Presentation.Quantum.EntityHierarchyPropertyGraph.FindTarget(IGraphNode sourceNode, IGraphNode target) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\Quantum\EntityHierarchyPropertyGraph.cs:line 34
   at Stride.Core.Assets.Quantum.AssetToBaseNodeLinker.FindTarget(IGraphNode sourceNode) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets.Quantum\AssetToBaseNodeLinker.cs:line 30
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 38
   at Stride.Core.Quantum.GraphVisitorBase.VisitReference(IGraphNode referencer, ObjectReference reference) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 170
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitReference(IGraphNode referencer, ObjectReference reference) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 93
   at Stride.Core.Quantum.GraphVisitorBase.VisitMemberTarget(IMemberNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 130
   at Stride.Core.Quantum.GraphVisitorBase.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 76
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 42
   at Stride.Core.Quantum.GraphVisitorBase.VisitChildren(IObjectNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 94
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitChildren(IObjectNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 73
   at Stride.Core.Quantum.GraphVisitorBase.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 70
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 42
   at Stride.Core.Quantum.GraphVisitorBase.VisitReference(IGraphNode referencer, ObjectReference reference) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 170
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitReference(IGraphNode referencer, ObjectReference reference) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 93
   at Stride.Core.Quantum.GraphVisitorBase.VisitItemTargets(IObjectNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 154
   at Stride.Core.Quantum.GraphVisitorBase.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 71
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 42
   at Stride.Core.Quantum.GraphVisitorBase.VisitReference(IGraphNode referencer, ObjectReference reference) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 170
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitReference(IGraphNode referencer, ObjectReference reference) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 93
   at Stride.Core.Quantum.GraphVisitorBase.VisitMemberTarget(IMemberNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 130
   at Stride.Core.Quantum.GraphVisitorBase.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 76
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 42
   at Stride.Core.Quantum.GraphVisitorBase.VisitChildren(IObjectNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 94
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitChildren(IObjectNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 73
   at Stride.Core.Quantum.GraphVisitorBase.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 70
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 42
   at Stride.Core.Quantum.GraphVisitorBase.VisitReference(IGraphNode referencer, ObjectReference reference) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 170
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitReference(IGraphNode referencer, ObjectReference reference) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 93
   at Stride.Core.Quantum.GraphVisitorBase.VisitMemberTarget(IMemberNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 130
   at Stride.Core.Quantum.GraphVisitorBase.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 76
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 42
   at Stride.Core.Quantum.GraphVisitorBase.VisitChildren(IObjectNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 94
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitChildren(IObjectNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 73
   at Stride.Core.Quantum.GraphVisitorBase.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 70
   at Stride.Core.Quantum.GraphNodeLinker.GraphNodeLinkerVisitor.VisitNode(IGraphNode node) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 42
   at Stride.Core.Quantum.GraphVisitorBase.Visit(IGraphNode node, MemberNode memberNode, GraphNodePath initialPath) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphVisitorBase.cs:line 50
   at Stride.Core.Quantum.GraphNodeLinker.LinkGraph(IGraphNode sourceNode, IGraphNode targetNode) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\presentation\Stride.Core.Quantum\GraphNodeLinker.cs:line 130
   at Stride.Core.Assets.Quantum.AssetPropertyGraph.LinkToBase(IAssetNode sourceRootNode, IAssetNode targetRootNode) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets.Quantum\AssetPropertyGraph.cs:line 523
   at Stride.Core.Assets.Quantum.AssetPropertyGraph.RefreshBase() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets.Quantum\AssetPropertyGraph.cs:line 203
   at Stride.Core.Assets.Quantum.AssetCompositeHierarchyPropertyGraph`2.RefreshBase() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets.Quantum\AssetCompositeHierarchyPropertyGraph.cs:line 349
   at Stride.Core.Assets.Quantum.AssetPropertyGraph.Initialize() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\assets\Stride.Core.Assets.Quantum\AssetPropertyGraph.cs:line 177
   at Stride.Core.Assets.Editor.ViewModel.AssetViewModel.Initialize() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Core.Assets.Editor\ViewModel\AssetViewModel.cs:line 280
   at Stride.Assets.Presentation.ViewModel.SceneViewModel.Initialize() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Assets.Presentation\ViewModel\SceneViewModel.cs:line 133
   at Stride.Core.Assets.Editor.ViewModel.SessionViewModel.<>c.<ProcessAddedPackages>b__214_1(AssetViewModel x) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Core.Assets.Editor\ViewModel\SessionViewModel.cs:line 1298
   at Stride.Core.Extensions.EnumerableExtensions.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\Extensions\EnumerableExtensions.cs:line 57
   at Stride.Core.Assets.Editor.ViewModel.SessionViewModel.ProcessAddedPackages(IEnumerable`1 packages) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Core.Assets.Editor\ViewModel\SessionViewModel.cs:line 1298
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

GPU0.AdapterCompatibility: Intel Corporation
GPU0.AdapterDACType: Internal
GPU0.AdapterRAM: 1073741824
GPU0.Availability: 3
GPU0.Caption: Intel(R) UHD Graphics
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 1920
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 60
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 1080
GPU0.Description: Intel(R) UHD Graphics
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20220403000000.000000-000
GPU0.DriverVersion: 30.0.101.1692
GPU0.InfFilename: oem232.inf
GPU0.InfSection: iTGLD_w10_DS
GPU0.InstalledDisplayDrivers: C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_ca528a70cdfef104\igdumdim64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_ca528a70cdfef104\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_ca528a70cdfef104\igd10iumd64.dll,C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_ca528a70cdfef104\igd12umd64.dll
GPU0.MaxRefreshRate: 60
GPU0.MinRefreshRate: 48
GPU0.Monochrome: False
GPU0.Name: Intel(R) UHD Graphics
GPU0.PNPDeviceID: PCI\VEN_8086&DEV_9A60&SUBSYS_0A6A1028&REV_01\3&11583659&0&10
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: xxxx
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 1920 x 1080 x 4294967296 barev
GPU0.VideoProcessor: Intel(R) UHD Graphics Family
GPU1.AdapterCompatibility: NVIDIA
GPU1.AdapterDACType: Integrated RAMDAC
GPU1.AdapterRAM: 4293918720
GPU1.Availability: 3
GPU1.Caption: NVIDIA RTX A3000 Laptop GPU
GPU1.ConfigManagerErrorCode: 0
GPU1.ConfigManagerUserConfig: False
GPU1.CreationClassName: Win32_VideoController
GPU1.CurrentBitsPerPixel: 32
GPU1.CurrentHorizontalResolution: 1920
GPU1.CurrentNumberOfColors: 4294967296
GPU1.CurrentNumberOfColumns: 0
GPU1.CurrentNumberOfRows: 0
GPU1.CurrentRefreshRate: 60
GPU1.CurrentScanMode: 4
GPU1.CurrentVerticalResolution: 1080
GPU1.Description: NVIDIA RTX A3000 Laptop GPU
GPU1.DeviceID: VideoController2
GPU1.DitherType: 0
GPU1.DriverDate: 20220404000000.000000-000
GPU1.DriverVersion: 30.0.15.1236
GPU1.InfFilename: oem200.inf
GPU1.InfSection: Section239
GPU1.InstalledDisplayDrivers: C:\Windows\System32\DriverStore\FileRepository\nvdm.inf_amd64_9df84b1d08920175\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvdm.inf_amd64_9df84b1d08920175\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvdm.inf_amd64_9df84b1d08920175\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nvdm.inf_amd64_9df84b1d08920175\nvldumdx.dll
GPU1.MaxRefreshRate: 0
GPU1.Monochrome: False
GPU1.Name: NVIDIA RTX A3000 Laptop GPU
GPU1.PNPDeviceID: PCI\VEN_10DE&DEV_2xxxx
GPU1.Status: OK
GPU1.SystemCreationClassName: Win32_ComputerSystem
GPU1.VideoArchitecture: 5
GPU1.VideoMemoryType: 2
GPU1.VideoModeDescription: 1920 x 1080 x 4294967296 barev
GPU1.VideoProcessor: NVIDIA RTX A3000 Laptop GPU
Log: 
`

**Comment by Generalec** [comment]
Is there any way/tool how to debug what asset name is "corrupted"?

I have old back up so I would lost few hours work.

**Comment by Doprez** [comment]
'Stride.Assets.Models.ModelAsset' to type 'Stride.Core.Assets.AssetCompositeHierarchy` it mentions this. Unfortunately it does not mention which model asset its struggling to use. I think it would be one of the .sdm3d files in your assets folder that would be causing the problem. 

if you want to share the project I can take a closer look after Im done work.

**Comment by Generalec** [comment]
I filtred all .sdm3d files in project folder and individually deleting each file and found the problematic file. Now IDE works.

Also I tried clean project in VS and rebuild was succesfull with no any erros or info.

Thank you so much ! Problem solved.
