### ISSUE TITLE
[TextBlock] - Runing game causes segmentation fault when Graphics Api is OpenGL 

### ISSUE THREAD

**Issue by Jklawreszuk** [stride3d/stride#2189]
**Release Type**: Official Release

**Version**: Latest

**Platform(s)**: Linux/Windows, OpenGL

**Describe the bug**

After launching, the game crashes, causing a segmentation error after exactly n seconds

**To Reproduce**
1. Create JumpyJet demo
2. Target Linux platform 
3. Build / Publish the game on Windows
4. Run executable on Linux after meeting [requirements](https://doc.stride3d.net/latest/en/manual/platforms/linux/setup-and-requirements.html?tabs=freetype-ubuntu%2Copenal-ubuntu%2Csdl2-ubuntu) or Windows
5. Application should crash after few seconds

**Expected behavior**
The application should work without any problems

**My observations**

Every application that had `TextBlock` objects caused this problem. When I removed all occurrences of it (for example, in JumpyJet) the problem did not appear

**Comment by Jklawreszuk** [comment]
Update: There is something wrong with OpenGL api. Switched on Vulkan everything works fine

**Comment by NicusorN5** [comment]
Do you have any stacktrace from the segfault?

**Comment by Jklawreszuk** [comment]
@NicusorN5 No it just silently crash :(
I also updated title because it seems that OpenGL does not work properly on any platforn

**Comment by Jklawreszuk** [comment]
I don't know if it be useful, but here is the frag of dotnet-dump tool analysis 
![test](https://github.com/user-attachments/assets/6e08671b-85ae-4960-9a8f-08408a5a8731)

**Comment by Jklawreszuk** [comment]
I switched backed again to Windows and I've managed to receive stacktrace:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Silk.NET.OpenGL.GL.BufferData[[System.IntPtr, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Silk.NET.OpenGL.BufferTargetARB, UIntPtr, IntPtr ByRef, Silk.NET.OpenGL.BufferUsageARB)
   at Stride.Graphics.CommandList.MapSubresource(Stride.Graphics.GraphicsResource, Int32, Stride.Graphics.MapMode, Boolean, Int32, Int32)
   at Stride.Graphics.BatchBase`1[[Stride.Graphics.UIBatch+UIImageDrawInfo, Stride.Graphics, Version=4.2.0.2188, Culture=neutral, PublicKeyToken=null]].DrawBatchPerTextureAndPass(ElementInfo<UIImageDrawInfo>[], Int32, Int32)
   at Stride.Graphics.BatchBase`1[[Stride.Graphics.UIBatch+UIImageDrawInfo, Stride.Graphics, Version=4.2.0.2188, Culture=neutral, PublicKeyToken=null]].DrawBatchPerTexture(Stride.Graphics.Texture, ElementInfo<UIImageDrawInfo>[], Int32, Int32)
   at Stride.Graphics.BatchBase`1[[Stride.Graphics.UIBatch+UIImageDrawInfo, Stride.Graphics, Version=4.2.0.2188, Culture=neutral, PublicKeyToken=null]].FlushBatch()
   at Stride.Graphics.BatchBase`1[[Stride.Graphics.UIBatch+UIImageDrawInfo, Stride.Graphics, Version=4.2.0.2188, Culture=neutral, PublicKeyToken=null]].End()
   at Stride.Rendering.UI.UIRenderFeature.DrawInternal(Stride.Rendering.RenderDrawContext, Stride.Rendering.RenderView, Stride.Rendering.RenderViewStage, Int32, Int32)
   at Stride.Rendering.UI.UIRenderFeature.Draw(Stride.Rendering.RenderDrawContext, Stride.Rendering.RenderView, Stride.Rendering.RenderViewStage, Int32, Int32)
   at Stride.Rendering.RenderSystem.Draw(Stride.Rendering.RenderDrawContext, Stride.Rendering.RenderView, Stride.Rendering.RenderStage)
   at JumpyJet.JumpyJetRenderer.DrawCore(Stride.Rendering.RenderContext, Stride.Rendering.RenderDrawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(Stride.Rendering.RenderDrawContext)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawInner(Stride.Rendering.RenderDrawContext)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(Stride.Rendering.RenderContext, Stride.Rendering.RenderDrawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(Stride.Rendering.RenderDrawContext)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(Stride.Rendering.RenderDrawContext)
   at Stride.Rendering.RendererBase.Draw(Stride.Rendering.RenderDrawContext)
   at Stride.Engine.SceneSystem.Draw(Stride.Games.GameTime)
   at Stride.Games.GameSystemCollection.Draw(Stride.Games.GameTime)
   at Stride.Games.GameBase.Draw(Stride.Games.GameTime)
   at Stride.Games.GameBase.RawTick(System.TimeSpan, Int32, Single, Boolean)
   at Stride.Games.GameBase.RawTickProducer()
   at Stride.Games.GameBase.Tick()
   at Stride.Games.GamePlatform.Tick()
   at Stride.Games.GamePlatform.OnRunCallback()
   at Stride.Games.GameWindowSDL+<>c__DisplayClass17_0.<Run>b__0()
   at Stride.Games.SDLMessageLoop.Run(Stride.Graphics.SDL.Window, RenderCallback)
   at Stride.Games.GameWindowSDL.Run()
   at Stride.Games.GamePlatform.Run(Stride.Games.GameContext)
   at Stride.Games.GameBase.Run(Stride.Games.GameContext)
   at Program.<Main>$(System.String[])
Segmentation fault
```

**Comment by Jklawreszuk** [comment]
I tried to debug code for a couple of days and I still dont understand why It crashes. In my case adding `if (mapMode == MapMode.WriteDiscard && buffer.BufferId == 11)` for `CommandList.OpenGL.cs -------> MapSubresource (line 940)`  was fixing an issue

**Comment by Jklawreszuk** [comment]
BufferId == 11 was ArrayBuffer in my case

**Comment by AbdallahFH** [comment]
So what is the problem now if you have fixed it?

**Comment by Jklawreszuk** [comment]
this is just a workaround
