### ISSUE TITLE
Winforms crash on startup

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#2455]
**Release Type**: Official Release

**Version**: 4.2.0.2188

**Platform(s)**: Windows

**Describe the bug**
`Publish Trimmable` seems to remove something that Winforms needs to properly function.

**To Reproduce**
1. use a default project
2. publish with the trimmable option set to true `Publish Trimmable`

**Expected behavior**
Crash bad. No crash good.

**Log and callstacks**
```
System.InvalidCastException: Specified cast is not valid.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode, IntPtr errorInfo)
   at Windows.Win32.Foundation.HRESULT.ThrowOnFailure(IntPtr errorInfo)
   at Windows.Win32.ComHelpers.GetComPointer[T](Object object)
   at Windows.Win32.ComHelpers.GetComScope[T](Object object)
   at System.Windows.Forms.RichTextBox.UpdateOleCallback()
   at System.Windows.Forms.RichTextBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Additional context**
This was found by Discord user DraftedDev and discussed in Discord (https://discord.com/channels/500285081265635328/500292370923913222/1286008639303192628)

Apparently the `Trimmable` option only affects Winforms as SDL worked.

**Comment by Kryptos-FR** [comment]
For context, Winforms is not completely trim compatible. Tracking issue: https://github.com/dotnet/winforms/issues/4649. WPF has the same problem: https://github.com/dotnet/wpf/issues/3811.
