### ISSUE TITLE
FlexibleProcessing runs in GameStudio always

### ISSUE THREAD

**Issue by Doprez** [stride3d/stride#2532]
**Release Type**: Official Release

**Version**: 4.2.0.2267

**Platform(s)**: Windows

**Describe the bug**
It seems like the bug is related to the Editor trying to run the `FlexibleProcessor` for `ISimulation` components. 

**To Reproduce**
1. Open the sample from https://github.com/stride3d/stride/tree/master/sources/engine/Stride.BepuPhysics/Stride.BepuPhysics.Demo in GameStudio
2. Open Scene number 9
3. witness massive slowdowns and an initial error message trying to use the bepu sim

**Expected behavior**
`ISimulation` components should not run in editor unless specified.

**Log and callstacks**
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Stride.BepuPhysics.Demo.Components.Utils.Spawner.Spawn(Vector3 position, Vector3 Impulse, Vector3 ImpulsePos) in C:\dev\stride-dev\BepuDemo\BepuDemo\Stride.BepuPhysics.Demo\Components\Utils\_Spawner.cs:line 27
   at Stride.BepuPhysics.Demo.Components.Utils.SpawnerComponent.SimulationUpdate(BepuSimulation simulation, Single timeStep) in C:\dev\stride-dev\BepuDemo\BepuDemo\Stride.BepuPhysics.Demo\Components\Utils\SpawnerComponent.cs:line 52
   at Stride.BepuPhysics.BepuSimulation.Elider.Handler`1.SimulationUpdate(BepuSimulation sim, Single deltaTime) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.BepuPhysics\Stride.BepuPhysics\BepuSimulation.cs:line 915
   at Stride.BepuPhysics.BepuSimulation.Elider.SimulationUpdate(Dictionary`2 handlers, BepuSimulation sim, Single deltaTime) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.BepuPhysics\Stride.BepuPhysics\BepuSimulation.cs:line 897
   at Stride.BepuPhysics.BepuSimulation.Update(TimeSpan elapsed) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.BepuPhysics\Stride.BepuPhysics\BepuSimulation.cs:line 718
   at Stride.BepuPhysics.Systems.PhysicsGameSystem.Update(GameTime time) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.BepuPhysics\Stride.BepuPhysics\Systems\PhysicsGameSystem.cs:line 33
   at Stride.Games.GameSystemCollection.Update(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Update(GameTime gameTime) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.Editor\EditorGame\Game\EditorServiceGame.cs:line 180
```

**Comment by Doprez** [comment]
Did a bit more digging on this and the bug seems to simply be that `IProcessorBase` is always added whether in Editor or at runtime which causes the GameStudio to try and access the uninitialized Bepu Simulation.

The entry point of the bug:
https://github.com/stride3d/stride/blob/62d7fa28fabb4ee75bee04366ebac4f889ddd0f2/sources/engine/Stride.Engine/Engine/FlexibleProcessing/ProcessorManager.cs#L91
Although I assume this is an issue with all of the flexible processing features it just crashes here for the spawner example in the demo project.

Fun bug, in Scene 7 with the character you can see the character rotating when the mouse is moved over the scene view.

**Comment by Eideren** [comment]
Thanks for the report, I should have time to take a look at it this weekend
