### ISSUE TITLE
EditText UI element IsSelectionActive throws object reference error

### ISSUE THREAD

**Issue by BlackCurtainStudio** [stride3d/stride#2569]
**Release Type**: Official Release

**Version**: 4.2.0.2282

**Platform(s)**: Windows

**Describe the bug**
When enabling and focusing a EditText UI element using `IsSelectionActive = true`, the error `Object reference not set to an instance of an object` is thrown. However, the EditText element seems to be responsive and accepts input anyway.

**To Reproduce**
Repro project: https://github.com/BlackCurtainStudio/Stride-EditTextSample

**Expected behavior**
No errors should occur. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/2b8419d8-02f8-4be8-807d-63a4d99bfea8)

**Log and callstacks**
`[EditTextSample.UiScript]: Error: Object reference not set to an instance of an object.
[EditTextSample.UiScript]: Error:    at Stride.Core.ServiceRegistryExtensions.GetSafeServiceAs[T](IServiceRegistry registry) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\core\Stride.Core\ServiceRegistryExtensions.cs:line 22
   at Stride.UI.Controls.EditText.ActivateEditTextImpl() in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.UI\Controls\EditText.Direct.cs:line 125
   at Stride.UI.Controls.EditText.set_IsSelectionActive(Boolean value) in C:\BuildAgent\work\b5f46e3c4829a09e\sources\engine\Stride.UI\Controls\EditText.cs:line 160`

**Comment by TranquilAbyss** [comment]
Providing some research I did for whom ever picks this up.

**Problem**
I think this exception is happening when `UIComponent` is enabled and `IsSelectionActive = true` happens in the same frame.

**Work Around**
- Wait another frame before running `UIComponent`  `IsSelectionActive = true`
- Enable `UIComponent` from the start and avoid the problem entirely.

**Problem Explanation**
This happens due to the EditText not having a Services set until the update run. This seems to be a unique problem to EditText.Direct (not that I tested it) due to `UIElementServices.Services.GetSafeServiceAs<InputManager>();` being in EditText type Direct, but other UIElements may require it too. 
The `null` `Services` is a `IServiceRegistry` and they all get set by their parent during run time by the `UIElement.Update`,  where the parent passes their Services (aka registry) to the child. This is why running `IsSelectionActive = true` on the next frame after `UIComponent` is enabled, works.
```
protected virtual void Update(GameTime time)
{
    if (Parent != null && !Parent.UIElementServices.Equals(ref uiElementServices))
        uiElementServices = Parent.UIElementServices;
}
```

I believe the `UIRenderFeature` `DrawInternal` that kicks off this process by setting a `Page`'s rootElement which passes down Services to the children through `Update`.

**Two suggestion for solutions**

- Try to pass in the `Services` on the `UIElement` SetParent, Which may also mean before the `UIRenderFeature` `DrawInternal` as well.
- Find a different way for the code to handle `ActivateEditTextImpl` without needing to accessing `Services` early.  `DeactivateEditTextImpl` most likely wont need to change, but it could help just in case some tries to call it on the same frame.

This `UIElementServices.Services.GetSafeServiceAs<InputManager>();` appears to only be called by EditText Direct from searching the entire solution

**Comment by jonyfries** [comment]
The same code that is in the Update function is also in the getting for the UIElementServices:

`        internal UIElementServices UIElementServices
        {
            get
            {
                if (Parent != null && !Parent.UIElementServices.Equals(ref uiElementServices))
                    uiElementServices = Parent.UIElementServices;

                return uiElementServices;
            }
            set
            {
                if (Parent != null)
                    throw new InvalidOperationException("Can only assign UIElementService to the root element!");

                uiElementServices = value;
            }
        }
`

So it seems to me that the code in the Update function should be unnecessary and that this issue will occur only if the root element doesn't have a UIElementServices defined.
