### ISSUE TITLE
Errors when importing a model

### ISSUE THREAD

**Issue by oschakravarthi** [stride3d/stride#440]
1. When I try to import a model (those models are attached to this post), I am getting the below error.

Error:An exception occurred while generating the template.
Object reference not set to an instance of an object.
   at Xenko.Assets.Models.ModelAssetImporter.Import(UFile localPath, AssetImporterParameters importParameters)
   at Xenko.Assets.Presentation.Templates.ModelFromFileTemplateGenerator.CreateAssets(AssetTemplateGeneratorParameters parameters)
   at Xenko.Assets.Presentation.Templates.AssetTemplateGenerator.Run(AssetTemplateGeneratorParameters parameters)
   at Xenko.Core.Assets.Editor.Components.TemplateDescriptions.TemplateGeneratorHelper.<>c__DisplayClass0_0`1.<RunTemplateGeneratorSafe>b__0()

Info:Nothing to import.
[models.zip](https://github.com/xenko3d/xenko/files/3103634/models.zip)

**Comment by Eideren** [comment]
Tested importing the given model and it works fine, probably fixed through #458 .
