### ISSUE TITLE
Xenko.Core.Assets.CompilerApp.exe bug

### ISSUE THREAD

**Issue by Basewq** [stride3d/stride#651]
**Release Type**: GitHub

**Version**: Commit 5fd0982ad37d3c9791892423f5ee5d2f24ec1ba5

**Platform(s)**: All

**Describe the bug**
Xenko.Core.Assets.CompilerApp.exe exits with code 1 due to YAML deserialization issue.
This happens while parsing `EffectCompileLog.xkeffectlog` file.
The problem is because `ShaderMixinSource.Mixins` has changed from `List<ShaderClassSource>` to `List<ShaderClassCode>`, and I believe the YAML in `EffectCompileLog.xkeffectlog` file is not in the proper format for this change.
The list element has changed from a concrete class type to an abstract class type, but the YAML deserializer attempts to look for a deserializer of the abstract type `ShaderClassCode`.
Deleting `EffectCompileLog.xkeffectlog` file will bypass this issue.
I am unsure what the YAML file for `EffectCompileLog.xkeffectlog` should really look like in order to handle the list with abstract type, as I can't get it to regenerate the file.

**To Reproduce**
1. Create new Physics Sample project.
2. Try run the game.

**Expected behavior**
Run without issue.

**Log and callstacks**
```
Error:Unhandled exception
No serializer available for type Xenko.Shaders.ShaderClassCodeYamlProxy
   at Xenko.Core.Serialization.MemberNonSealedSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at Xenko.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at Xenko.Core.Serialization.Serializers.ListSerializer`1.Serialize(List`1& obj, ArchiveMode mode, SerializationStream stream)
   at Xenko.Core.Serialization.MemberNonSealedSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at Xenko.Core.DataSerializers.XenkoShaders_ShaderMixinSourceSerializer.Serialize(ShaderMixinSource& obj, ArchiveMode mode, SerializationStream stream)
   at Xenko.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at Xenko.Core.Serialization.MemberNonSealedSerializerObject`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at Xenko.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at Xenko.Core.Serialization.Serializers.DictionaryAllSerializer`3.Serialize(TDictionary& obj, ArchiveMode mode, SerializationStream stream)
   at Xenko.Core.Serialization.SerializerExtensions.Serialize[T](SerializationStream stream, T& obj, ArchiveMode mode)
   at Xenko.Core.Serialization.SerializerExtensions.Write[T](SerializationStream stream, T obj)
   at Xenko.Shaders.ShaderMixinObjectId.ComputeInternal(String effectName, CompilerParameters compilerParameters)
   at Xenko.Shaders.ShaderMixinObjectId.Compute(String effectName, CompilerParameters compilerParameters)
   at Xenko.Shaders.Compiler.EffectCompileRequest.GetHashCode()
   at System.Collections.Generic.GenericEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xenko.Core.IO.DictionaryStore`2.AddLoaded(KeyValuePair`2 item)
   at Xenko.Core.IO.Store`1.RefreshData(Int64 fileSize)
   at Xenko.Core.IO.Store`1.LoadNewValues()
   at Xenko.Assets.Effect.EffectLogAssetCompiler.Prepare(AssetCompilerContext context, AssetItem assetItem, String targetUrlInStorage, AssetCompilerResult result)
   at Xenko.Core.Assets.Compiler.AssetCompilerBase.Prepare(AssetCompilerContext context, AssetItem assetItem)
   at Xenko.Core.Assets.Compiler.AssetDependenciesCompiler.Prepare(AssetCompilerResult finalResult, AssetCompilerContext context, AssetItem assetItem, Type compilationContext, HashSet`1 visitedItems, Dictionary`2 compiledItems, BuildStep parentBuildStep, BuildDependencyType dependencyType)
   at Xenko.Core.Assets.Compiler.AssetDependenciesCompiler.PrepareMany(AssetCompilerContext context, List`1 assetItems)
   at Xenko.Core.Assets.Compiler.PackageCompiler.Prepare(AssetCompilerContext compilerContext)
   at Xenko.Core.Assets.CompilerApp.PackageBuilder.BuildMaster()
   at Xenko.Core.Assets.CompilerApp.PackageBuilder.Build()
   at Xenko.Core.Assets.CompilerApp.PackageBuilderApp.Run(String[] args)
```

**Workaround**
Delete `EffectCompileLog.xkeffectlog` file to avoid this issue.

**Comment by Basewq** [comment]
Fixed in b37250385a6820c91c31008ee638fdbd633ebff6
