### ISSUE TITLE
Xenko cant install bec of visual studio ERROR 1

### ISSUE THREAD

**Issue by MuktadaCreations** [stride3d/stride#653]
when I try to install xenko, just after downloading all the needed files xenko ask for an administrator request access for visual studio it does that a couple of times intel it starts it after starting it immediately goes to the modify tap and after that it completely shuts down VS the  and says something about error 1 in a VS massage there is a video to see https://youtu.be/hUsp1EyGASE

P.S. I have visual studio 2017, 2019 and it does opens the modify window and I don't have .NET thing in it bec it's huge, if I can manually install what xenko need's please tell me

**Comment by Kryptos-FR** [comment]
Please look at the documentation:
* https://doc.xenko.com/latest/en/manual/get-started/install-xenko.html
* https://doc.xenko.com/latest/en/manual/troubleshooting/xenko-doesnt-run.html

Also, in the video ti is clear that you are preventing the installer to complete its work. MSBuild Tools is part of the requirements for Stride (new name of Xenko), so you need to let it install or update necessary files.

**Comment by arcazrael** [comment]
Before installing xenko.
-Checks if visual studio install has any updates.
-Open visual studio install, check if it opens without a problem
-Install visual studio tool 2017

I'm using xenko 3.1 and visual studio 2019 community

**Comment by RayKoopa** [comment]
This isn't working for me too since a _long_ time - I tried installing Xenko 3.1 throughout the last year and today, and it _never_ worked on multiple PC installs here.

I'm using VS2019 Enterprise 16.6 Preview 3 with Workloads ".NET desktop development", "Desktop development with C++" and ".NET Core cross-platform development", and I also tried it with older stable 2019 Community versions back in the days.

Whenever the Xenko launcher tries to install _something_ with the VS installer, the VS installer aborts with the log message
```
[7980:000a][2020-04-20T18:29:45] Running pre-check verification.
[7980:000a][2020-04-20T18:29:45] Warning: Pre-check verification: Your machine is busy installing a program other than Visual Studio.

Select Continue to install Visual Studio while the other install is running. This might cause problems with other parts of the installation.

Select Retry to continue with the Visual Studio install once the other install has completed.

Select Cancel to cancel the Visual Studio install.
```
and error log message
```
[7980:000a][2020-04-20T18:29:45] Pre-check verification failed with warning(s) :  AnotherInstallationRunning.
```
so there seems to be something wrong in the installation process of Xenko 3.1.

After that, the Xenko launcher message "The installation of Visual Studio returned with code 1. Do you want to try it again?" appears (retrying does not help, it just repeats the issue above). It also logs:
```
Error code 1 while running install package process [C:\Users\Ray\.nuget\packages\xenko.gamestudio/3.1.0.1\tools\packageinstall.exe]
Error: System.InvalidOperationException: Visual Studio 2019 install failed with error 1 at Xenko.PackageInstall.Program.CheckVisualStudioAndBuildTools() in D:\BuildAgent\work\8cafb933a54b01d0\sources\tools\Xenko.PackageInstall\Program.cs:line 105 at Xenko.PackageInstall.Program.Main(String[] args) in D:\BuildAgent\work\8cafb933a54b01d0\sources\tools\Xenko.PackageInstall\Program.cs:line 51
 at Xenko.Core.Packages.NugetStore.RunPackageInstall(String packageInstall, String arguments, ProgressReport progress) at Xenko.Core.Packages.NugetStore.OnPackageInstalled(Object sender, PackageOperationEventArgs args) at Xenko.Core.Packages.NugetStore.<InstallPackage>d51.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass550.<<Download>b_0>d.MoveNext()
```

I tried to manually install the VS2019 Build Tools as stated on https://doc.xenko.com/latest/en/manual/troubleshooting/xenko-doesnt-run.html (which is also outdated as the build tools are now listed under "Tools for Visual Studio 2019" on https://visualstudio.microsoft.com/downloads/ and not under "Other Tools and Frameworks" anymore) but it doesn't fix it either.

Xenko 3.0 does not seem to have this problem (it doesn't open a VS installer at all), though I can't really see staying with an almost 2 year old version should be the solution :(

**Comment by xwellingtonx** [comment]
> This isn't working for me too since a _long_ time - I tried installing Xenko 3.1 throughout the last year and today, and it _never_ worked on multiple PC installs here.
> 
> I'm using VS2019 Enterprise 16.6 Preview 3 with Workloads ".NET desktop development", "Desktop development with C++" and ".NET Core cross-platform development", and I also tried it with older stable 2019 Community versions back in the days.
> 
> Whenever the Xenko launcher tries to install _something_ with the VS installer, the VS installer aborts with the log message
> 
> ```
> [7980:000a][2020-04-20T18:29:45] Running pre-check verification.
> [7980:000a][2020-04-20T18:29:45] Warning: Pre-check verification: Your machine is busy installing a program other than Visual Studio.
> Select Continue to install Visual Studio while the other install is running. This might cause problems with other parts of the installation.
> Select Retry to continue with the Visual Studio install once the other install has completed.
> Select Cancel to cancel the Visual Studio install.
> ```
> 
> and error log message
> 
> ```
> [7980:000a][2020-04-20T18:29:45] Pre-check verification failed with warning(s) :  AnotherInstallationRunning.
> ```
> 
> so there seems to be something wrong in the installation process of Xenko 3.1. Btw, the VS installer logs to have been started with
> 
> ```
> [7980:0004][2020-04-20T18:29:41] Command line: "C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Hosts\Microsoft.ServiceHub.Host.CLR\vs_installerservice.exe" "desktopClr$C94B8CFE-E3FD-4BAF-A941-2866DBB566FE" "net.pipe://2CE5993F4776C6E35D7ABB475F9BF504"
> ```
> 
> After that, the Xenko launcher message "The installation of Visual Studio returned with code 1. Do you want to try it again?" appears (retrying does not help, it just repeats the issue above). It also logs:
> 
> ```
> Error code 1 while running install package process [C:\Users\Ray\.nuget\packages\xenko.gamestudio/3.1.0.1\tools\packageinstall.exe]
> Error: System.InvalidOperationException: Visual Studio 2019 install failed with error 1 at Xenko.PackageInstall.Program.CheckVisualStudioAndBuildTools() in D:\BuildAgent\work\8cafb933a54b01d0\sources\tools\Xenko.PackageInstall\Program.cs:line 105 at Xenko.PackageInstall.Program.Main(String[] args) in D:\BuildAgent\work\8cafb933a54b01d0\sources\tools\Xenko.PackageInstall\Program.cs:line 51
>  at Xenko.Core.Packages.NugetStore.RunPackageInstall(String packageInstall, String arguments, ProgressReport progress) at Xenko.Core.Packages.NugetStore.OnPackageInstalled(Object sender, PackageOperationEventArgs args) at Xenko.Core.Packages.NugetStore.<InstallPackage>d51.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass550.<<Download>b_0>d.MoveNext()
> ```
> 
> I tried to manually install the VS2019 Build Tools as stated on https://doc.xenko.com/latest/en/manual/troubleshooting/xenko-doesnt-run.html (which is also outdated as the build tools are now listed under "Tools for Visual Studio 2019" on https://visualstudio.microsoft.com/downloads/ and not under "Other Tools and Frameworks" anymore) but it doesn't fix it either.
> 
> Xenko 3.0 does not seem to have this problem (it doesn't open a VS installer at all), though I can't really see staying with an almost 2 year old version should be the solution :(

@RayKoopa, The VS Preview versions are not been detected by the Stride Launcher, see issue #11. 

Having the Preview version installed in your machine might be the cause of those exceptions.

**Comment by RayKoopa** [comment]
@xwellingtonx I'll try that, though by now I may just wait for the Stride 4 Beta since I don't really want two VS installations right now.

**Comment by tre4b** [comment]
Just adding to this.  I have the exact same problem,  I already have VS2019 community installed that I am using with Unity 2019.3.   Unity has been giving me some challenges and I saw Stride and thought that might be the C# orientated language that would work for me.  No chance to install though.

When you initially install it first asks if you want to install the latest version of the engine.  It then asks if you want to install the latest version of the VS integrations and recommends you do this.  I chose yes the first time and saw this error.  Uninstalled the launcher and tried again, same issue.  Then uninstalled and tried again this time selecting NO to installing the VS part.  The VS launcher was still called anyway and the same error happened.

![error message](https://user-images.githubusercontent.com/37894577/80312327-8f99d600-87dc-11ea-9c7f-fa311a054c80.png)

**Comment by RayKoopa** [comment]
Your issue should be resolved by starting the VS installer manually so it can update itself, according to your error message.
But yeah, there are other errors resulting in "code 1" coming from the Build Tools installer, claiming another installation is already running, while there isn't. I'm kinda sure this is not even Stride's problem; attempting to install them manually fails randomly aswell with the same error on my PC.

**Comment by xen2** [comment]
The new launcher is supposed to give much more info by fetching them from the log.
I remember having the "another installation" because of Windows Update running in the background (or maybe a reboot required, not sure about that one).

However, the most common reason is that Visual Studio Installer needs to self-update as well.
Sadly there is no official way to force it to update itself by running a command with parameters...

**Comment by tre4b** [comment]
Did the update manually and that worked.  But only so far

![image](https://user-images.githubusercontent.com/37894577/80396662-dd7e0f00-88ac-11ea-9220-15665de69725.png)
 :-(  not having much luck

**Comment by Eideren** [comment]
@tre4b Continue with this specific issue over at #673 instead

**Comment by MuktadaCreations** [comment]
Thanks everyone for helping but I just updated VS 2017 by accident and it somehow works.

**Comment by Albeoris** [comment]
Guys, we need to at least write a friendly message when such a problem occurs.

For example, if I download the installer from a link from an error, it will crash during the upgrade process, as it tries to start the package installer without command line arguments.

I had to download the installer from the official MS website, completely remove the outdated version of VS, reinstall. Only after that I solved this problem.

I think a link to KB or at least this issue will greatly help other users who have encountered a similar problem.

**Comment by xen2** [comment]
Agree, it's important to replace this with a much better error message now that we start to know the various causes (i.e. list of likely reasons and possibly ask user to run/download VS Installer with a Yes/No dialog box)

**Comment by rds1983** [comment]
I had similar problem yesterday.
I am using VS 2019 16.5.4
Stride installer runs VS installer in order to install required components, but latter fails with message like "another installation is already in progress".
I solved it following way: cloned stride3d, built "sources/tools/Stride.PackageInstall" and ran "packageinstall /install".
Afterwards Stride launcher installed Stride without issues.

**Comment by sgf** [comment]
i have the same problem
![TIM图片20200623123017](https://user-images.githubusercontent.com/2557696/85361015-53b98d80-b54d-11ea-9eab-e80146cb642d.png)

im try again and again.....but never success.

**Comment by sgf** [comment]
my vs Version:Microsoft Visual Studio Enterprise 2019 16.6.2

``` Error code 1 while running install package process [C:\Users\super\.nuget\packages\stride.gamestudio/4.0.0.1-beta04-1193\tools\packageinstall.exe]
Error: System.InvalidOperationException: Visual Studio 2019 install failed with error 1 在 Stride.PackageInstall.Program.CheckVisualStudioAndBuildTools() 位置 C:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.PackageInstall\Program.cs:行号 154 在 Stride.PackageInstall.Program.Main(String[] args) 位置 C:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.PackageInstall\Program.cs:行号 53
 at Stride.Core.Packages.NugetStore.RunPackageInstall(String packageInstall, String arguments, ProgressReport progress) at Stride.Core.Packages.NugetStore.OnPackageInstalled(Object sender, PackageOperationEventArgs args) at Stride.Core.Packages.NugetStore.InstallPackage(String packageId, PackageVersion version, ProgressReport progress) at Stride.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass55_0.<<Download>b0>d.MoveNext() ```

**Comment by JosuaSta** [comment]
I had the same problem. Exception saying that there is already an installation running on the system.
What helped for me was:
When the exception happens, leave the exception window open and open the task manager. Kill the Windows Installer Task and hit the retry button. After this the Visual Studio Installer will open up again and install the dependencies correctly.
Hope this helps ...

**Comment by xen2** [comment]
It seems widespread and hard to control/fix.
My idea is to move forward and make 4.1 .NET Core only to avoid those issues altogether.

**Comment by devjarmo** [comment]
This would still allow the targetting of .Net Framework for projects correct? I'm all in favor of fixing this issue because it's plaguing adoption--and Stride has a good influx of developers weekly. I only fear that a change will impact some of the .Net Framework library stuff I use and targetting .Net Framework with games.

**Comment by Eideren** [comment]
Here's a workaround that was posted on discord:
Use the task manager to kill the windows installer process, it should spawn a message prompt, press yes.
Not exactly sure if the requirements are installed by that point though.

**Comment by CallumWalton** [comment]
> Here's a workaround that was posted on discord:
> Use the task manager to kill the windows installer process, it should spawn a message prompt, press yes.
> Not exactly sure if the requirements are installed by that point though.

Worked brilliantly, thanks! Just had to time it right (as a temp work around I recommend this, hope the devs fix soon!)

**Comment by Mloren** [comment]
> Here's a workaround that was posted on discord:
> Use the task manager to kill the windows installer process, it should spawn a message prompt, press yes.
> Not exactly sure if the requirements are installed by that point though.

This is the only solution that worked for me. Thanks.

**Comment by Jan-Jakub-Fleiser** [comment]
i have the same problem but...
![vs](https://user-images.githubusercontent.com/35141008/103409242-8a143d00-4b6e-11eb-9a90-dec87d9d5dad.jpeg)
using visual studio 2019 adn the solution above does not work for me.

**Comment by tebjan** [comment]
@Jan-Jakub-Fleiser could you try to install Core 2.1 Developer tools in the visual studio installer? this solved it for me...

**Comment by Jan-Jakub-Fleiser** [comment]
> @Jan-Jakub-Fleiser could you try to install Core 2.1 Developer tools in the visual studio installer? this solved it for me...
sorr y but did you mean "Development Tools plus .NET Core 2.1"? either way it worked thanks.

**Comment by tebjan** [comment]
> did you mean "Development Tools plus .NET Core 2.1"

that's the one. yes! :)

**Comment by cstdbool** [comment]
> i have the same problem but...
> ![vs](https://user-images.githubusercontent.com/35141008/103409242-8a143d00-4b6e-11eb-9a90-dec87d9d5dad.jpeg)
> using visual studio 2019 adn the solution above does not work for me.

I had the same issue as @Jan-Jakub-Fleiser. Turns out that Stride installer was invoking the VS installer and build tools incorrectly. This is fixed with #988 (commit 065b78b61219b41651eb813f8b29e1767305cc09).
