### ISSUE TITLE
The editor crashes when selecting an IDE

### ISSUE THREAD

**Issue by Lastryo** [stride3d/stride#668]
**Version**: Stride.GameStudio 4.0.0.1-beta02-0926

**Platform(s)**: Windows

**Describe the bug**
The error occurs when changing the IDE in the settings, default is set to DefaultIDE, change to Visual Studio, DropDown window is set to an empty value, the next attempt to change the IDE, leads to an error

**Screenshots**
Step1: Open Settings
![image](https://user-images.githubusercontent.com/12784860/80283274-08d2f380-871f-11ea-86ef-f563987eb1c2.png)
Step2: Change to Visual Studio 2019
![image](https://user-images.githubusercontent.com/12784860/80283310-40da3680-871f-11ea-8bea-105d909f05c9.png)
Step3: Set Up empty window
![image](https://user-images.githubusercontent.com/12784860/80283336-66ffd680-871f-11ea-89bf-97f90a0ab9a3.png)
Step4: Change to DefaultIDE or Visual Studio (1 or several again)
![image](https://user-images.githubusercontent.com/12784860/80283365-9dd5ec80-871f-11ea-8947-09d8d1bfce0a.png)
Step5: Crash
![image](https://user-images.githubusercontent.com/12784860/80283385-c6f67d00-871f-11ea-9183-ebdc680eda88.png)

**Crash report**

Application: GameStudio
UserEmail: 
UserMessage: 
StrideVersion: 4.0.0.1-beta02-0926
GameStudioVersion: 4
ThreadName: Main thread
DefaultGraphicProfile: Level_11_0
OpenedAssets: 21515a9f-e8b4-41b0-a96c-1d2de6ac41d9:MainScene (Scene)
a52a18f6-eac7-3c10-0091-676a54fb0468:PlayerAnimator (Script Source Code)

LastActions: 
CurrentDirectory: E:\Programs\Stride
CommandArgs: E:\Projects\StrideProjects\newStrideGeme\newStrideGeme.sln
OsVersion: Майкрософт Windows 10 Pro 10.0.18363 x64
ProcessorCount: 8
Exception: TargetInvocationException: Адресат вызова создал исключение.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.SetValue(Object item, Object value)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Stride.GameStudio.DataBindingExceptionRethrower.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String format, Object[] args) in D:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.GameStudio\DataBindingExceptionRethrower.cs:line 62
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at MS.Internal.AvTrace.Trace(TraceEventType type, Int32 eventId, String message, String[] labels, Object[] parameters)
   at MS.Internal.TraceData.Trace(TraceEventType type, AvTraceDetails traceDetails, Object p1, Object p2)
   at System.Windows.Data.BindingExpression.UpdateSource(Object value)
   at System.Windows.Data.BindingExpressionBase.UpdateValue()
   at System.Windows.Data.BindingExpressionBase.ProcessDirty()
   at System.Windows.Data.BindingExpressionBase.Dirty()
   at System.Windows.Data.BindingExpressionBase.SetValue(DependencyObject d, DependencyProperty dp, Object value)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.Selector.UpdatePublicSelectionProperties()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   at System.Windows.Controls.ComboBox.NotifyComboBoxItemMouseUp(ComboBoxItem comboBoxItem)
   at System.Windows.Controls.ComboBoxItem.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Stride.GameStudio.Program.Main() in D:\BuildAgent\work\b5f46e3c4829a09e\sources\editor\Stride.GameStudio\Program.cs:line 159

InnerException:
  NodePresenterException: An error occurred while updating the value of the node, see the inner exception for more information.
     at Stride.Core.Presentation.Quantum.Presenters.MemberNodePresenter.UpdateValue(Object newValue)
     at Stride.Core.Presentation.Quantum.ViewModels.NodeViewModel.SetNodeValue(Object newValue)

  InnerException:
    ArgumentException: Элемент с тем же ключом уже был добавлен.
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at Stride.Core.Presentation.Quantum.ViewModels.NodeViewModel.<>c__DisplayClass97_0.<AddAssociatedData>b__0()
       at Stride.Core.Presentation.Quantum.ViewModels.NodeViewModel.ChangeAndNotify(Action changeAction, String[] propertyNames)
       at Stride.Core.Presentation.Quantum.ViewModels.NodeViewModel.FinishInitialization()
       at Stride.Core.Presentation.Quantum.ViewModels.NodeViewModel.Refresh()
       at Stride.Core.Presentation.Quantum.ViewModels.NodeViewModel.OnValueChanged()
       at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
       at Stride.Core.Quantum.MemberNode.NotifyContentChanged(MemberNodeChangeEventArgs args)
       at Stride.Core.Quantum.MemberNode.Update(Object newValue, Boolean sendNotification)
       at Stride.Core.Presentation.Quantum.Presenters.MemberNodePresenter.UpdateValue(Object newValue)

GPU0.AdapterCompatibility: NVIDIA
GPU0.AdapterDACType: Integrated RAMDAC
GPU0.AdapterRAM: 4293918720
GPU0.Availability: 3
GPU0.Caption: NVIDIA GeForce RTX 2070 SUPER
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 3440
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 59
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 1440
GPU0.Description: NVIDIA GeForce RTX 2070 SUPER
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20190724000000.000000-000
GPU0.DriverVersion: 26.21.14.3200
GPU0.InfFilename: oem5.inf
GPU0.InfSection: Section001
GPU0.InstalledDisplayDrivers: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_90685a092bcf58c7\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_90685a092bcf58c7\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_90685a092bcf58c7\nvldumdx.dll,C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_90685a092bcf58c7\nvldumdx.dll
GPU0.MaxRefreshRate: 75
GPU0.MinRefreshRate: 50
GPU0.Monochrome: False
GPU0.Name: NVIDIA GeForce RTX 2070 SUPER
GPU0.PNPDeviceID: PCI\VEN_10DE&DEV_1E84&SUBSYS_1E8410DE&REV_A1\4&3834D97&0&0008
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: DESKTOP-KD07750
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: Цвета: 3440 x 1440 x 4294967296
GPU0.VideoProcessor: GeForce RTX 2070 SUPER
Log: 1: BasicCameraController(0,0): []: Fatal: The asset BasicCameraController is missing or incorrectly indexed in the package. Please report this issue.
2: PlayerAnimator(0,0): []: Fatal: The asset PlayerAnimator is missing or incorrectly indexed in the package. Please report this issue.

**Comment by Kryptos-FR** [comment]
Could you include the content of the crash report? Ideally, attach it as a file.

Don't hesitate to remove any personal information from it. The most important part is the stack trace.

Thanks.
