### ISSUE TITLE
[Launcher] Microsoft.NET.Sdk not found

### ISSUE THREAD

**Issue by djocb** [stride3d/stride#673]
the editor is not running , the great a new projekt is not running what build you for 3d software there no running perfekly.
the vb-plugin is not running what going on by you!!!
whe i go to new projekt become this bug!!!!

Verbose:Generating MyGame4...
Verbose:Process dependencies for MyGame4...
Error:Unexpected exception while loading project [C:\Users\djocb\Documents\Stride Projects\MyGame4\MyGame4\MyGame4.csproj]
Verbose:Restore NuGet packages for MyGame4...
[C:\Users\djocb\Documents\Stride Projects\MyGame4\MyGame4\MyGame4.csproj(0,0)]: Error:Das angegebene SDK "Microsoft.NET.Sdk" wurde nicht gefunden.
[C:\Users\djocb\Documents\Stride Projects\MyGame4\MyGame4\MyGame4.csproj(0,0)]: Verbose:Generating MyGame4.Windows...
[C:\Users\djocb\Documents\Stride Projects\MyGame4\MyGame4\MyGame4.csproj(0,0)]: Error:An exception occurred while generating the template.

please help meee!!!!!!!!!!!!!!!!!!!!!

**Comment by tebjan** [comment]
https://twitter.com/gitlost

**Comment by SebastianStehle** [comment]
Being friendly motivates people to help and support you.

**Comment by Basewq** [comment]
**Error:Das angegebene SDK "Microsoft.NET.Sdk" wurde nicht gefunden.**

If you have VS2017 installed, update it.
If you don't have that or that doesn't work, ensure .NET Core SDK is installed or up to date.
Otherwise check if the solution exists in this thread https://github.com/microsoft/msbuild/issues/2532

**Comment by djocb** [comment]
Thanks, i have VB 2019 Not 2017 ?

Basewq <notifications@github.com> schrieb am Mo., 27. Apr. 2020, 16:43:

**Comment by Eideren** [comment]
Perhaps something that the launcher should validate before the user tries to launch the application

**Comment by Basewq** [comment]
@djocb As Eideren suggests, ensure both .NET Core cross-platform development + .NET desktop development are ticked.
Try following the steps in this comment and see if it'll help:
https://github.com/microsoft/msbuild/issues/4858#issuecomment-547537686

**Comment by tre4b** [comment]
I've checked I have both loaded and I have made sure everything is right up to date.  I created a new project from the launcher and this is what I got. 
![image](https://user-images.githubusercontent.com/37894577/80462454-a2242480-892e-11ea-8f4f-8a32fe9041f5.png)

 I checked in the MyGame2 directory and the .csproj file exists.

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stride.Engine" Version="4.0.0.1-beta02-0926" />

    <PackageReference Include="Stride.Video" Version="4.0.0.1-beta02-0926" />
    <PackageReference Include="Stride.Physics" Version="4.0.0.1-beta02-0926" />
    <PackageReference Include="Stride.Navigation" Version="4.0.0.1-beta02-0926" />
    <PackageReference Include="Stride.Particles" Version="4.0.0.1-beta02-0926" />
    <PackageReference Include="Stride.UI" Version="4.0.0.1-beta02-0926" />

    <PackageReference Include="Stride.Core.Assets.CompilerApp" Version="4.0.0.1-beta02-0926" IncludeAssets="build;buildTransitive" />
  </ItemGroup>
</Project>

Can't see anything wrong here.  The only thing I can think is that I am creating this in a "non standard" directory.

**Comment by tre4b** [comment]
Just an extra note.  I tried opening the .csproj directly.  That opened but would not run as this proj builds a dll.  The MyGame.Windows directory also has a .csproj, that one builds an app but is missing a project (the MyGame one).  I added this manually and from there I could open Stride and get the file to open.

Doesn't work right though pressing New does nothing,  building creates nothing and you cannot exit, you have to got to task manager and kill it.  Closer than yesterday but still far from functional.

**Comment by Basewq** [comment]
Did it not create the .sln file?

Another person also solved their MSBuild issue by using 'Repair' in the Visual Studio, but that's probably a last resort since that basically reinstalls it, I think.

**Comment by tre4b** [comment]
I have been thinking about uninstalling and reinstalling Visual Studio might be the only way.  It is just a hassle though as I use it for other things and I would like to avoid if possible.    There is no SLN file at all, I suspect that is not being created because it fails something to do with the .csproj.  Probably it is trying to link it in to a .sln.

**Comment by Basewq** [comment]
Do you have the build tools installed? eg.
![image](https://user-images.githubusercontent.com/1356956/80466818-23ac9e80-8991-11ea-8792-071797776304.png)

The biggest problem with the MSBuild is that Microsoft keeps messing around with the .NET Core SDK installation, so it keeps breaking stuff.
Just throwing other ideas skimming through google:
If you've got any older .NET Core SDKs installed (eg. v1 or v2), consider uninstalling them.
If you've got `MSBuildSDKsPath` in your environment path, ensure it's pointing to the recent .net core SDK path or maybe just remove it (and restart your machine).

**Comment by Basewq** [comment]
If you're still having issues (and haven't given up), can you provide the following info?
1. Locate your MSBuild.exe tell us what the the File version is
Should be in a place like `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe`
then right click the exe -> Properties -> Details -> File version
2. In command prompt, type
`dotnet --list-sdks`
and tell us its output

**Comment by tre4b** [comment]
Hi Basewq

I have Visual studio Build tools 16.5.4 installed, though when I have gone into the modify that check box was not checked so I have checked and will retry.  Actually almost nothing was ticked in there so I have also done .Net Core SDK and Core 3.1 just in case.

Giving that a shot now, if that does not work I will come back with the info above.

**Comment by tre4b** [comment]
So close

![image](https://user-images.githubusercontent.com/37894577/80500769-7e7cd080-8966-11ea-82a3-5315faed2284.png)

![image](https://user-images.githubusercontent.com/37894577/80501136-fd720900-8966-11ea-93ef-53c798ea9452.png)

and finally

![image](https://user-images.githubusercontent.com/37894577/80501264-25616c80-8967-11ea-89b9-e49c032a08d8.png)

**Comment by Basewq** [comment]
What's the error when it crashes?
Click the 'View report' button (you can remove any personal info)

**Comment by tre4b** [comment]
Okay,  Just did a whole lot of repair on VS got it working again with everything else and then tried the above again.  Same result so here is the content of the view report

Application: GameStudio
UserEmail: 
UserMessage: 
StrideVersion: 4.0.0.1-beta02-0926
GameStudioVersion: 4
ThreadName: EditorGameThread (MainScene)
DefaultGraphicProfile: Level_10_0
OpenedAssets: 
LastActions: 
CurrentDirectory: C:\Program Files\Stride
CommandArgs: /LauncherWindowHandle 1116200
OsVersion: Microsoft Windows 10 Pro 10.0.18363 x64
ProcessorCount: 24
Exception: IndexOutOfRangeException: Index was outside the bounds of the array.
   at Stride.Input.GameControllerDirectInput.Update(List`1 inputEvents)
   at Stride.Input.InputManager.Update(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Update(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Update(GameTime gameTime)
   at Stride.Games.GameBase.InitializeBeforeRun()
   at Stride.Games.GamePlatform.OnInitCallback()
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at Stride.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController`1.SceneGameRunThread()
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

GPU0.AdapterCompatibility: NVIDIA
GPU0.AdapterDACType: Integrated RAMDAC
GPU0.AdapterRAM: 4293918720
GPU0.Availability: 3
GPU0.Caption: NVIDIA GeForce RTX 2070 SUPER
GPU0.ConfigManagerErrorCode: 0
GPU0.ConfigManagerUserConfig: False
GPU0.CreationClassName: Win32_VideoController
GPU0.CurrentBitsPerPixel: 32
GPU0.CurrentHorizontalResolution: 5120
GPU0.CurrentNumberOfColors: 4294967296
GPU0.CurrentNumberOfColumns: 0
GPU0.CurrentNumberOfRows: 0
GPU0.CurrentRefreshRate: 59
GPU0.CurrentScanMode: 4
GPU0.CurrentVerticalResolution: 1440
GPU0.Description: NVIDIA GeForce RTX 2070 SUPER
GPU0.DeviceID: VideoController1
GPU0.DitherType: 0
GPU0.DriverDate: 20200403000000.000000-000
GPU0.DriverVersion: 26.21.14.4587
GPU0.InfFilename: oem62.inf
GPU0.InfSection: Section001
GPU0.InstalledDisplayDrivers: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_95bdb3a23d6478de\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_95bdb3a23d6478de\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_95bdb3a23d6478de\nvldumdx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_95bdb3a23d6478de\nvldumdx.dll
GPU0.MaxRefreshRate: 75
GPU0.MinRefreshRate: 29
GPU0.Monochrome: False
GPU0.Name: NVIDIA GeForce RTX 2070 SUPER
GPU0.PNPDeviceID: PCI\VEN_10DE&DEV_1EC7&SUBSYS_13AA10DE&REV_A1\4&19AA7BB9&0&0019
GPU0.Status: OK
GPU0.SystemCreationClassName: Win32_ComputerSystem
GPU0.SystemName: LARCH1
GPU0.VideoArchitecture: 5
GPU0.VideoMemoryType: 2
GPU0.VideoModeDescription: 5120 x 1440 x 4294967296 colors
GPU0.VideoProcessor: GeForce RTX 2070 SUPER
Log: 1: [SceneEditorGame]: Error: Unexpected exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Stride.Input.GameControllerDirectInput.Update(List`1 inputEvents)
   at Stride.Input.InputManager.Update(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Update(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Update(GameTime gameTime)
   at Stride.Games.GameBase.InitializeBeforeRun()
2: [SafeAction]: Fatal: Unexpected exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Stride.Input.GameControllerDirectInput.Update(List`1 inputEvents)
   at Stride.Input.InputManager.Update(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Update(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Update(GameTime gameTime)
   at Stride.Games.GameBase.InitializeBeforeRun()
   at Stride.Games.GamePlatform.OnInitCallback()
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at Stride.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController`1.SceneGameRunThread()
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0()

**Comment by Basewq** [comment]
Hmm, this is a new error.
Is this a brand new project (and which one) created after you reinstalled VS, or are you reusing the same project when it failed in your first message?

**Comment by Kryptos-FR** [comment]
```
Exception: IndexOutOfRangeException: Index was outside the bounds of the array.
at Stride.Input.GameControllerDirectInput.Update(List1 inputEvents)
```

Do you have game controllers, touch pads or other devices connected to your machine (aside from mouse and keyboard)? If so, can you try disconnecting them?

**Comment by tre4b** [comment]
I created a brand new project using the "New Game" template for this one.  I have actually created a new project after each change I made just in case the old one left something behind.  Earlier I wondered whether it might be the "New Game" template that was the issue so I tried "Template: first-person shooter.  That got to the initialising screen and then hung completely, just completely locked with the progress bar on the screen and had to be killed.

A couple of thoughts.  My machine is using a Rhyzen 3900 rather than an intel processor and it has 64gb of Ram.  Not sure if either of this could be confusing things?  Other than that just a 2070 Super.  I do have Unity loaded still so not sure if this is causing interference.  I know Unity is one of the "three" people talk about but I read about Stride and liked the ethos and sound of the engine so thought to give it a try.

I've plumped straight for the Stride 4.0 beta version so no 3.1 bits hanging around to confuse, however I'm happy to give 3.1 a shot as a baseline.  I will give it a shot with controllers unplugged.

**Comment by tre4b** [comment]
And

![image](https://user-images.githubusercontent.com/37894577/80582851-542f1f80-8a07-11ea-8267-fd7ac1c9fbb2.png)

tada.  I have a foot controller, 3 button USB device.  Unplugged that and it all worked.   Before doing that I tried the JumpJet template and that kept failing to build

![JumpyJet Error](https://user-images.githubusercontent.com/37894577/80582962-7c1e8300-8a07-11ea-9b19-6bac974cb5a6.png)

Captured the error screen and looking at the info seemed to be all about game controllers, at which point I remembered your request.

Can I help you with info to try and resolve this as an overall issue rather than just remove the controller to use the engine?  Others may use a similar device as it is a cheap way of getting extra buttons for jumping ;-)

**Comment by Eideren** [comment]
@tre4b Let's move discussion over that particular issue to #678 

Now as for the main issue I'll resume what users above this message have done to solve it:
* Update VS 2017 to the latest version if you have it installed.
* If you don't have any visual studio installed and you don't want it install [build tools for visual studio 2019](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) instead
* Make sure that you have installed that (VS 2017, 2019 or build tools) with the following workloads: 
   * .NET Core cross-platform development
   * .NET desktop development
   * In the components tab .Net Core SDK ( it should have been ticked when enabling .NET Core cross-platform development but make sure that it is. )
   * In the components tab .Net Core 3.1
* Repair them (VS 2017, 2019 or build tools)

I'm not closing this off, we should make sure that users of the launcher don't experience this issue in the first place, either through making sure and installing requirements, repairing corrupted dot net installation or detecting and guiding users into solving it themselves within the launcher or gamestudio.

**Comment by xen2** [comment]
Lot has happened since then.
Let's reopen or create new issue if it still happens.
