### ISSUE TITLE
[Input] Direct input controller OutOfRange

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#678]
**Release Type**: Launcher

**Version**: 4.0

**Platform(s)**: Windows, build and editor

**Describe the bug**
Exceptions are being thrown in [GameControllerDirectInput.cs](https://github.com/stride3d/stride/blob/master/sources/engine/Stride.Input/Windows/GameControllerDirectInput.cs#L142)'s update

**To Reproduce**
1. Generate 'New Game' template.
2. Connect non-standard direct input USB device.

**Expected behavior**
Append input from DI devices successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/5742236/80591390-ea6e4000-8a1d-11ea-8e6f-20e7b7c31df4.png)

**Log and callstacks**
```
Exception: IndexOutOfRangeException: Index was outside the bounds of the array.
   at Stride.Input.GameControllerDirectInput.Update(List`1 inputEvents)
   at Stride.Input.InputManager.Update(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Update(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Update(GameTime gameTime)
   at Stride.Games.GameBase.InitializeBeforeRun()
   at Stride.Games.GamePlatform.OnInitCallback()
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at Stride.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController`1.SceneGameRunThread()
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
```
[SceneEditorGame]: Error: Unexpected exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Stride.Input.GameControllerDirectInput.Update(List`1 inputEvents)
   at Stride.Input.InputManager.Update(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Update(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Update(GameTime gameTime)
   at Stride.Games.GameBase.InitializeBeforeRun()
[SafeAction]: Fatal: Unexpected exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Stride.Input.GameControllerDirectInput.Update(List`1 inputEvents)
   at Stride.Input.InputManager.Update(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Update(GameTime gameTime)
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Update(GameTime gameTime)
   at Stride.Games.GameBase.InitializeBeforeRun()
   at Stride.Games.GamePlatform.OnInitCallback()
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at Stride.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController`1.SceneGameRunThread()
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0()
```

**Additional context**
Initially brought up here https://github.com/stride3d/stride/issues/673#issuecomment-621101365
More context from @tre4b
> I have a foot controller, 3 button USB device. Unplugged that and it all worked.

**Comment by Eideren** [comment]
@tre4b 
Could you run that project with VS, wait for the exception to break and send us a screenshot of the [autos window](https://docs.microsoft.com/en-us/visualstudio/debugger/autos-and-locals-windows?view=vs-2019), within ``game`` > ``Input`` unfold properties like in this screenshot:
![image](https://user-images.githubusercontent.com/5742236/80597939-e136a080-8a28-11ea-8712-bb366650b6e9.png)

**Comment by tre4b** [comment]
No problem 

![image](https://user-images.githubusercontent.com/37894577/80620175-8e1b1880-8a3d-11ea-9516-cba065ac05b6.png)
![image](https://user-images.githubusercontent.com/37894577/80620260-aab75080-8a3d-11ea-8c53-55432c154c14.png)

I have Two controllers one of which has no drivers loaded at this time.  What the other one is I have no idea!  Possibly the G502 Mouse software fakes a controller?

**Comment by Eideren** [comment]
@tre4b could you disconnect those that don't cause a crash ? I'll also need those ``AxisInfos.Offset`` and ``Source.Devices.Values.*`` unfolded like in the screenshot. Sorry that I'm making you go through this.

**Comment by tre4b** [comment]
Okay not a problem.  I've unplugged all but still three of them show up.  All have Name "2 axis 8 Button gamepad".  Weird because I've never owned one of them ;-)  Only one shows the axis information.

![image](https://user-images.githubusercontent.com/37894577/80627347-aa23b780-8a47-11ea-8a61-3d57626e09ac.png)

Then

![image](https://user-images.githubusercontent.com/37894577/80627378-b60f7980-8a47-11ea-83c7-05a821dcb67a.png)

and

![image](https://user-images.githubusercontent.com/37894577/80627405-c293d200-8a47-11ea-9927-e7da3ce49bda.png)

Also.  How do I tell if the VS plugin is installed.  The launcher does not show reinstall and I don't know how else to check.

**Comment by Eideren** [comment]
561 buttons ? That's kind of insane, I'm pretty sure directinput doesn't support such a large amount and [we certainly dont](https://github.com/stride3d/stride/blob/17bdc261f0f1ce01512d276c67e7e31c852efd22/sources/engine/Stride.Input/Windows/DirectInputState.cs#L11). Not too sure what's going on here, I'll need a bit more data from you, could you try running the exe within this archive with your devices plugged in ?
https://drive.google.com/file/d/1NAGlobsXNVXd_26CLQAjfN6PCmSFPCit/view?usp=sharing
Once the exe starts you'll have a bunch of *.txt files in that directory, send them over and I should be able to fix this.

**Comment by tre4b** [comment]
I wonder if it is some kind of bad registration of a device or two.  Under  "Sound, video and game controllers" I have only sound devices, nothing else.  I might just see if I can find a way to remove all of these.  They stay there when the controllers are not connected too.

**Comment by tre4b** [comment]
[2 axis 8 button gamepad_0.txt](https://github.com/stride3d/stride/files/4570960/2.axis.8.button.gamepad_0.txt)

[2 axis 8 button gamepad_1.txt](https://github.com/stride3d/stride/files/4570961/2.axis.8.button.gamepad_1.txt)

[2 axis 8 button gamepad_2.txt](https://github.com/stride3d/stride/files/4570962/2.axis.8.button.gamepad_2.txt)

One of my controllers is a device called a Strategic Commander, once made by Microsoft.  It uses an opensource application to control it that only works at run time.   When you run the app it connects up and works, but only then.  I'm starting to wonder if this might be the issue.    I'm going to have a dig at that.  The last file shows something massively broken ;-)

**Comment by tre4b** [comment]
Can't find anything matching in the registry :-(  Just thinking though my last purchase was a Logitech mouse that uses GHub gaming software.  I wonder if it could be this?  GHub has lots of configurations and if they did something weird with their configuration...   This being the last thing I installed and the largest ordinal in the array might make sense...

**Comment by Eideren** [comment]
Well those buttons all seem unique, I can't really tell that there's anything wrong with the objects returned by the interface besides the sheer number of them so I don't think the issue is on our side but to be frank I can't find an actual legit source explicitly mentioning that direct input supports a maximum of 128 buttons, if it does support more than that we might have to change some of SharpDX's stuff which is definitely out of my depth.
I made #696 to at least work around this issue.
