### ISSUE TITLE
Heisenbug in the 'GraphicsDeviceManager.ApplyChanges()'

### ISSUE THREAD

**Issue by HordeResurrection** [stride3d/stride#721]
**Release Type**: Official Release

**Version**: 3.1.01

**Platform(s)**: Windows 10

**Describe the bug**
I invoked `Game.GraphicsDeviceManager.ApplyChanges()` in an overriden `Game.LoadContent()` method and got a null reference exception sometimes. It seems like a race condition.

I looked at the Stride source code:
[SwapChainGraphicsPresenter.OnDestroyed](https://github.com/stride3d/stride/blob/273dfddd462fd3746569f833e1493700c070b14d/sources/engine/Stride.Graphics/Direct3D/SwapChainGraphicsPresenter.Direct3D.cs#L177)
```
        protected internal override void OnDestroyed()
        {
            // Manually update back buffer texture
            backBuffer.OnDestroyed();
            backBuffer.LifetimeState = GraphicsResourceLifetimeState.Destroyed;

            swapChain.Dispose();
            swapChain = null;

            base.OnDestroyed();
        }
```
It seems like `backBuffer` or `swapChain` has a null value.

**To Reproduce**
I don't know how to reproduce this heisenbug.
This bug is sometimes reproduced in a `Release` version of game. I haven't observed this behaviour in a `Debug` version.

**Expected behavior**
I want to change window resolution and toggle fullscreen mode in runtime soon as program starts and loads configuration files.

**Log and callstacks**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xenko.Graphics.SwapChainGraphicsPresenter.OnDestroyed()
   at Xenko.Graphics.ResumeManager.OnDestroyed()
   at Xenko.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   at Xenko.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   at Xenko.Games.GraphicsDeviceManager.ApplyChanges()
   at HordeResurrection.Game.MyGame.LoadContent()
   [...]
```
[callstack.txt](https://github.com/stride3d/stride/files/4620928/callstack.txt)

**Comment by HordeResurrection** [comment]
I performed some analysis.
It seems like `OnDestroyed()` called twise.
Because `backBuffer` can not be `null` and `swapChain` got a `null` value only in `OnDestroyed()` method

**Comment by HordeResurrection** [comment]
I moved `GraphicsDeviceManager.ApplyChanges()` to the overriden `Game.Initialize()` method. It's a more proper solution. The null referece exception gone. But it's only workaround.

Once I had a new exception immediately after `GraphicsDeviceManager.ApplyChanges()`:
```
SharpDX.SharpDXException: HRESULT: [0x887A0022], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_CURRENTLY_AVAILABLE/NotCurrentlyAvailable], Message: A resource is not available at the time of the call, but may become available later.

   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.SetFullscreenState(RawBool fullscreen, Output targetRef)
   at Xenko.Graphics.SwapChainGraphicsPresenter.CreateSwapChainForDesktop(IntPtr handle)
   at Xenko.Graphics.SwapChainGraphicsPresenter.CreateSwapChainForWindows()
   at Xenko.Graphics.SwapChainGraphicsPresenter..ctor(GraphicsDevice device, PresentationParameters presentationParameters)
   at Xenko.Games.GamePlatform.CreateDevice(GraphicsDeviceInformation deviceInformation)
   at Xenko.Games.GamePlatform.ChangeOrCreateDevice(GraphicsDevice currentDevice, GraphicsDeviceInformation deviceInformation)
   at Xenko.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   at Xenko.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   at Xenko.Games.GameBase.InitializeBeforeRun()
   at Xenko.Games.GamePlatform.OnInitCallback()
   at Xenko.Games.GameWindowWinforms.Run()
   at Xenko.Games.GameBase.Run(GameContext gameContext)
   at HordeResurrection.HordeResurrectionApp.RunGame(MyGame game)

```

I switched window to the fullscreen mode.
My gamelog says what exception caused immediately after `Game.Initialize()` and before `Game.LoadContent()`.

It seems like another race condition.

**Comment by HordeResurrection** [comment]
I created new issue regarding new exception: https://github.com/stride3d/stride/issues/724
But first exception also still live in code. It's a race condition or double disposing. I do not know.

**Comment by HordeResurrection** [comment]
Same exception (null reference in `SwapChainGraphicsPresenter.OnDestroyed()`) can be raised at the any time when full screen mode toggled.
For example. I press Alt+Tab then the game minimizing and toggle fullscreen. It cause crash anytimes:
![2020-05-15_01-40-56_TOTALCMD64](https://user-images.githubusercontent.com/65279361/82021156-1252da00-9693-11ea-9a31-2d5e80345c32.png)

**Comment by HordeResurrection** [comment]
Do not use fullscreen in exclusive mode. It's buggy.
