### ISSUE TITLE
Error loading Stride SDK in Visual Studio

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#728]
**Release Type**: Official Release
I have downloaded the stride installer fresh today.

**Version**: 4.0.0.1-beta2-0926

**Platform(s)**: N/A

**Describe the bug**
After opening Visual Studio 2019 from the GameStudio I get my solution opened properly. However, in the Output window I see:
```
Error loading Stride SDK: System.InvalidOperationException: Could not find a base address that matches scheme net.pipe for the endpoint with binding NetNamedPipeBinding. Registered base address schemes are [].
   at System.ServiceModel.ServiceHostBase.MakeAbsoluteUri(Uri relativeOrAbsoluteUri, Binding binding, UriSchemeKeyedCollection baseAddresses)
   at System.ServiceModel.ServiceHostBase.AddServiceEndpoint(String implementedContract, Binding binding, Uri address, Uri listenUri)
   at System.ServiceModel.ServiceHost.AddServiceEndpoint(Type implementedContract, Binding binding, Uri address, Uri listenUri)
   at System.ServiceModel.ServiceHost.AddServiceEndpoint(Type implementedContract, Binding binding, String address, Uri listenUri)
   at Stride.VisualStudio.BuildEngine.PackageBuildMonitorRemote..ctor(IBuildMonitorCallback buildMonitorCallback, String logPipeUrl) in D:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.VisualStudio.Commands\PackageBuildMonitorRemote.cs:line 25
   at Stride.VisualStudio.Commands.StrideCommands.StartRemoteBuildLogServer(IBuildMonitorCallback buildMonitorCallback, String logPipeUrl) in D:\BuildAgent\work\b5f46e3c4829a09e\sources\tools\Stride.VisualStudio.Commands\StrideCommands.cs:line 34
   at Stride.VisualStudio.Commands.StrideCommandsProxy.StartRemoteBuildLogServer(BuildMonitorCallback buildMonitorCallback, String logPipeUrl)
   at Stride.VisualStudio.Commands.StrideCommandsProxy.StartRemoteBuildLogServer(BuildMonitorCallback buildMonitorCallback, String logPipeUrl)
   at Stride.VisualStudio.StridePackage.<InitializeCommandProxy>d__21.MoveNext()
```

**To Reproduce**
1. Open VS from the GameStudio and wait for it to load

**Expected behavior**
No exceptions in the Output window.

**Additional context**
It doesn't seem to affect building, but is a bit unsettling for the user. I don't know what Stride features are accessible from VS via the SDK so I cannot say if it breaks anything else.

**Comment by manio143** [comment]
Fixed in 4.0.0.1-beta03-1019. Closing.
