### ISSUE TITLE
[Linux] NullReferenceException in ResourceGroupBufferUploader 

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#731]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta02-0926

**Platform(s)**: Linux 
Linux Mint 19.2 x86_64 kernel 4.15.0-99-generic
dotnet-runtime: Microsoft.NETCore.App 2.1.18

**Describe the bug**
Building a new project for Linux, and then running it results in a NullReferenceException.

**To Reproduce**
1. Create a new project with Stride for Windows and Linux
2. Run `dotnet publish -r linux-x64 -c Release` in the Linux project's folder.
3. Pull the publish folder onto a Linux machine
4. Execute NewGame.Linux from terminal
5. See the game window pop-up (just black) and disapear, leaving an exception information in the terminal

**Expected behavior**
Game launches and I can see the same thing I see when running the project on Windows (a rendered sphere).

**Log and callstacks**
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Buffer.Memmove(Byte* dest, Byte* src, UInt64 len)
   at Stride.Graphics.ResourceGroupBufferUploader.Apply(CommandList commandList, ResourceGroup[] resourceGroups, Int32 resourceGroupsOffset)
   at Stride.Rendering.EffectInstance.Apply(GraphicsContext graphicsContext)
   at Stride.Graphics.PrimitiveQuad.Draw(GraphicsContext graphicsContext, Texture texture, SamplerState samplerState, Color4 color, Nullable`1 blendState)
   at Stride.Engine.SceneSystem.RenderSplashScreen(Color4 color, BlendStateDescription blendState)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
   at Stride.Games.GameBase.Tick()
   at Stride.Games.GamePlatform.Tick()
   at Stride.Graphics.SDL.SDLMessageLoop.Run(Window form, RenderCallback renderCallback)
   at Stride.Games.GameWindowSDL.Run()
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at NewGame.Linux.NewGameApp.Main(String[] args)
```

**Additional notes**
I even tried using .NET Core 3.1, but this fails much earlier with `System.TypeInitializationException`, so I guess it's not yet supported.

**Comment by manio143** [comment]
Superseded by #902
