### ISSUE TITLE
[VR] Problems with steam vr 1.13.9 (mirror display related ?)

### ISSUE THREAD

**Issue by Faolan-Rad** [stride3d/stride#782]
with the new steamvr update VR in stride no longer works and you get this error 

[Game]: Error: Unexpected exception. SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateShaderResourceView(Resource resourceRef, Nullable`1 descRef, ShaderResourceView sRViewOut)
   at SharpDX.Direct3D11.ShaderResourceView..ctor(Device device, Resource resource, ShaderResourceViewDescription description)
   at Stride.Graphics.Texture.GetShaderResourceView(ViewType viewType, Int32 arrayOrDepthSlice, Int32 mipIndex)
   at Stride.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes)
   at Stride.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas)
   at Stride.Graphics.Texture.InitializeFrom(TextureDescription description, DataBox[] textureDatas)
   at Stride.Graphics.Texture.InitializeFromImpl(Texture2D texture, Boolean isSrgb)
   at Stride.Graphics.Texture.InitializeFromImpl(ShaderResourceView srv)
   at Stride.VirtualReality.OpenVR.GetMirrorTexture(GraphicsDevice device, Int32 eyeIndex)
   at Stride.VirtualReality.OpenVRHmd.Enable(GraphicsDevice device, GraphicsDeviceManager graphicsDeviceManager, Boolean requireMirror, Int32 mirrorWidth, Int32 mirrorHeight)
   at Stride.VirtualReality.VRDeviceSystem.OnEnabledChanged(Object sender, EventArgs eventArgs)
   at Stride.Games.GameSystemBase.OnEnabledChanged(EventArgs e)
   at Stride.Games.GameSystemBase.set_Enabled(Boolean value)
   at Stride.Rendering.Compositing.ForwardRenderer.InitializeCore()
   at Stride.Rendering.RendererCoreBase.Initialize(RenderContext context)
   at Stride.Rendering.RendererCoreBase.EnsureContext(RenderContext context)
   at Stride.Rendering.Compositing.SceneRendererBase.Collect(RenderContext context)
   at Stride.Rendering.Compositing.SceneRendererCollection.CollectCore(RenderContext context)
   at Stride.Rendering.Compositing.SceneRendererBase.Collect(RenderContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.CollectInner(RenderContext renderContext)
   at Stride.Rendering.Compositing.SceneCameraRenderer.CollectCore(RenderContext context)
   at Stride.Rendering.Compositing.SceneRendererBase.Collect(RenderContext context)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateShaderResourceView(Resource resourceRef, Nullable`1 descRef, ShaderResourceView sRViewOut)
   at SharpDX.Direct3D11.ShaderResourceView..ctor(Device device, Resource resource, ShaderResourceViewDescription description)
   at Stride.Graphics.Texture.GetShaderResourceView(ViewType viewType, Int32 arrayOrDepthSlice, Int32 mipIndex)
   at Stride.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes)
   at Stride.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas)
   at Stride.Graphics.Texture.InitializeFrom(TextureDescription description, DataBox[] textureDatas)
   at Stride.Graphics.Texture.InitializeFromImpl(Texture2D texture, Boolean isSrgb)
   at Stride.Graphics.Texture.InitializeFromImpl(ShaderResourceView srv)
   at Stride.VirtualReality.OpenVR.GetMirrorTexture(GraphicsDevice device, Int32 eyeIndex)
   at Stride.VirtualReality.OpenVRHmd.Enable(GraphicsDevice device, GraphicsDeviceManager graphicsDeviceManager, Boolean requireMirror, Int32 mirrorWidth, Int32 mirrorHeight)
   at Stride.VirtualReality.VRDeviceSystem.OnEnabledChanged(Object sender, EventArgs eventArgs)
   at Stride.Games.GameSystemBase.OnEnabledChanged(EventArgs e)
   at Stride.Games.GameSystemBase.set_Enabled(Boolean value)
   at Stride.Rendering.Compositing.ForwardRenderer.InitializeCore()
   at Stride.Rendering.RendererCoreBase.Initialize(RenderContext context)
   at Stride.Rendering.RendererCoreBase.EnsureContext(RenderContext context)
   at Stride.Rendering.Compositing.SceneRendererBase.Collect(RenderContext context)
   at Stride.Rendering.Compositing.SceneRendererCollection.CollectCore(RenderContext context)
   at Stride.Rendering.Compositing.SceneRendererBase.Collect(RenderContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.CollectInner(RenderContext renderContext)
   at Stride.Rendering.Compositing.SceneCameraRenderer.CollectCore(RenderContext context)
   at Stride.Rendering.Compositing.SceneRendererBase.Collect(RenderContext context)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()

**Comment by phr00t** [comment]
@Faolan-Rad I'm curious if you would have issues on my fork, which I've been trying to keep up to date with SteamVR: https://github.com/phr00t/FocusEngine (this won't help any with the Stride bug, though, since this crash is happening in DirectX, where I use Vulkan for VR).

**Comment by Faolan-Rad** [comment]
okay thank you that worked.

**Comment by Eideren** [comment]
Still, it shouldn't crash or at least have a more explicit exception, reopening this.

**Comment by phr00t** [comment]
Yes, that is the option and it was only a suggestion (that may have helped Faolan-Rad). I can't help you further, though, since I maintain my own fork (https://github.com/phr00t/FocusEngine) that handles this area very differently (and likely doesn't have this problem).
