### ISSUE TITLE
DebugText.Print causes a GraphicsException at graphics profile Level_9_1

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#792]
**Release Type**: GitHub

**Version**: master

**Platform(s)**: Windows

**Describe the bug**
When targeting DX 9 via `Level_9_1`:
Calling `DebugText.Print("Whatever", new Int2(10));` on the new project raises a `Stride.Graphics.GraphicsException` (details below).

**To Reproduce**
1. Create new project, select graphics profile 9.1
2. Add a SyncScript that tries to debug print something
3. Observe the game crash

**Expected behavior**
The string is printed on the screen.

**Log and callstacks**
```
Stride.Graphics.GraphicsException: Unexpected error on Present (device status: InternalError)
---> SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], 
Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags)
   at Stride.Graphics.SwapChainGraphicsPresenter.Present()
   --- End of inner exception stack trace ---
   at Stride.Graphics.SwapChainGraphicsPresenter.Present()
   at Stride.Games.GraphicsDeviceManager.Stride.Games.IGraphicsDeviceManager.EndDraw(Boolean present)
   at Stride.Games.GameBase.EndDraw(Boolean present)
   at Stride.Engine.Game.EndDraw(Boolean present)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
```

**Comment by xen2** [comment]
Curious, do you use profile 9.1 for a reason?
Asking because I was considering removing 9.x profiles in release 4.1 (or 4.2).

**Comment by manio143** [comment]
Frankly, because I was given the option to. I just thought that it was a good idea to choose the lowest available graphics profile and only upgrade if it was necessary for some features.

**Comment by xen2** [comment]
Thanks for the feedback.
Maybe I will add a `Obsolete` mention in the dropdown.
They tend to cause various issues (workaround for intel, renderdoc not working, very limited features, reduced graphics when creating game with this level as it's equivalent to mobille, etc.) and they should be avoided unless absolutely necessary.
