### ISSUE TITLE
CSharpBeginner crashes when press "linear interpolation" button

### ISSUE THREAD

**Issue by KawaiiSelbst** [stride3d/stride#821]
**Release Type**: Official Release

**Version**: 4.0.0.1-beta04-1254 (.NET Core 3.1.6)

**Platform(s)**: Windows

**Describe the bug**
When you press the menu button "Linear Interpolation", game crashes

**To Reproduce**
1. Create a new project from CSharpBeginner template.
2. Compile and run game.
3. Press "Linear Interpolation" button

**Screenshots**
![image](https://user-images.githubusercontent.com/54507994/89733746-55d59e00-da60-11ea-8b98-f8b49b906aa0.png)

**Log and callstacks**
```
[ContentManager]: Error: The asset 'Scenes/Basics/Linear Interpolation' could not be found. Asset path should be 'MyFolder/MyAssetName'. Check that the path is correct and that the asset has been included into the build.
[Game]: Error: Unexpected exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CSharpBeginner.Code.TutorialUI.BtnLoadTutorial(Object sender, RoutedEventArgs e, KeyValuePair`2 newTutorialScene)
   at CSharpBeginner.Code.TutorialUI.<>c__DisplayClass10_0.<Start>b__0(Object sender, RoutedEventArgs e)
   at Stride.UI.UIElement.PropagateRoutedEvent(RoutedEventArgs e)
   at Stride.UI.UIElement.RaiseEvent(RoutedEventArgs e)
   at Stride.UI.Controls.ButtonBase.OnTouchUp(TouchEventArgs args)
   at Stride.UI.UIElement.TouchUpClassHandler(Object sender, TouchEventArgs args)
   at Stride.UI.UIElement.PropagateRoutedEvent(RoutedEventArgs e)
   at Stride.UI.UIElement.RaiseEvent(RoutedEventArgs e)
   at Stride.Rendering.UI.UIRenderFeature.UpdateTouchEvents(Viewport& viewport, Matrix& worldViewProj, RenderUIElement state, GameTime gameTime)
   at Stride.Rendering.UI.UIRenderFeature.PickingUpdate(RenderUIElement renderUIElement, Viewport viewport, Matrix& worldViewProj, GameTime drawTime, UIElement& elementUnderMouseCursor)
   at Stride.Rendering.UI.UIRenderFeature.DrawInternal(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex)
   at Stride.Rendering.UI.UIRenderFeature.Draw(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex)
   at Stride.Rendering.RenderSystem.Draw(RenderDrawContext renderDrawContext, RenderView renderView, RenderStage renderStage)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneRendererCollection.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
System.NullReferenceException: Object reference not set to an instance of an object.
   at CSharpBeginner.Code.TutorialUI.BtnLoadTutorial(Object sender, RoutedEventArgs e, KeyValuePair`2 newTutorialScene)
   at CSharpBeginner.Code.TutorialUI.<>c__DisplayClass10_0.<Start>b__0(Object sender, RoutedEventArgs e)
   at Stride.UI.UIElement.PropagateRoutedEvent(RoutedEventArgs e)
   at Stride.UI.UIElement.RaiseEvent(RoutedEventArgs e)
   at Stride.UI.Controls.ButtonBase.OnTouchUp(TouchEventArgs args)
   at Stride.UI.UIElement.TouchUpClassHandler(Object sender, TouchEventArgs args)
   at Stride.UI.UIElement.PropagateRoutedEvent(RoutedEventArgs e)
   at Stride.UI.UIElement.RaiseEvent(RoutedEventArgs e)
   at Stride.Rendering.UI.UIRenderFeature.UpdateTouchEvents(Viewport& viewport, Matrix& worldViewProj, RenderUIElement state, GameTime gameTime)
   at Stride.Rendering.UI.UIRenderFeature.PickingUpdate(RenderUIElement renderUIElement, Viewport viewport, Matrix& worldViewProj, GameTime drawTime, UIElement& elementUnderMouseCursor)
   at Stride.Rendering.UI.UIRenderFeature.DrawInternal(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex)
   at Stride.Rendering.UI.UIRenderFeature.Draw(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex)
   at Stride.Rendering.RenderSystem.Draw(RenderDrawContext renderDrawContext, RenderView renderView, RenderStage renderStage)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneRendererCollection.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CSharpBeginner.Code.TutorialUI.BtnLoadTutorial(Object sender, RoutedEventArgs e, KeyValuePair`2 newTutorialScene)
   at CSharpBeginner.Code.TutorialUI.<>c__DisplayClass10_0.<Start>b__0(Object sender, RoutedEventArgs e)
   at Stride.UI.UIElement.PropagateRoutedEvent(RoutedEventArgs e)
   at Stride.UI.UIElement.RaiseEvent(RoutedEventArgs e)
   at Stride.UI.Controls.ButtonBase.OnTouchUp(TouchEventArgs args)
   at Stride.UI.UIElement.TouchUpClassHandler(Object sender, TouchEventArgs args)
   at Stride.UI.UIElement.PropagateRoutedEvent(RoutedEventArgs e)
   at Stride.UI.UIElement.RaiseEvent(RoutedEventArgs e)
   at Stride.Rendering.UI.UIRenderFeature.UpdateTouchEvents(Viewport& viewport, Matrix& worldViewProj, RenderUIElement state, GameTime gameTime)
   at Stride.Rendering.UI.UIRenderFeature.PickingUpdate(RenderUIElement renderUIElement, Viewport viewport, Matrix& worldViewProj, GameTime drawTime, UIElement& elementUnderMouseCursor)
   at Stride.Rendering.UI.UIRenderFeature.DrawInternal(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex)
   at Stride.Rendering.UI.UIRenderFeature.Draw(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex)
   at Stride.Rendering.RenderSystem.Draw(RenderDrawContext renderDrawContext, RenderView renderView, RenderStage renderStage)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawView(RenderContext context, RenderDrawContext drawContext, Int32 eyeIndex, Int32 eyeCount)
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneRendererCollection.DrawCore(RenderContext context, RenderDrawContext drawContext)
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext)   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context)
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context)
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context)
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime)
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime)
   at Stride.Games.GameBase.Draw(GameTime gameTime)
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame)
   at Stride.Games.GameBase.RawTickProducer()
   at Stride.Games.GameBase.Tick()
   at Stride.Games.GamePlatform.Tick()
   at Stride.Games.GamePlatform.OnRunCallback()
   at Stride.Games.WindowsMessageLoop.Run(Control form, RenderCallback renderCallback, Boolean useApplicationDoEvents)
   at Stride.Games.GameWindowWinforms.Run()
   at Stride.Games.GameBase.Run(GameContext gameContext)
   at CSharpBasics.CSharpBeginnerApp.Main(String[] args)
```

**Comment by KawaiiSelbst** [comment]
Some scenes are missing in the folder
![image](https://user-images.githubusercontent.com/54507994/89733954-af8a9800-da61-11ea-8be3-74b64c7923d4.png)

**Comment by Aggror** [comment]
I will have a look.

**Comment by poweryang1** [comment]
In void Start() method in TutorialUI.cs file,

...
tutorialScenes.Add("Linear Interpolation", "Linear Interpolation");
tutorialScenes.Add("Loading content from code", "Loading content");
tutorialScenes.Add("Instantiating prefabs", "Instantiating prefabs");
...

There are problems at that three menus.

**Comment by FlipKittyKate** [comment]
> In void Start() method in TutorialUI.cs file,
> 
> ...
> tutorialScenes.Add("Linear Interpolation", "Linear Interpolation");
> tutorialScenes.Add("Loading content from code", "Loading content");
> tutorialScenes.Add("Instantiating prefabs", "Instantiating prefabs");
> ...
> 
> There are problems at that three menus.
Because these scenes are not there at all
