### ISSUE TITLE
[Shaders] "Using the cache requires a database."

### ISSUE THREAD

**Issue by Eideren** [stride3d/stride#857]
**Release Type**: github

**Version**: Latest

**Platform(s)**: Editor

**Describe the bug**
Editor throws ``Using the cache requires a database.`` when launching a project.

**To Reproduce**
1. Build and run latest version of editor solution
2. Start a new project

**Expected behavior**
*It just works*

**Log and callstacks**
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Using the cache requires a database.
Parameter name: database
  Source=Stride.Shaders
  StackTrace:
   at Stride.Shaders.Compiler.EffectCompilerCache..ctor(EffectCompilerBase compiler, DatabaseFileProvider database, TaskSchedulerSelector taskSchedulerSelector) in E:\GitProject\xenko\sources\engine\Stride.Shaders\Compiler\EffectCompilerCache.cs:line 50
   at Stride.Shaders.Compiler.EffectCompilerFactory.CreateEffectCompiler(IVirtualFileProvider fileProvider, EffectSystem effectSystem, String packageName, EffectCompilationMode effectCompilationMode, Boolean recordEffectRequested, TaskSchedulerSelector taskSchedulerSelector, DatabaseFileProvider database) in E:\GitProject\xenko\sources\engine\Stride.Engine\Shaders.Compiler\EffectCompilerFactory.cs:line 70
   at Stride.Engine.Game.Initialize() in E:\GitProject\xenko\sources\engine\Stride.Engine\Engine\Game.cs:line 369
   at Stride.Editor.Engine.EmbeddedGame.Initialize() in E:\GitProject\xenko\sources\editor\Stride.Editor\Engine\EmbeddedGame.cs:line 34
   at Stride.Editor.EditorGame.Game.EditorServiceGame.Initialize() in E:\GitProject\xenko\sources\editor\Stride.Editor\EditorGame\Game\EditorServiceGame.cs:line 148
   at Stride.Assets.Presentation.AssetEditors.EntityHierarchyEditor.Game.EntityHierarchyEditorGame.Initialize() in E:\GitProject\xenko\sources\editor\Stride.Assets.Presentation\AssetEditors\EntityHierarchyEditor\Game\EntityHierarchyEditorGame.cs:line 225
   at Stride.Games.GameBase.InitializeBeforeRun() in E:\GitProject\xenko\sources\engine\Stride.Games\GameBase.cs:line 395
   at Stride.Games.GamePlatform.OnInitCallback() in E:\GitProject\xenko\sources\engine\Stride.Games\GamePlatform.cs:line 179
   at Stride.Games.GameWindowWinforms.Run() in E:\GitProject\xenko\sources\engine\Stride.Games\Desktop\GameWindowWinforms.cs:line 174
   at Stride.Games.GamePlatform.Run(GameContext gameContext) in E:\GitProject\xenko\sources\engine\Stride.Games\GamePlatform.cs:line 132
   at Stride.Games.GameBase.Run(GameContext gameContext) in E:\GitProject\xenko\sources\engine\Stride.Games\GameBase.cs:line 434
   at Stride.Assets.Presentation.AssetEditors.GameEditor.Services.EditorGameController`1.SceneGameRunThread() in E:\GitProject\xenko\sources\editor\Stride.Assets.Presentation\AssetEditors\GameEditor\Services\EditorGameController.cs:line 415
   at Stride.Core.Diagnostics.SafeAction.<>c__DisplayClass1_0.<Wrap>b__0() in E:\GitProject\xenko\sources\core\Stride.Core\Diagnostics\SafeAction.cs:line 30
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

  This exception was originally thrown at this call stack:
    Stride.Shaders.Compiler.EffectCompilerCache.EffectCompilerCache(Stride.Shaders.Compiler.EffectCompilerBase, Stride.Core.IO.DatabaseFileProvider, Stride.Shaders.Compiler.TaskSchedulerSelector) in EffectCompilerCache.cs
    Stride.Shaders.Compiler.EffectCompilerFactory.CreateEffectCompiler(Stride.Core.IO.IVirtualFileProvider, Stride.Rendering.EffectSystem, string, Stride.Engine.Design.EffectCompilationMode, bool, Stride.Shaders.Compiler.TaskSchedulerSelector, Stride.Core.IO.DatabaseFileProvider) in EffectCompilerFactory.cs
    Stride.Engine.Game.Initialize() in Game.cs
    Stride.Editor.Engine.EmbeddedGame.Initialize() in EmbeddedGame.cs
    Stride.Editor.EditorGame.Game.EditorServiceGame.Initialize() in EditorServiceGame.cs
    Stride.Assets.Presentation.AssetEditors.EntityHierarchyEditor.Game.EntityHierarchyEditorGame.Initialize() in EntityHierarchyEditorGame.cs
    Stride.Games.GameBase.InitializeBeforeRun() in GameBase.cs
    Stride.Games.GamePlatform.OnInitCallback() in GamePlatform.cs
    Stride.Games.GameWindowWinforms.Run() in GameWindowWinforms.cs
    Stride.Games.GamePlatform.Run(Stride.Games.GameContext) in GamePlatform.cs
[...]
```

**Additional context**
Seems to be related to #843, running a version before the merge does not throw while one immediately after does, could you take a look @azeno ?

**Comment by azeno** [comment]
Are you sure you're running on the latest? I was under the impression I fixed this in https://github.com/stride3d/stride/pull/853

**Comment by Eideren** [comment]
My bad, I forgot to fetch latest. Uou most likely did, 'will open this back if it didn't !
