### ISSUE TITLE
[Graphics] OpenGL NullReferenceException

### ISSUE THREAD

**Issue by manio143** [stride3d/stride#902]
**Release Type**: GitHub

**Version**: beta04

**Platform(s)**: Windows & Linux

**Describe the bug**
A NullReferenceException is thrown when running a game on OpenGL. A Buffer is created with BufferTarget = 0, which is an invalid value for the OpenGL library methods. Such buffer is most likely created in the `Buffer.ToStaging()` which passes `BufferFlags.None` to the `Buffer.OpenGL` constructor (`InitializeFromImpl`).
This buffer is used to get a pointer to copy data between RAM and VRAM, but because the target is 0, we're getting back a nullptr from the `GL.MapBufferRange`.

**To Reproduce**
1. Compile runtime for WindowsOpenGL
2. Compile game with `<StrideGraphicsApi>OpenGL</StrideGraphicsApi>`
3. Copy over correct version of OpenTK.dll (see #900) to the bin folder (also possibly freetype.dll and SDL2.dll to x64 folder)
4. Run game (not from VS as it will overwrite OpenTK.dll with the dummy version)

**Expected behavior**
No exception, games run normally.

**Log and callstacks**

```
var mappedConstantBuffer = commandList.MapSubresource(preallocatedBuffer, 0, MapMode.WriteDiscard);
-> mappedConstantBuffer.DataBox.DataPointer == 0
```

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Buffer.Memmove(Byte* dest, Byte* src, UInt64 len)
   at Stride.Graphics.ResourceGroupBufferUploader.Apply(CommandList commandList, ResourceGroup[] resourceGroups, Int32 resourceGroupsOffset) in D:\Documents\stride\sources\engine\Stride.Graphics\ResourceGroupBufferUploader.cs:line 90
   at Stride.Rendering.MeshRenderFeature.Draw(RenderDrawContext context, RenderView renderView, RenderViewStage renderViewStage, Int32 startIndex, Int32 endIndex) in D:\Documents\stride\sources\engine\Stride.Rendering\Rendering\MeshRenderFeature.cs:line 204
   at Stride.Rendering.RenderSystem.Draw(RenderDrawContext renderDrawContext, RenderView renderView, RenderStage renderStage) in D:\Documents\stride\sources\engine\Stride.Rendering\Rendering\RenderSystem.cs:line 341
   at Stride.Rendering.Shadows.ShadowMapRenderer.Draw(RenderDrawContext drawContext) in D:\Documents\stride\sources\engine\Stride.Rendering\Rendering\Shadows\ShadowMapRenderer.cs:line 155
   at Stride.Rendering.Compositing.ForwardRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext) in D:\Documents\stride\sources\engine\Stride.Engine\Rendering\Compositing\ForwardRenderer.cs:line 612
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context) in D:\Documents\stride\sources\engine\Stride.Rendering\Rendering\Compositing\SceneRendererBase.cs:line 39
   at Stride.Rendering.Compositing.SceneRendererCollection.DrawCore(RenderContext context, RenderDrawContext drawContext) in D:\Documents\stride\sources\engine\Stride.Rendering\Rendering\Compositing\SceneRendererCollection.cs:line 27
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context) in D:\Documents\stride\sources\engine\Stride.Rendering\Rendering\Compositing\SceneRendererBase.cs:line 39
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawInner(RenderDrawContext renderContext) in D:\Documents\stride\sources\engine\Stride.Engine\Rendering\Compositing\SceneCameraRenderer.cs:line 105
   at Stride.Rendering.Compositing.SceneCameraRenderer.DrawCore(RenderContext context, RenderDrawContext drawContext) in D:\Documents\stride\sources\engine\Stride.Engine\Rendering\Compositing\SceneCameraRenderer.cs:line 70
   at Stride.Rendering.Compositing.SceneRendererBase.Draw(RenderDrawContext context) in D:\Documents\stride\sources\engine\Stride.Rendering\Rendering\Compositing\SceneRendererBase.cs:line 39
   at Stride.Rendering.Compositing.GraphicsCompositor.DrawCore(RenderDrawContext context) in D:\Documents\stride\sources\engine\Stride.Engine\Rendering\Compositing\GraphicsCompositor.cs:line 116
   at Stride.Rendering.RendererBase.Draw(RenderDrawContext context) in D:\Documents\stride\sources\engine\Stride.Rendering\Rendering\RendererBase.cs:line 49
   at Stride.Engine.SceneSystem.Draw(GameTime gameTime) in D:\Documents\stride\sources\engine\Stride.Engine\Engine\SceneSystem.cs:line 230
   at Stride.Games.GameSystemCollection.Draw(GameTime gameTime) in D:\Documents\stride\sources\engine\Stride.Games\GameSystemCollection.cs:line 125
   at Stride.Games.GameBase.Draw(GameTime gameTime) in D:\Documents\stride\sources\engine\Stride.Games\GameBase.cs:line 780
   at Stride.Games.GameBase.RawTick(TimeSpan elapsedTimePerUpdate, Int32 updateCount, Single drawInterpolationFactor, Boolean drawFrame) in D:\Documents\stride\sources\engine\Stride.Games\GameBase.cs:line 639
   at Stride.Games.GameBase.RawTickProducer() in D:\Documents\stride\sources\engine\Stride.Games\GameBase.cs:line 572
   at Stride.Games.GameBase.Tick() in D:\Documents\stride\sources\engine\Stride.Games\GameBase.cs:line 496
   at Stride.Games.GamePlatform.Tick() in D:\Documents\stride\sources\engine\Stride.Games\GamePlatform.cs:line 187
   at Stride.Games.GamePlatform.OnRunCallback() in D:\Documents\stride\sources\engine\Stride.Games\GamePlatform.cs:line 157
   at Stride.Games.GameWindowSDL.<>c__DisplayClass17_0.<Run>b__0() in D:\Documents\stride\sources\engine\Stride.Games\SDL\GameWindowSDL.cs:line 181
   at Stride.Games.SDLMessageLoop.Run(Window form, RenderCallback renderCallback) in D:\Documents\stride\sources\engine\Stride.Games\SDL\SDLMessageLoop.cs:line 142
   at Stride.Games.GameWindowSDL.Run() in D:\Documents\stride\sources\engine\Stride.Games\SDL\GameWindowSDL.cs:line 172
   at Stride.Games.GamePlatform.Run(GameContext gameContext) in D:\Documents\stride\sources\engine\Stride.Games\GamePlatform.cs:line 133
   at Stride.Games.GameBase.Run(GameContext gameContext) in D:\Documents\stride\sources\engine\Stride.Games\GameBase.cs:line 436
   at MinimalTestProject.MinimalTestProjectApp.Main(String[] args) in D:\Documents\Stride Projects\MinimalTestProject\MinimalTestProject.Windows\MinimalTestProjectApp.cs:line 11
```

**Additional context**
Either we're misusing the staging buffer for something it's not supposed to be used for, or the OpenGL implementation of the buffer is broken and the staging buffer should be handled in a different way.

**Comment by xen2** [comment]
OpenGL is gone, closing
